# coding: utf-8
# Copyright (c) 2026, Oracle and/or its affiliates.  All rights reserved.


from __future__ import absolute_import

from .active_cluster_resources import ActiveClusterResources
from .add_member_to_role_details import AddMemberToRoleDetails
from .admin_setting import AdminSetting
from .admin_setting_collection import AdminSettingCollection
from .admin_setting_summary import AdminSettingSummary
from .adw_schema import AdwSchema
from .adw_schema_summary import AdwSchemaSummary
from .adw_table import AdwTable
from .adw_table_summary import AdwTableSummary
from .agent_card_capabilities_detail import AgentCardCapabilitiesDetail
from .agent_card_config_detail import AgentCardConfigDetail
from .agent_card_preview_response import AgentCardPreviewResponse
from .agent_card_skill_detail import AgentCardSkillDetail
from .agent_flow import AgentFlow
from .agent_flow_attachment import AgentFlowAttachment
from .agent_flow_collection import AgentFlowCollection
from .agent_flow_compute import AgentFlowCompute
from .agent_flow_dependency import AgentFlowDependency
from .agent_flow_dependency_item import AgentFlowDependencyItem
from .agent_flow_deployment import AgentFlowDeployment
from .agent_flow_deployment_collection import AgentFlowDeploymentCollection
from .agent_flow_deployment_summary import AgentFlowDeploymentSummary
from .agent_flow_detachment import AgentFlowDetachment
from .agent_flow_diagram import AgentFlowDiagram
from .agent_flow_edge import AgentFlowEdge
from .agent_flow_guardrails_collection import AgentFlowGuardrailsCollection
from .agent_flow_guardrails_summary import AgentFlowGuardrailsSummary
from .agent_flow_node import AgentFlowNode
from .agent_flow_permission_collection import AgentFlowPermissionCollection
from .agent_flow_permission_summary import AgentFlowPermissionSummary
from .agent_flow_session import AgentFlowSession
from .agent_flow_session_collection import AgentFlowSessionCollection
from .agent_flow_session_context import AgentFlowSessionContext
from .agent_flow_session_metric import AgentFlowSessionMetric
from .agent_flow_session_metrics_range import AgentFlowSessionMetricsRange
from .agent_flow_session_summary import AgentFlowSessionSummary
from .agent_flow_summary import AgentFlowSummary
from .agent_flow_validation_issue import AgentFlowValidationIssue
from .agent_flow_validation_metadata import AgentFlowValidationMetadata
from .agent_flow_validation_options import AgentFlowValidationOptions
from .agent_flow_validation_result import AgentFlowValidationResult
from .agent_flow_validation_summary import AgentFlowValidationSummary
from .agent_node import AgentNode
from .agent_provider import AgentProvider
from .aggregated_data_point import AggregatedDataPoint
from .aggregated_time_series_data_point import AggregatedTimeSeriesDataPoint
from .ai_compute_override_item import AiComputeOverrideItem
from .ai_data_platform import AiDataPlatform
from .ai_model import AiModel
from .airflow_cell_config import AirflowCellConfig
from .alh_schema import AlhSchema
from .alh_schema_summary import AlhSchemaSummary
from .alh_table import AlhTable
from .alh_table_summary import AlhTableSummary
from .allowed_tool_details import AllowedToolDetails
from .artifact_file_info import ArtifactFileInfo
from .artifact_list import ArtifactList
from .assign_agent_flow_permission_details import AssignAgentFlowPermissionDetails
from .assign_catalog_permission_details import AssignCatalogPermissionDetails
from .assign_cluster_permission_details import AssignClusterPermissionDetails
from .assign_create_workspace_permission_details import AssignCreateWorkspacePermissionDetails
from .assign_credential_permission_details import AssignCredentialPermissionDetails
from .assign_job_permission_details import AssignJobPermissionDetails
from .assign_knowledge_base_permission_details import AssignKnowledgeBasePermissionDetails
from .assign_master_catalog_permission_details import AssignMasterCatalogPermissionDetails
from .assign_recipient_permission_details import AssignRecipientPermissionDetails
from .assign_role_permission_details import AssignRolePermissionDetails
from .assign_schema_permission_details import AssignSchemaPermissionDetails
from .assign_share_permission_details import AssignSharePermissionDetails
from .assign_table_permission_details import AssignTablePermissionDetails
from .assign_tool_permission_details import AssignToolPermissionDetails
from .assign_view_permission_details import AssignViewPermissionDetails
from .assign_volume_permission_details import AssignVolumePermissionDetails
from .assign_workspace_object_permission_details import AssignWorkspaceObjectPermissionDetails
from .assign_workspace_permission_details import AssignWorkspacePermissionDetails
from .async_operation import AsyncOperation
from .async_operation_collection import AsyncOperationCollection
from .async_operation_summary import AsyncOperationSummary
from .atp_schema import AtpSchema
from .atp_schema_summary import AtpSchemaSummary
from .atp_table import AtpTable
from .atp_table_summary import AtpTableSummary
from .attach_compute_details import AttachComputeDetails
from .attach_master_catalog_to_cluster_details import AttachMasterCatalogToClusterDetails
from .attach_to_notebook_config import AttachToNotebookConfig
from .attach_workspace_object_to_cluster_details import AttachWorkspaceObjectToClusterDetails
from .attached_session import AttachedSession
from .audit_log_search_result_collection import AuditLogSearchResultCollection
from .audit_log_search_result_summary import AuditLogSearchResultSummary
from .auth import Auth
from .auto_scale import AutoScale
from .bearer_token_auth import BearerTokenAuth
from .bucket_collection import BucketCollection
from .bucket_summary import BucketSummary
from .bundle import Bundle
from .bundle_deployed_resource import BundleDeployedResource
from .bundle_deployment_status import BundleDeploymentStatus
from .bundle_overrides import BundleOverrides
from .bundle_overrides_with_path import BundleOverridesWithPath
from .bundle_validation_result import BundleValidationResult
from .bundled_resource import BundledResource
from .catalog import Catalog
from .catalog_collection import CatalogCollection
from .catalog_connection_details import CatalogConnectionDetails
from .catalog_migration_detail import CatalogMigrationDetail
from .catalog_permission_collection import CatalogPermissionCollection
from .catalog_permission_summary import CatalogPermissionSummary
from .catalog_summary import CatalogSummary
from .catalog_test_connection_details import CatalogTestConnectionDetails
from .category_config import CategoryConfig
from .chat_message import ChatMessage
from .checkout_branch_details import CheckoutBranchDetails
from .clear_outputs_details import ClearOutputsDetails
from .cluster import Cluster
from .cluster_collection import ClusterCollection
from .cluster_event import ClusterEvent
from .cluster_execution_context_availability_event import ClusterExecutionContextAvailabilityEvent
from .cluster_instance import ClusterInstance
from .cluster_library_collection import ClusterLibraryCollection
from .cluster_library_details import ClusterLibraryDetails
from .cluster_library_summary import ClusterLibrarySummary
from .cluster_log_collection import ClusterLogCollection
from .cluster_logs_summary import ClusterLogsSummary
from .cluster_patch_event import ClusterPatchEvent
from .cluster_permission_collection import ClusterPermissionCollection
from .cluster_permission_summary import ClusterPermissionSummary
from .cluster_runtime_config import ClusterRuntimeConfig
from .cluster_spec import ClusterSpec
from .cluster_state_event import ClusterStateEvent
from .cluster_summary import ClusterSummary
from .commit_push_details import CommitPushDetails
from .compute_dependency import ComputeDependency
from .compute_override_item import ComputeOverrideItem
from .conflict_resolve_details import ConflictResolveDetails
from .content import Content
from .content_moderation_category_config import ContentModerationCategoryConfig
from .content_moderation_config import ContentModerationConfig
from .content_moderation_policy import ContentModerationPolicy
from .continuous import Continuous
from .copy_agent_flow_details import CopyAgentFlowDetails
from .copy_workspace_object_details import CopyWorkspaceObjectDetails
from .create_admin_setting_details import CreateAdminSettingDetails
from .create_agent_flow_compute_details import CreateAgentFlowComputeDetails
from .create_agent_flow_details import CreateAgentFlowDetails
from .create_agent_flow_edge_details import CreateAgentFlowEdgeDetails
from .create_agent_flow_node_details import CreateAgentFlowNodeDetails
from .create_agent_flow_session_details import CreateAgentFlowSessionDetails
from .create_agent_node_details import CreateAgentNodeDetails
from .create_bundle_details import CreateBundleDetails
from .create_catalog_details import CreateCatalogDetails
from .create_cluster_details import CreateClusterDetails
from .create_connection_details import CreateConnectionDetails
from .create_content_details import CreateContentDetails
from .create_custom_tool_details import CreateCustomToolDetails
from .create_custom_tool_node_details import CreateCustomToolNodeDetails
from .create_data_lake_credential_details import CreateDataLakeCredentialDetails
from .create_data_table_details import CreateDataTableDetails
from .create_experiment_details import CreateExperimentDetails
from .create_experiment_response_details import CreateExperimentResponseDetails
from .create_experiment_run_details import CreateExperimentRunDetails
from .create_experiment_run_response_details import CreateExperimentRunResponseDetails
from .create_git_branch import CreateGitBranch
from .create_git_branch_details import CreateGitBranchDetails
from .create_git_folder_details import CreateGitFolderDetails
from .create_http_tool_details import CreateHttpToolDetails
from .create_http_tool_node_details import CreateHttpToolNodeDetails
from .create_job_details import CreateJobDetails
from .create_job_run_details import CreateJobRunDetails
from .create_knowledge_base_details import CreateKnowledgeBaseDetails
from .create_knowledge_base_job_details import CreateKnowledgeBaseJobDetails
from .create_knowledge_base_job_run_details import CreateKnowledgeBaseJobRunDetails
from .create_master_catalog_details import CreateMasterCatalogDetails
from .create_mcp_tool_node_details import CreateMcpToolNodeDetails
from .create_model_version_details import CreateModelVersionDetails
from .create_model_version_response_details import CreateModelVersionResponseDetails
from .create_nl_to_sql_tool_details import CreateNlToSqlToolDetails
from .create_or_update_bundle_overrides_details import CreateOrUpdateBundleOverridesDetails
from .create_prompt_tool_details import CreatePromptToolDetails
from .create_prompt_tool_node_details import CreatePromptToolNodeDetails
from .create_rag_tool_details import CreateRagToolDetails
from .create_rag_tool_node_details import CreateRagToolNodeDetails
from .create_recipient_details import CreateRecipientDetails
from .create_registered_model_details import CreateRegisteredModelDetails
from .create_registered_model_response_details import CreateRegisteredModelResponseDetails
from .create_role_details import CreateRoleDetails
from .create_schema_details import CreateSchemaDetails
from .create_session_details import CreateSessionDetails
from .create_setting_details import CreateSettingDetails
from .create_share_details import CreateShareDetails
from .create_spark_cluster_details import CreateSparkClusterDetails
from .create_sql_tool_details import CreateSqlToolDetails
from .create_sql_tool_node_details import CreateSqlToolNodeDetails
from .create_table_details import CreateTableDetails
from .create_tool_details import CreateToolDetails
from .create_user_setting_details import CreateUserSettingDetails
from .create_view_details import CreateViewDetails
from .create_volume_details import CreateVolumeDetails
from .create_workspace_details import CreateWorkspaceDetails
from .create_workspace_permission_collection import CreateWorkspacePermissionCollection
from .create_workspace_permission_summary import CreateWorkspacePermissionSummary
from .credential import Credential
from .credential_collection import CredentialCollection
from .credential_details import CredentialDetails
from .credential_summary import CredentialSummary
from .credential_v2 import CredentialV2
from .credential_v2_collection import CredentialV2Collection
from .credential_v2_name_and_secret_key import CredentialV2NameAndSecretKey
from .credential_v2_summary import CredentialV2Summary
from .credentials_permission_collection import CredentialsPermissionCollection
from .custom_pii_rule import CustomPiiRule
from .custom_result import CustomResult
from .custom_test_tool_result import CustomTestToolResult
from .custom_tool import CustomTool
from .custom_tool_configuration import CustomToolConfiguration
from .custom_tool_entry import CustomToolEntry
from .custom_tool_node import CustomToolNode
from .dac_endpoint_collection import DacEndpointCollection
from .dac_endpoint_summary import DacEndpointSummary
from .data_lake import DataLake
from .data_lake_cluster_collection import DataLakeClusterCollection
from .data_lake_cluster_summary import DataLakeClusterSummary
from .data_lake_metadata import DataLakeMetadata
from .dataset import Dataset
from .dataset_input import DatasetInput
from .de_provision_user_schemas_details import DeProvisionUserSchemasDetails
from .default_cluster import DefaultCluster
from .delete_experiment_details import DeleteExperimentDetails
from .delete_experiment_response_details import DeleteExperimentResponseDetails
from .delete_experiment_run_details import DeleteExperimentRunDetails
from .delete_experiment_run_response_details import DeleteExperimentRunResponseDetails
from .delete_experiment_run_tag_details import DeleteExperimentRunTagDetails
from .delete_experiment_run_tag_response_details import DeleteExperimentRunTagResponseDetails
from .delete_experiment_tag_details import DeleteExperimentTagDetails
from .delete_experiment_tag_response_details import DeleteExperimentTagResponseDetails
from .delete_model_version_details import DeleteModelVersionDetails
from .delete_model_version_response_details import DeleteModelVersionResponseDetails
from .delete_model_version_tag_details import DeleteModelVersionTagDetails
from .delete_model_version_tag_response_details import DeleteModelVersionTagResponseDetails
from .delete_registered_model_details import DeleteRegisteredModelDetails
from .delete_registered_model_response_details import DeleteRegisteredModelResponseDetails
from .delete_registered_model_tag_details import DeleteRegisteredModelTagDetails
from .delete_registered_model_tag_response_details import DeleteRegisteredModelTagResponseDetails
from .denied_topic import DeniedTopic
from .denied_topics_policy import DeniedTopicsPolicy
from .dependency import Dependency
from .depends_on import DependsOn
from .deploy_agent_flow_details import DeployAgentFlowDetails
from .deploy_bundle_details import DeployBundleDetails
from .detach_compute_details import DetachComputeDetails
from .detach_workspace_object_from_cluster_details import DetachWorkspaceObjectFromClusterDetails
from .download_cluster_logs_details import DownloadClusterLogsDetails
from .download_file_with_par_result import DownloadFileWithParResult
from .driver_config import DriverConfig
from .embedding_model_details import EmbeddingModelDetails
from .exadata_schema import ExadataSchema
from .exadata_schema_summary import ExadataSchemaSummary
from .exadata_table import ExadataTable
from .exadata_table_summary import ExadataTableSummary
from .execute_database_user_workflows_details import ExecuteDatabaseUserWorkflowsDetails
from .execute_sql_command_details import ExecuteSqlCommandDetails
from .experiment import Experiment
from .experiment_collection import ExperimentCollection
from .experiment_response import ExperimentResponse
from .experiment_run import ExperimentRun
from .experiment_run_collection import ExperimentRunCollection
from .experiment_run_data import ExperimentRunData
from .experiment_run_info import ExperimentRunInfo
from .experiment_run_inputs import ExperimentRunInputs
from .experiment_run_metric import ExperimentRunMetric
from .experiment_run_metric_history_collection import ExperimentRunMetricHistoryCollection
from .experiment_run_outputs import ExperimentRunOutputs
from .experiment_run_param import ExperimentRunParam
from .experiment_run_tag import ExperimentRunTag
from .experiment_run_tag_key import ExperimentRunTagKey
from .experiment_tag import ExperimentTag
from .experiment_tag_key import ExperimentTagKey
from .export_contents_details import ExportContentsDetails
from .export_task_run_output_details import ExportTaskRunOutputDetails
from .exported_contents import ExportedContents
from .exported_task_run_output_contents import ExportedTaskRunOutputContents
from .expression import Expression
from .external_agent_node import ExternalAgentNode
from .external_catalog_migration_result import ExternalCatalogMigrationResult
from .external_table_definition import ExternalTableDefinition
from .feature import Feature
from .feature_status_collection import FeatureStatusCollection
from .feature_status_result import FeatureStatusResult
from .feature_status_summary import FeatureStatusSummary
from .fetch_bundle_deployment_status_details import FetchBundleDeploymentStatusDetails
from .fetch_mcp_objects_details import FetchMcpObjectsDetails
from .fetch_mcp_objects_result import FetchMcpObjectsResult
from .fetch_output_details import FetchOutputDetails
from .field_info import FieldInfo
from .file_dependency import FileDependency
from .filter_types import FilterTypes
from .generate_temp_file_upload_target_response_details import GenerateTempFileUploadTargetResponseDetails
from .get_bundle_overrides_details import GetBundleOverridesDetails
from .get_experiment_run_response_details import GetExperimentRunResponseDetails
from .get_model_version_response_details import GetModelVersionResponseDetails
from .get_registered_model_response_details import GetRegisteredModelResponseDetails
from .git_account_user_setting import GitAccountUserSetting
from .git_branch import GitBranch
from .git_branch_collection import GitBranchCollection
from .git_branch_summary import GitBranchSummary
from .git_config import GitConfig
from .git_diff_detail import GitDiffDetail
from .git_diff_summary import GitDiffSummary
from .git_diff_summary_collection import GitDiffSummaryCollection
from .git_folder import GitFolder
from .git_merge_details import GitMergeDetails
from .git_operation_state import GitOperationState
from .git_pull_details import GitPullDetails
from .git_rebase_details import GitRebaseDetails
from .git_repair_work_tree_details import GitRepairWorkTreeDetails
from .git_repository import GitRepository
from .git_reset_details import GitResetDetails
from .git_restore_branch_details import GitRestoreBranchDetails
from .grouped_search_criteria import GroupedSearchCriteria
from .guardrail_node import GuardrailNode
from .guardrails_configuration import GuardrailsConfiguration
from .history_collection import HistoryCollection
from .history_summary import HistorySummary
from .http_result import HttpResult
from .http_test_tool_result import HttpTestToolResult
from .http_tool import HttpTool
from .http_tool_configuration import HttpToolConfiguration
from .http_tool_node import HttpToolNode
from .human_in_the_loop_node import HumanInTheLoopNode
from .iam_user_credential_user_setting import IamUserCredentialUserSetting
from .identity_domain_collection import IdentityDomainCollection
from .identity_domain_summary import IdentityDomainSummary
from .identity_group_collection import IdentityGroupCollection
from .identity_group_summary import IdentityGroupSummary
from .identity_user_collection import IdentityUserCollection
from .identity_user_summary import IdentityUserSummary
from .if_else_task import IfElseTask
from .infer_schema import InferSchema
from .infer_schema_column import InferSchemaColumn
from .infer_schema_properties import InferSchemaProperties
from .infer_schema_with_preview import InferSchemaWithPreview
from .init_script_path import InitScriptPath
from .input_tag import InputTag
from .install_cluster_library_details import InstallClusterLibraryDetails
from .is_principal_admin import IsPrincipalAdmin
from .is_principal_aidp_admin import IsPrincipalAidpAdmin
from .jar_task import JarTask
from .job import Job
from .job_cluster import JobCluster
from .job_collection import JobCollection
from .job_dependency import JobDependency
from .job_permission_collection import JobPermissionCollection
from .job_permission_summary import JobPermissionSummary
from .job_run import JobRun
from .job_run_collection import JobRunCollection
from .job_run_summary import JobRunSummary
from .job_summary import JobSummary
from .job_task import JobTask
from .kafka_topic_schema import KafkaTopicSchema
from .kafka_topic_schema_summary import KafkaTopicSchemaSummary
from .kb_v_hnsw_index_details import KbVHnswIndexDetails
from .kb_v_ivf_index_details import KbVIvfIndexDetails
from .kernel import Kernel
from .kernel_collection import KernelCollection
from .kernel_summary import KernelSummary
from .keyed_time_series import KeyedTimeSeries
from .knowledge_base import KnowledgeBase
from .knowledge_base_collection import KnowledgeBaseCollection
from .knowledge_base_job import KnowledgeBaseJob
from .knowledge_base_job_collection import KnowledgeBaseJobCollection
from .knowledge_base_job_run import KnowledgeBaseJobRun
from .knowledge_base_job_run_collection import KnowledgeBaseJobRunCollection
from .knowledge_base_job_run_data import KnowledgeBaseJobRunData
from .knowledge_base_job_run_summary import KnowledgeBaseJobRunSummary
from .knowledge_base_job_summary import KnowledgeBaseJobSummary
from .knowledge_base_permission_collection import KnowledgeBasePermissionCollection
from .knowledge_base_permission_summary import KnowledgeBasePermissionSummary
from .knowledge_base_source_metadata_details import KnowledgeBaseSourceMetadataDetails
from .knowledge_base_summary import KnowledgeBaseSummary
from .knowledge_base_vector_index_details import KnowledgeBaseVectorIndexDetails
from .libraries import Libraries
from .lifecycle_state import LifecycleState
from .list_experiment_runs_details import ListExperimentRunsDetails
from .list_experiments_details import ListExperimentsDetails
from .list_filter import ListFilter
from .list_logged_models_details import ListLoggedModelsDetails
from .list_permissions_with_resource_details import ListPermissionsWithResourceDetails
from .llm_config import LlmConfig
from .log_experiment_run_batch_details import LogExperimentRunBatchDetails
from .log_experiment_run_batch_response_details import LogExperimentRunBatchResponseDetails
from .log_experiment_run_inputs_details import LogExperimentRunInputsDetails
from .log_experiment_run_inputs_response_details import LogExperimentRunInputsResponseDetails
from .log_experiment_run_metric_details import LogExperimentRunMetricDetails
from .log_experiment_run_metric_response_details import LogExperimentRunMetricResponseDetails
from .log_experiment_run_model_details import LogExperimentRunModelDetails
from .log_experiment_run_model_response_details import LogExperimentRunModelResponseDetails
from .log_experiment_run_param_details import LogExperimentRunParamDetails
from .log_experiment_run_param_response_details import LogExperimentRunParamResponseDetails
from .log_group import LogGroup
from .logged_model import LoggedModel
from .logged_model_collection import LoggedModelCollection
from .logged_model_info import LoggedModelInfo
from .logged_model_order import LoggedModelOrder
from .logged_model_tag import LoggedModelTag
from .logging_config import LoggingConfig
from .manage_agent_flow_permission_details import ManageAgentFlowPermissionDetails
from .manage_audit_logs_details import ManageAuditLogsDetails
from .manage_catalog_permission_details import ManageCatalogPermissionDetails
from .manage_cluster_permission_details import ManageClusterPermissionDetails
from .manage_create_workspace_permission_details import ManageCreateWorkspacePermissionDetails
from .manage_credential_permission_details import ManageCredentialPermissionDetails
from .manage_job_permission_details import ManageJobPermissionDetails
from .manage_knowledge_base_permission_details import ManageKnowledgeBasePermissionDetails
from .manage_master_catalog_permission_details import ManageMasterCatalogPermissionDetails
from .manage_recipient_permission_details import ManageRecipientPermissionDetails
from .manage_role_permission_details import ManageRolePermissionDetails
from .manage_schema_permission_details import ManageSchemaPermissionDetails
from .manage_share_access_details import ManageShareAccessDetails
from .manage_share_data_asset_details import ManageShareDataAssetDetails
from .manage_share_permission_details import ManageSharePermissionDetails
from .manage_table_permission_details import ManageTablePermissionDetails
from .manage_tool_permission_details import ManageToolPermissionDetails
from .manage_view_permission_details import ManageViewPermissionDetails
from .manage_volume_permission_details import ManageVolumePermissionDetails
from .manage_workspace_object_permission_details import ManageWorkspaceObjectPermissionDetails
from .manage_workspace_permission_details import ManageWorkspacePermissionDetails
from .managed_table_definition import ManagedTableDefinition
from .master_catalog import MasterCatalog
from .master_catalog_collection import MasterCatalogCollection
from .master_catalog_permission_collection import MasterCatalogPermissionCollection
from .master_catalog_permission_summary import MasterCatalogPermissionSummary
from .master_catalog_summary import MasterCatalogSummary
from .mcp_object import McpObject
from .mcp_prompt_object import McpPromptObject
from .mcp_resource_object import McpResourceObject
from .mcp_result import McpResult
from .mcp_test_tool_result import McpTestToolResult
from .mcp_tool import McpTool
from .mcp_tool_configuration import McpToolConfiguration
from .mcp_tool_node import McpToolNode
from .mcp_tool_object import McpToolObject
from .memory_configuration import MemoryConfiguration
from .memory_limit_configuration import MemoryLimitConfiguration
from .memory_limit_configuration_details import MemoryLimitConfigurationDetails
from .metrics_summary import MetricsSummary
from .mkdir_details import MkdirDetails
from .model import Model
from .model_input import ModelInput
from .model_metric import ModelMetric
from .model_output import ModelOutput
from .model_param import ModelParam
from .model_parameter import ModelParameter
from .model_parameter_detail import ModelParameterDetail
from .model_parameter_response import ModelParameterResponse
from .model_summary import ModelSummary
from .model_version import ModelVersion
from .model_version_collection import ModelVersionCollection
from .model_version_deployment_job_state import ModelVersionDeploymentJobState
from .model_version_tag import ModelVersionTag
from .model_version_tag_key import ModelVersionTagKey
from .models_collection import ModelsCollection
from .modify_content_details import ModifyContentDetails
from .move_workspace_object_details import MoveWorkspaceObjectDetails
from .nested_agent_flow_node import NestedAgentFlowNode
from .new_cluster_configuration import NewClusterConfiguration
from .nl_to_sql_tool import NlToSqlTool
from .nl_to_sql_tool_configuration import NlToSqlToolConfiguration
from .nl_to_sql_tool_input_schema import NlToSqlToolInputSchema
from .no_auth import NoAuth
from .node_input import NodeInput
from .node_io import NodeIo
from .node_io_color import NodeIoColor
from .node_output import NodeOutput
from .notebook_task import NotebookTask
from .notify_cluster_event_handler_details import NotifyClusterEventHandlerDetails
from .o_auth import OAuth
from .o_auth_admin_setting import OAuthAdminSetting
from .o_auth_configuration import OAuthConfiguration
from .oac_schema import OacSchema
from .oac_schema_summary import OacSchemaSummary
from .oac_table import OacTable
from .oac_table_summary import OacTableSummary
from .object_recent_search_summary import ObjectRecentSearchSummary
from .object_search_summary import ObjectSearchSummary
from .object_suggest_summary import ObjectSuggestSummary
from .oci_logging import OciLogging
from .oci_resource_principal_auth import OciResourcePrincipalAuth
from .oracle_schema import OracleSchema
from .oracle_schema_summary import OracleSchemaSummary
from .oracle_table import OracleTable
from .oracle_table_summary import OracleTableSummary
from .output_parameter import OutputParameter
from .par_details import ParDetails
from .parameter import Parameter
from .patch_cluster_library_details import PatchClusterLibraryDetails
from .patch_session_details import PatchSessionDetails
from .perform_infer_schema_details import PerformInferSchemaDetails
from .permission_assignees import PermissionAssignees
from .permission_summary import PermissionSummary
from .permission_with_resource_details import PermissionWithResourceDetails
from .pii_category import PiiCategory
from .pii_detection_policy import PiiDetectionPolicy
from .playground_cache import PlaygroundCache
from .point import Point
from .preview_agent_flow_agent_card_details import PreviewAgentFlowAgentCardDetails
from .principals_with_workspace_access_collection import PrincipalsWithWorkspaceAccessCollection
from .principals_with_workspace_access_summary import PrincipalsWithWorkspaceAccessSummary
from .prompt_attacks_prevention_policy import PromptAttacksPreventionPolicy
from .prompt_result import PromptResult
from .prompt_test_tool_result import PromptTestToolResult
from .prompt_tool import PromptTool
from .prompt_tool_configuration import PromptToolConfiguration
from .prompt_tool_node import PromptToolNode
from .provision_user_schema_details import ProvisionUserSchemaDetails
from .purge_bundle_details import PurgeBundleDetails
from .python_task import PythonTask
from .queue import Queue
from .rag_result import RagResult
from .rag_test_tool_result import RagTestToolResult
from .rag_tool import RagTool
from .rag_tool_configuration import RagToolConfiguration
from .rag_tool_input_schema import RagToolInputSchema
from .rag_tool_node import RagToolNode
from .range_filter import RangeFilter
from .recent_resource_item import RecentResourceItem
from .recent_search_results_collection import RecentSearchResultsCollection
from .recent_searches_criteria import RecentSearchesCriteria
from .recently_accessed import RecentlyAccessed
from .recently_accessed_resource import RecentlyAccessedResource
from .recipient import Recipient
from .recipient_collection import RecipientCollection
from .recipient_permission_collection import RecipientPermissionCollection
from .recipient_permission_summary import RecipientPermissionSummary
from .recipient_summary import RecipientSummary
from .registered_model import RegisteredModel
from .registered_model_alias import RegisteredModelAlias
from .registered_model_collection import RegisteredModelCollection
from .registered_model_tag import RegisteredModelTag
from .registered_model_tag_key import RegisteredModelTagKey
from .remove_member_from_role_details import RemoveMemberFromRoleDetails
from .rename_registered_model_details import RenameRegisteredModelDetails
from .rename_registered_model_response_details import RenameRegisteredModelResponseDetails
from .rename_table_field_details import RenameTableFieldDetails
from .rename_workspace_object_details import RenameWorkspaceObjectDetails
from .repair_history import RepairHistory
from .repair_job_run_details import RepairJobRunDetails
from .reset_git_folder_state_details import ResetGitFolderStateDetails
from .restart_cluster_details import RestartClusterDetails
from .restore_experiment_details import RestoreExperimentDetails
from .restore_experiment_response_details import RestoreExperimentResponseDetails
from .restore_experiment_run_details import RestoreExperimentRunDetails
from .restore_experiment_run_response_details import RestoreExperimentRunResponseDetails
from .retrieved_chunk import RetrievedChunk
from .revoke_agent_flow_permission_details import RevokeAgentFlowPermissionDetails
from .revoke_catalog_permission_details import RevokeCatalogPermissionDetails
from .revoke_cluster_permission_details import RevokeClusterPermissionDetails
from .revoke_create_workspace_permission_details import RevokeCreateWorkspacePermissionDetails
from .revoke_credential_permission_details import RevokeCredentialPermissionDetails
from .revoke_job_permission_details import RevokeJobPermissionDetails
from .revoke_knowledge_base_permission_details import RevokeKnowledgeBasePermissionDetails
from .revoke_master_catalog_permission_details import RevokeMasterCatalogPermissionDetails
from .revoke_recipient_permission_details import RevokeRecipientPermissionDetails
from .revoke_role_permission_details import RevokeRolePermissionDetails
from .revoke_schema_permission_details import RevokeSchemaPermissionDetails
from .revoke_share_permission_details import RevokeSharePermissionDetails
from .revoke_table_permission_details import RevokeTablePermissionDetails
from .revoke_tool_permission_details import RevokeToolPermissionDetails
from .revoke_view_permission_details import RevokeViewPermissionDetails
from .revoke_volume_permission_details import RevokeVolumePermissionDetails
from .revoke_workspace_object_permission_details import RevokeWorkspaceObjectPermissionDetails
from .revoke_workspace_permission_details import RevokeWorkspacePermissionDetails
from .role import Role
from .role_assignee import RoleAssignee
from .role_collection import RoleCollection
from .role_permission_collection import RolePermissionCollection
from .role_permission_summary import RolePermissionSummary
from .role_summary import RoleSummary
from .run_output_data import RunOutputData
from .safety_policy import SafetyPolicy
from .scan import Scan
from .schedule import Schedule
from .schema import Schema
from .schema_collection import SchemaCollection
from .schema_permission_collection import SchemaPermissionCollection
from .schema_permission_summary import SchemaPermissionSummary
from .schema_summary import SchemaSummary
from .search_audit_logs_details import SearchAuditLogsDetails
from .search_cluster_logs_details import SearchClusterLogsDetails
from .search_criteria import SearchCriteria
from .search_object_type import SearchObjectType
from .search_result import SearchResult
from .search_result_summary import SearchResultSummary
from .search_results_collection import SearchResultsCollection
from .search_results_group_by_collection import SearchResultsGroupByCollection
from .secret_pair import SecretPair
from .secret_token_credential_details import SecretTokenCredentialDetails
from .service_account_credential_details import ServiceAccountCredentialDetails
from .session import Session
from .session_chat_history_collection import SessionChatHistoryCollection
from .session_chat_history_summary import SessionChatHistorySummary
from .session_collection import SessionCollection
from .session_configuration import SessionConfiguration
from .session_retention_configuration import SessionRetentionConfiguration
from .session_summary import SessionSummary
from .session_variable import SessionVariable
from .session_variable_details import SessionVariableDetails
from .set_experiment_run_tag_details import SetExperimentRunTagDetails
from .set_experiment_run_tag_response_details import SetExperimentRunTagResponseDetails
from .set_experiment_tag_details import SetExperimentTagDetails
from .set_experiment_tag_response_details import SetExperimentTagResponseDetails
from .set_model_version_tag_details import SetModelVersionTagDetails
from .set_model_version_tag_response_details import SetModelVersionTagResponseDetails
from .set_registered_model_tag_details import SetRegisteredModelTagDetails
from .set_registered_model_tag_response_details import SetRegisteredModelTagResponseDetails
from .setting import Setting
from .setting_data import SettingData
from .shape_config import ShapeConfig
from .share import Share
from .share_collection import ShareCollection
from .share_data_asset_collection import ShareDataAssetCollection
from .share_data_asset_summary import ShareDataAssetSummary
from .share_permission_collection import SharePermissionCollection
from .share_permission_summary import SharePermissionSummary
from .share_summary import ShareSummary
from .sort_details import SortDetails
from .span_details import SpanDetails
from .span_status import SpanStatus
from .spark_cluster import SparkCluster
from .spark_runtime_config import SparkRuntimeConfig
from .sql_result import SqlResult
from .sql_test_tool_result import SqlTestToolResult
from .sql_tool import SqlTool
from .sql_tool_configuration import SqlToolConfiguration
from .sql_tool_node import SqlToolNode
from .standard_schema import StandardSchema
from .standard_schema_summary import StandardSchemaSummary
from .standard_table import StandardTable
from .standard_table_summary import StandardTableSummary
from .start_cluster_details import StartClusterDetails
from .start_node import StartNode
from .state import State
from .stop_agent_flow_session_details import StopAgentFlowSessionDetails
from .stop_cluster_details import StopClusterDetails
from .subscription_details import SubscriptionDetails
from .suggest_criteria import SuggestCriteria
from .suggest_results_collection import SuggestResultsCollection
from .summarize_metrics_data_details import SummarizeMetricsDataDetails
from .summarize_metrics_response import SummarizeMetricsResponse
from .supervisor_agent_node import SupervisorAgentNode
from .sync_bundle_details import SyncBundleDetails
from .table import Table
from .table_collection import TableCollection
from .table_field_details import TableFieldDetails
from .table_permission_collection import TablePermissionCollection
from .table_permission_summary import TablePermissionSummary
from .table_property import TableProperty
from .table_summary import TableSummary
from .task import Task
from .task_execution_result import TaskExecutionResult
from .task_run import TaskRun
from .task_run_collection import TaskRunCollection
from .task_run_output import TaskRunOutput
from .task_run_retry import TaskRunRetry
from .task_run_summary import TaskRunSummary
from .test_custom_tool_details import TestCustomToolDetails
from .test_http_tool_details import TestHttpToolDetails
from .test_mcp_connection import TestMcpConnection
from .test_mcp_external_tool import TestMcpExternalTool
from .test_mcp_operation import TestMcpOperation
from .test_mcp_tool_details import TestMcpToolDetails
from .test_prompt_tool_details import TestPromptToolDetails
from .test_rag_tool_details import TestRagToolDetails
from .test_sql_tool_details import TestSqlToolDetails
from .test_tool_details import TestToolDetails
from .test_tool_param_values import TestToolParamValues
from .test_tool_result import TestToolResult
from .time_created import TimeCreated
from .time_updated import TimeUpdated
from .tool import Tool
from .tool_collection import ToolCollection
from .tool_permission_collection import ToolPermissionCollection
from .tool_permission_summary import ToolPermissionSummary
from .tool_summary import ToolSummary
from .trace_details import TraceDetails
from .trace_event import TraceEvent
from .transition_model_version_stage_details import TransitionModelVersionStageDetails
from .transition_model_version_stage_response_details import TransitionModelVersionStageResponseDetails
from .txt_file_definition import TxtFileDefinition
from .uninstall_cluster_library_details import UninstallClusterLibraryDetails
from .update_admin_setting_details import UpdateAdminSettingDetails
from .update_agent_flow_compute_details import UpdateAgentFlowComputeDetails
from .update_agent_flow_deployment_details import UpdateAgentFlowDeploymentDetails
from .update_agent_flow_deployment_metadata_details import UpdateAgentFlowDeploymentMetadataDetails
from .update_agent_flow_details import UpdateAgentFlowDetails
from .update_agent_flow_node_details import UpdateAgentFlowNodeDetails
from .update_agent_flow_session_details import UpdateAgentFlowSessionDetails
from .update_agent_flow_session_playground_cache_details import UpdateAgentFlowSessionPlaygroundCacheDetails
from .update_agent_node_details import UpdateAgentNodeDetails
from .update_catalog_details import UpdateCatalogDetails
from .update_cluster_async_operation_status_details import UpdateClusterAsyncOperationStatusDetails
from .update_cluster_details import UpdateClusterDetails
from .update_connection_details import UpdateConnectionDetails
from .update_content_details import UpdateContentDetails
from .update_custom_tool_details import UpdateCustomToolDetails
from .update_custom_tool_node_details import UpdateCustomToolNodeDetails
from .update_data_lake_credential_details import UpdateDataLakeCredentialDetails
from .update_dir_details import UpdateDirDetails
from .update_experiment_details import UpdateExperimentDetails
from .update_experiment_response_details import UpdateExperimentResponseDetails
from .update_experiment_run_details import UpdateExperimentRunDetails
from .update_experiment_run_response_details import UpdateExperimentRunResponseDetails
from .update_experiment_run_tags_details import UpdateExperimentRunTagsDetails
from .update_experiment_run_tags_response_details import UpdateExperimentRunTagsResponseDetails
from .update_experiment_tags_details import UpdateExperimentTagsDetails
from .update_experiment_tags_response_details import UpdateExperimentTagsResponseDetails
from .update_file_metadata_details import UpdateFileMetadataDetails
from .update_git_repository_details import UpdateGitRepositoryDetails
from .update_http_tool_details import UpdateHttpToolDetails
from .update_http_tool_node_details import UpdateHttpToolNodeDetails
from .update_job_details import UpdateJobDetails
from .update_knowledge_base_add_source_details import UpdateKnowledgeBaseAddSourceDetails
from .update_knowledge_base_delete_source_details import UpdateKnowledgeBaseDeleteSourceDetails
from .update_knowledge_base_details import UpdateKnowledgeBaseDetails
from .update_knowledge_base_metadata_update_details import UpdateKnowledgeBaseMetadataUpdateDetails
from .update_knowledge_base_source_update_details import UpdateKnowledgeBaseSourceUpdateDetails
from .update_knowledge_base_source_update_details_item import UpdateKnowledgeBaseSourceUpdateDetailsItem
from .update_master_catalog_details import UpdateMasterCatalogDetails
from .update_mcp_tool_node_details import UpdateMcpToolNodeDetails
from .update_model_version_details import UpdateModelVersionDetails
from .update_model_version_response_details import UpdateModelVersionResponseDetails
from .update_model_version_tags_details import UpdateModelVersionTagsDetails
from .update_model_version_tags_response_details import UpdateModelVersionTagsResponseDetails
from .update_nl_to_sql_tool_details import UpdateNlToSqlToolDetails
from .update_prompt_tool_details import UpdatePromptToolDetails
from .update_prompt_tool_node_details import UpdatePromptToolNodeDetails
from .update_rag_tool_details import UpdateRagToolDetails
from .update_rag_tool_node_details import UpdateRagToolNodeDetails
from .update_recipient_details import UpdateRecipientDetails
from .update_registered_model_details import UpdateRegisteredModelDetails
from .update_registered_model_response_details import UpdateRegisteredModelResponseDetails
from .update_registered_model_tags_details import UpdateRegisteredModelTagsDetails
from .update_registered_model_tags_response_details import UpdateRegisteredModelTagsResponseDetails
from .update_role_details import UpdateRoleDetails
from .update_schema_details import UpdateSchemaDetails
from .update_setting_details import UpdateSettingDetails
from .update_share_details import UpdateShareDetails
from .update_spark_cluster_details import UpdateSparkClusterDetails
from .update_sql_tool_details import UpdateSqlToolDetails
from .update_sql_tool_node_details import UpdateSqlToolNodeDetails
from .update_table_details import UpdateTableDetails
from .update_table_field_details import UpdateTableFieldDetails
from .update_tool_details import UpdateToolDetails
from .update_user_setting_details import UpdateUserSettingDetails
from .update_view_details import UpdateViewDetails
from .update_volume_details import UpdateVolumeDetails
from .update_workspace_async_operation_status_details import UpdateWorkspaceAsyncOperationStatusDetails
from .update_workspace_details import UpdateWorkspaceDetails
from .upload_file_with_par_details import UploadFileWithParDetails
from .upload_file_with_par_result import UploadFileWithParResult
from .user_setting import UserSetting
from .user_setting_collection import UserSettingCollection
from .user_setting_summary import UserSettingSummary
from .validate_agent_flow_diagram_details import ValidateAgentFlowDiagramDetails
from .validate_agent_flow_response import ValidateAgentFlowResponse
from .validate_bundle_details import ValidateBundleDetails
from .validate_view_sql_details import ValidateViewSqlDetails
from .validation_error import ValidationError
from .vault_reference_credential_details import VaultReferenceCredentialDetails
from .view import View
from .view_collection import ViewCollection
from .view_field_details import ViewFieldDetails
from .view_permission_collection import ViewPermissionCollection
from .view_permission_summary import ViewPermissionSummary
from .view_property import ViewProperty
from .view_sql_parse_details import ViewSqlParseDetails
from .view_summary import ViewSummary
from .view_update_details import ViewUpdateDetails
from .volume import Volume
from .volume_collection import VolumeCollection
from .volume_file import VolumeFile
from .volume_file_cluster_library_summary import VolumeFileClusterLibrarySummary
from .volume_file_collection import VolumeFileCollection
from .volume_file_summary import VolumeFileSummary
from .volume_permission_collection import VolumePermissionCollection
from .volume_permission_summary import VolumePermissionSummary
from .volume_summary import VolumeSummary
from .word_filters_policy import WordFiltersPolicy
from .worker_config import WorkerConfig
from .workspace import Workspace
from .workspace_collection import WorkspaceCollection
from .workspace_file_cluster_library_summary import WorkspaceFileClusterLibrarySummary
from .workspace_network_configuration_details import WorkspaceNetworkConfigurationDetails
from .workspace_object import WorkspaceObject
from .workspace_object_collection import WorkspaceObjectCollection
from .workspace_object_details import WorkspaceObjectDetails
from .workspace_object_permission_collection import WorkspaceObjectPermissionCollection
from .workspace_object_permission_summary import WorkspaceObjectPermissionSummary
from .workspace_object_search_results_collection import WorkspaceObjectSearchResultsCollection
from .workspace_object_search_summary import WorkspaceObjectSearchSummary
from .workspace_object_summary import WorkspaceObjectSummary
from .workspace_permission_collection import WorkspacePermissionCollection
from .workspace_permission_summary import WorkspacePermissionSummary
from .workspace_search_criteria import WorkspaceSearchCriteria
from .workspace_summary import WorkspaceSummary

# Maps type names to classes for aidataplatform_dp services.
aidataplatform_dp_type_mapping = {
    "ActiveClusterResources": ActiveClusterResources,
    "AddMemberToRoleDetails": AddMemberToRoleDetails,
    "AdminSetting": AdminSetting,
    "AdminSettingCollection": AdminSettingCollection,
    "AdminSettingSummary": AdminSettingSummary,
    "AdwSchema": AdwSchema,
    "AdwSchemaSummary": AdwSchemaSummary,
    "AdwTable": AdwTable,
    "AdwTableSummary": AdwTableSummary,
    "AgentCardCapabilitiesDetail": AgentCardCapabilitiesDetail,
    "AgentCardConfigDetail": AgentCardConfigDetail,
    "AgentCardPreviewResponse": AgentCardPreviewResponse,
    "AgentCardSkillDetail": AgentCardSkillDetail,
    "AgentFlow": AgentFlow,
    "AgentFlowAttachment": AgentFlowAttachment,
    "AgentFlowCollection": AgentFlowCollection,
    "AgentFlowCompute": AgentFlowCompute,
    "AgentFlowDependency": AgentFlowDependency,
    "AgentFlowDependencyItem": AgentFlowDependencyItem,
    "AgentFlowDeployment": AgentFlowDeployment,
    "AgentFlowDeploymentCollection": AgentFlowDeploymentCollection,
    "AgentFlowDeploymentSummary": AgentFlowDeploymentSummary,
    "AgentFlowDetachment": AgentFlowDetachment,
    "AgentFlowDiagram": AgentFlowDiagram,
    "AgentFlowEdge": AgentFlowEdge,
    "AgentFlowGuardrailsCollection": AgentFlowGuardrailsCollection,
    "AgentFlowGuardrailsSummary": AgentFlowGuardrailsSummary,
    "AgentFlowNode": AgentFlowNode,
    "AgentFlowPermissionCollection": AgentFlowPermissionCollection,
    "AgentFlowPermissionSummary": AgentFlowPermissionSummary,
    "AgentFlowSession": AgentFlowSession,
    "AgentFlowSessionCollection": AgentFlowSessionCollection,
    "AgentFlowSessionContext": AgentFlowSessionContext,
    "AgentFlowSessionMetric": AgentFlowSessionMetric,
    "AgentFlowSessionMetricsRange": AgentFlowSessionMetricsRange,
    "AgentFlowSessionSummary": AgentFlowSessionSummary,
    "AgentFlowSummary": AgentFlowSummary,
    "AgentFlowValidationIssue": AgentFlowValidationIssue,
    "AgentFlowValidationMetadata": AgentFlowValidationMetadata,
    "AgentFlowValidationOptions": AgentFlowValidationOptions,
    "AgentFlowValidationResult": AgentFlowValidationResult,
    "AgentFlowValidationSummary": AgentFlowValidationSummary,
    "AgentNode": AgentNode,
    "AgentProvider": AgentProvider,
    "AggregatedDataPoint": AggregatedDataPoint,
    "AggregatedTimeSeriesDataPoint": AggregatedTimeSeriesDataPoint,
    "AiComputeOverrideItem": AiComputeOverrideItem,
    "AiDataPlatform": AiDataPlatform,
    "AiModel": AiModel,
    "AirflowCellConfig": AirflowCellConfig,
    "AlhSchema": AlhSchema,
    "AlhSchemaSummary": AlhSchemaSummary,
    "AlhTable": AlhTable,
    "AlhTableSummary": AlhTableSummary,
    "AllowedToolDetails": AllowedToolDetails,
    "ArtifactFileInfo": ArtifactFileInfo,
    "ArtifactList": ArtifactList,
    "AssignAgentFlowPermissionDetails": AssignAgentFlowPermissionDetails,
    "AssignCatalogPermissionDetails": AssignCatalogPermissionDetails,
    "AssignClusterPermissionDetails": AssignClusterPermissionDetails,
    "AssignCreateWorkspacePermissionDetails": AssignCreateWorkspacePermissionDetails,
    "AssignCredentialPermissionDetails": AssignCredentialPermissionDetails,
    "AssignJobPermissionDetails": AssignJobPermissionDetails,
    "AssignKnowledgeBasePermissionDetails": AssignKnowledgeBasePermissionDetails,
    "AssignMasterCatalogPermissionDetails": AssignMasterCatalogPermissionDetails,
    "AssignRecipientPermissionDetails": AssignRecipientPermissionDetails,
    "AssignRolePermissionDetails": AssignRolePermissionDetails,
    "AssignSchemaPermissionDetails": AssignSchemaPermissionDetails,
    "AssignSharePermissionDetails": AssignSharePermissionDetails,
    "AssignTablePermissionDetails": AssignTablePermissionDetails,
    "AssignToolPermissionDetails": AssignToolPermissionDetails,
    "AssignViewPermissionDetails": AssignViewPermissionDetails,
    "AssignVolumePermissionDetails": AssignVolumePermissionDetails,
    "AssignWorkspaceObjectPermissionDetails": AssignWorkspaceObjectPermissionDetails,
    "AssignWorkspacePermissionDetails": AssignWorkspacePermissionDetails,
    "AsyncOperation": AsyncOperation,
    "AsyncOperationCollection": AsyncOperationCollection,
    "AsyncOperationSummary": AsyncOperationSummary,
    "AtpSchema": AtpSchema,
    "AtpSchemaSummary": AtpSchemaSummary,
    "AtpTable": AtpTable,
    "AtpTableSummary": AtpTableSummary,
    "AttachComputeDetails": AttachComputeDetails,
    "AttachMasterCatalogToClusterDetails": AttachMasterCatalogToClusterDetails,
    "AttachToNotebookConfig": AttachToNotebookConfig,
    "AttachWorkspaceObjectToClusterDetails": AttachWorkspaceObjectToClusterDetails,
    "AttachedSession": AttachedSession,
    "AuditLogSearchResultCollection": AuditLogSearchResultCollection,
    "AuditLogSearchResultSummary": AuditLogSearchResultSummary,
    "Auth": Auth,
    "AutoScale": AutoScale,
    "BearerTokenAuth": BearerTokenAuth,
    "BucketCollection": BucketCollection,
    "BucketSummary": BucketSummary,
    "Bundle": Bundle,
    "BundleDeployedResource": BundleDeployedResource,
    "BundleDeploymentStatus": BundleDeploymentStatus,
    "BundleOverrides": BundleOverrides,
    "BundleOverridesWithPath": BundleOverridesWithPath,
    "BundleValidationResult": BundleValidationResult,
    "BundledResource": BundledResource,
    "Catalog": Catalog,
    "CatalogCollection": CatalogCollection,
    "CatalogConnectionDetails": CatalogConnectionDetails,
    "CatalogMigrationDetail": CatalogMigrationDetail,
    "CatalogPermissionCollection": CatalogPermissionCollection,
    "CatalogPermissionSummary": CatalogPermissionSummary,
    "CatalogSummary": CatalogSummary,
    "CatalogTestConnectionDetails": CatalogTestConnectionDetails,
    "CategoryConfig": CategoryConfig,
    "ChatMessage": ChatMessage,
    "CheckoutBranchDetails": CheckoutBranchDetails,
    "ClearOutputsDetails": ClearOutputsDetails,
    "Cluster": Cluster,
    "ClusterCollection": ClusterCollection,
    "ClusterEvent": ClusterEvent,
    "ClusterExecutionContextAvailabilityEvent": ClusterExecutionContextAvailabilityEvent,
    "ClusterInstance": ClusterInstance,
    "ClusterLibraryCollection": ClusterLibraryCollection,
    "ClusterLibraryDetails": ClusterLibraryDetails,
    "ClusterLibrarySummary": ClusterLibrarySummary,
    "ClusterLogCollection": ClusterLogCollection,
    "ClusterLogsSummary": ClusterLogsSummary,
    "ClusterPatchEvent": ClusterPatchEvent,
    "ClusterPermissionCollection": ClusterPermissionCollection,
    "ClusterPermissionSummary": ClusterPermissionSummary,
    "ClusterRuntimeConfig": ClusterRuntimeConfig,
    "ClusterSpec": ClusterSpec,
    "ClusterStateEvent": ClusterStateEvent,
    "ClusterSummary": ClusterSummary,
    "CommitPushDetails": CommitPushDetails,
    "ComputeDependency": ComputeDependency,
    "ComputeOverrideItem": ComputeOverrideItem,
    "ConflictResolveDetails": ConflictResolveDetails,
    "Content": Content,
    "ContentModerationCategoryConfig": ContentModerationCategoryConfig,
    "ContentModerationConfig": ContentModerationConfig,
    "ContentModerationPolicy": ContentModerationPolicy,
    "Continuous": Continuous,
    "CopyAgentFlowDetails": CopyAgentFlowDetails,
    "CopyWorkspaceObjectDetails": CopyWorkspaceObjectDetails,
    "CreateAdminSettingDetails": CreateAdminSettingDetails,
    "CreateAgentFlowComputeDetails": CreateAgentFlowComputeDetails,
    "CreateAgentFlowDetails": CreateAgentFlowDetails,
    "CreateAgentFlowEdgeDetails": CreateAgentFlowEdgeDetails,
    "CreateAgentFlowNodeDetails": CreateAgentFlowNodeDetails,
    "CreateAgentFlowSessionDetails": CreateAgentFlowSessionDetails,
    "CreateAgentNodeDetails": CreateAgentNodeDetails,
    "CreateBundleDetails": CreateBundleDetails,
    "CreateCatalogDetails": CreateCatalogDetails,
    "CreateClusterDetails": CreateClusterDetails,
    "CreateConnectionDetails": CreateConnectionDetails,
    "CreateContentDetails": CreateContentDetails,
    "CreateCustomToolDetails": CreateCustomToolDetails,
    "CreateCustomToolNodeDetails": CreateCustomToolNodeDetails,
    "CreateDataLakeCredentialDetails": CreateDataLakeCredentialDetails,
    "CreateDataTableDetails": CreateDataTableDetails,
    "CreateExperimentDetails": CreateExperimentDetails,
    "CreateExperimentResponseDetails": CreateExperimentResponseDetails,
    "CreateExperimentRunDetails": CreateExperimentRunDetails,
    "CreateExperimentRunResponseDetails": CreateExperimentRunResponseDetails,
    "CreateGitBranch": CreateGitBranch,
    "CreateGitBranchDetails": CreateGitBranchDetails,
    "CreateGitFolderDetails": CreateGitFolderDetails,
    "CreateHttpToolDetails": CreateHttpToolDetails,
    "CreateHttpToolNodeDetails": CreateHttpToolNodeDetails,
    "CreateJobDetails": CreateJobDetails,
    "CreateJobRunDetails": CreateJobRunDetails,
    "CreateKnowledgeBaseDetails": CreateKnowledgeBaseDetails,
    "CreateKnowledgeBaseJobDetails": CreateKnowledgeBaseJobDetails,
    "CreateKnowledgeBaseJobRunDetails": CreateKnowledgeBaseJobRunDetails,
    "CreateMasterCatalogDetails": CreateMasterCatalogDetails,
    "CreateMcpToolNodeDetails": CreateMcpToolNodeDetails,
    "CreateModelVersionDetails": CreateModelVersionDetails,
    "CreateModelVersionResponseDetails": CreateModelVersionResponseDetails,
    "CreateNlToSqlToolDetails": CreateNlToSqlToolDetails,
    "CreateOrUpdateBundleOverridesDetails": CreateOrUpdateBundleOverridesDetails,
    "CreatePromptToolDetails": CreatePromptToolDetails,
    "CreatePromptToolNodeDetails": CreatePromptToolNodeDetails,
    "CreateRagToolDetails": CreateRagToolDetails,
    "CreateRagToolNodeDetails": CreateRagToolNodeDetails,
    "CreateRecipientDetails": CreateRecipientDetails,
    "CreateRegisteredModelDetails": CreateRegisteredModelDetails,
    "CreateRegisteredModelResponseDetails": CreateRegisteredModelResponseDetails,
    "CreateRoleDetails": CreateRoleDetails,
    "CreateSchemaDetails": CreateSchemaDetails,
    "CreateSessionDetails": CreateSessionDetails,
    "CreateSettingDetails": CreateSettingDetails,
    "CreateShareDetails": CreateShareDetails,
    "CreateSparkClusterDetails": CreateSparkClusterDetails,
    "CreateSqlToolDetails": CreateSqlToolDetails,
    "CreateSqlToolNodeDetails": CreateSqlToolNodeDetails,
    "CreateTableDetails": CreateTableDetails,
    "CreateToolDetails": CreateToolDetails,
    "CreateUserSettingDetails": CreateUserSettingDetails,
    "CreateViewDetails": CreateViewDetails,
    "CreateVolumeDetails": CreateVolumeDetails,
    "CreateWorkspaceDetails": CreateWorkspaceDetails,
    "CreateWorkspacePermissionCollection": CreateWorkspacePermissionCollection,
    "CreateWorkspacePermissionSummary": CreateWorkspacePermissionSummary,
    "Credential": Credential,
    "CredentialCollection": CredentialCollection,
    "CredentialDetails": CredentialDetails,
    "CredentialSummary": CredentialSummary,
    "CredentialV2": CredentialV2,
    "CredentialV2Collection": CredentialV2Collection,
    "CredentialV2NameAndSecretKey": CredentialV2NameAndSecretKey,
    "CredentialV2Summary": CredentialV2Summary,
    "CredentialsPermissionCollection": CredentialsPermissionCollection,
    "CustomPiiRule": CustomPiiRule,
    "CustomResult": CustomResult,
    "CustomTestToolResult": CustomTestToolResult,
    "CustomTool": CustomTool,
    "CustomToolConfiguration": CustomToolConfiguration,
    "CustomToolEntry": CustomToolEntry,
    "CustomToolNode": CustomToolNode,
    "DacEndpointCollection": DacEndpointCollection,
    "DacEndpointSummary": DacEndpointSummary,
    "DataLake": DataLake,
    "DataLakeClusterCollection": DataLakeClusterCollection,
    "DataLakeClusterSummary": DataLakeClusterSummary,
    "DataLakeMetadata": DataLakeMetadata,
    "Dataset": Dataset,
    "DatasetInput": DatasetInput,
    "DeProvisionUserSchemasDetails": DeProvisionUserSchemasDetails,
    "DefaultCluster": DefaultCluster,
    "DeleteExperimentDetails": DeleteExperimentDetails,
    "DeleteExperimentResponseDetails": DeleteExperimentResponseDetails,
    "DeleteExperimentRunDetails": DeleteExperimentRunDetails,
    "DeleteExperimentRunResponseDetails": DeleteExperimentRunResponseDetails,
    "DeleteExperimentRunTagDetails": DeleteExperimentRunTagDetails,
    "DeleteExperimentRunTagResponseDetails": DeleteExperimentRunTagResponseDetails,
    "DeleteExperimentTagDetails": DeleteExperimentTagDetails,
    "DeleteExperimentTagResponseDetails": DeleteExperimentTagResponseDetails,
    "DeleteModelVersionDetails": DeleteModelVersionDetails,
    "DeleteModelVersionResponseDetails": DeleteModelVersionResponseDetails,
    "DeleteModelVersionTagDetails": DeleteModelVersionTagDetails,
    "DeleteModelVersionTagResponseDetails": DeleteModelVersionTagResponseDetails,
    "DeleteRegisteredModelDetails": DeleteRegisteredModelDetails,
    "DeleteRegisteredModelResponseDetails": DeleteRegisteredModelResponseDetails,
    "DeleteRegisteredModelTagDetails": DeleteRegisteredModelTagDetails,
    "DeleteRegisteredModelTagResponseDetails": DeleteRegisteredModelTagResponseDetails,
    "DeniedTopic": DeniedTopic,
    "DeniedTopicsPolicy": DeniedTopicsPolicy,
    "Dependency": Dependency,
    "DependsOn": DependsOn,
    "DeployAgentFlowDetails": DeployAgentFlowDetails,
    "DeployBundleDetails": DeployBundleDetails,
    "DetachComputeDetails": DetachComputeDetails,
    "DetachWorkspaceObjectFromClusterDetails": DetachWorkspaceObjectFromClusterDetails,
    "DownloadClusterLogsDetails": DownloadClusterLogsDetails,
    "DownloadFileWithParResult": DownloadFileWithParResult,
    "DriverConfig": DriverConfig,
    "EmbeddingModelDetails": EmbeddingModelDetails,
    "ExadataSchema": ExadataSchema,
    "ExadataSchemaSummary": ExadataSchemaSummary,
    "ExadataTable": ExadataTable,
    "ExadataTableSummary": ExadataTableSummary,
    "ExecuteDatabaseUserWorkflowsDetails": ExecuteDatabaseUserWorkflowsDetails,
    "ExecuteSqlCommandDetails": ExecuteSqlCommandDetails,
    "Experiment": Experiment,
    "ExperimentCollection": ExperimentCollection,
    "ExperimentResponse": ExperimentResponse,
    "ExperimentRun": ExperimentRun,
    "ExperimentRunCollection": ExperimentRunCollection,
    "ExperimentRunData": ExperimentRunData,
    "ExperimentRunInfo": ExperimentRunInfo,
    "ExperimentRunInputs": ExperimentRunInputs,
    "ExperimentRunMetric": ExperimentRunMetric,
    "ExperimentRunMetricHistoryCollection": ExperimentRunMetricHistoryCollection,
    "ExperimentRunOutputs": ExperimentRunOutputs,
    "ExperimentRunParam": ExperimentRunParam,
    "ExperimentRunTag": ExperimentRunTag,
    "ExperimentRunTagKey": ExperimentRunTagKey,
    "ExperimentTag": ExperimentTag,
    "ExperimentTagKey": ExperimentTagKey,
    "ExportContentsDetails": ExportContentsDetails,
    "ExportTaskRunOutputDetails": ExportTaskRunOutputDetails,
    "ExportedContents": ExportedContents,
    "ExportedTaskRunOutputContents": ExportedTaskRunOutputContents,
    "Expression": Expression,
    "ExternalAgentNode": ExternalAgentNode,
    "ExternalCatalogMigrationResult": ExternalCatalogMigrationResult,
    "ExternalTableDefinition": ExternalTableDefinition,
    "Feature": Feature,
    "FeatureStatusCollection": FeatureStatusCollection,
    "FeatureStatusResult": FeatureStatusResult,
    "FeatureStatusSummary": FeatureStatusSummary,
    "FetchBundleDeploymentStatusDetails": FetchBundleDeploymentStatusDetails,
    "FetchMcpObjectsDetails": FetchMcpObjectsDetails,
    "FetchMcpObjectsResult": FetchMcpObjectsResult,
    "FetchOutputDetails": FetchOutputDetails,
    "FieldInfo": FieldInfo,
    "FileDependency": FileDependency,
    "FilterTypes": FilterTypes,
    "GenerateTempFileUploadTargetResponseDetails": GenerateTempFileUploadTargetResponseDetails,
    "GetBundleOverridesDetails": GetBundleOverridesDetails,
    "GetExperimentRunResponseDetails": GetExperimentRunResponseDetails,
    "GetModelVersionResponseDetails": GetModelVersionResponseDetails,
    "GetRegisteredModelResponseDetails": GetRegisteredModelResponseDetails,
    "GitAccountUserSetting": GitAccountUserSetting,
    "GitBranch": GitBranch,
    "GitBranchCollection": GitBranchCollection,
    "GitBranchSummary": GitBranchSummary,
    "GitConfig": GitConfig,
    "GitDiffDetail": GitDiffDetail,
    "GitDiffSummary": GitDiffSummary,
    "GitDiffSummaryCollection": GitDiffSummaryCollection,
    "GitFolder": GitFolder,
    "GitMergeDetails": GitMergeDetails,
    "GitOperationState": GitOperationState,
    "GitPullDetails": GitPullDetails,
    "GitRebaseDetails": GitRebaseDetails,
    "GitRepairWorkTreeDetails": GitRepairWorkTreeDetails,
    "GitRepository": GitRepository,
    "GitResetDetails": GitResetDetails,
    "GitRestoreBranchDetails": GitRestoreBranchDetails,
    "GroupedSearchCriteria": GroupedSearchCriteria,
    "GuardrailNode": GuardrailNode,
    "GuardrailsConfiguration": GuardrailsConfiguration,
    "HistoryCollection": HistoryCollection,
    "HistorySummary": HistorySummary,
    "HttpResult": HttpResult,
    "HttpTestToolResult": HttpTestToolResult,
    "HttpTool": HttpTool,
    "HttpToolConfiguration": HttpToolConfiguration,
    "HttpToolNode": HttpToolNode,
    "HumanInTheLoopNode": HumanInTheLoopNode,
    "IamUserCredentialUserSetting": IamUserCredentialUserSetting,
    "IdentityDomainCollection": IdentityDomainCollection,
    "IdentityDomainSummary": IdentityDomainSummary,
    "IdentityGroupCollection": IdentityGroupCollection,
    "IdentityGroupSummary": IdentityGroupSummary,
    "IdentityUserCollection": IdentityUserCollection,
    "IdentityUserSummary": IdentityUserSummary,
    "IfElseTask": IfElseTask,
    "InferSchema": InferSchema,
    "InferSchemaColumn": InferSchemaColumn,
    "InferSchemaProperties": InferSchemaProperties,
    "InferSchemaWithPreview": InferSchemaWithPreview,
    "InitScriptPath": InitScriptPath,
    "InputTag": InputTag,
    "InstallClusterLibraryDetails": InstallClusterLibraryDetails,
    "IsPrincipalAdmin": IsPrincipalAdmin,
    "IsPrincipalAidpAdmin": IsPrincipalAidpAdmin,
    "JarTask": JarTask,
    "Job": Job,
    "JobCluster": JobCluster,
    "JobCollection": JobCollection,
    "JobDependency": JobDependency,
    "JobPermissionCollection": JobPermissionCollection,
    "JobPermissionSummary": JobPermissionSummary,
    "JobRun": JobRun,
    "JobRunCollection": JobRunCollection,
    "JobRunSummary": JobRunSummary,
    "JobSummary": JobSummary,
    "JobTask": JobTask,
    "KafkaTopicSchema": KafkaTopicSchema,
    "KafkaTopicSchemaSummary": KafkaTopicSchemaSummary,
    "KbVHnswIndexDetails": KbVHnswIndexDetails,
    "KbVIvfIndexDetails": KbVIvfIndexDetails,
    "Kernel": Kernel,
    "KernelCollection": KernelCollection,
    "KernelSummary": KernelSummary,
    "KeyedTimeSeries": KeyedTimeSeries,
    "KnowledgeBase": KnowledgeBase,
    "KnowledgeBaseCollection": KnowledgeBaseCollection,
    "KnowledgeBaseJob": KnowledgeBaseJob,
    "KnowledgeBaseJobCollection": KnowledgeBaseJobCollection,
    "KnowledgeBaseJobRun": KnowledgeBaseJobRun,
    "KnowledgeBaseJobRunCollection": KnowledgeBaseJobRunCollection,
    "KnowledgeBaseJobRunData": KnowledgeBaseJobRunData,
    "KnowledgeBaseJobRunSummary": KnowledgeBaseJobRunSummary,
    "KnowledgeBaseJobSummary": KnowledgeBaseJobSummary,
    "KnowledgeBasePermissionCollection": KnowledgeBasePermissionCollection,
    "KnowledgeBasePermissionSummary": KnowledgeBasePermissionSummary,
    "KnowledgeBaseSourceMetadataDetails": KnowledgeBaseSourceMetadataDetails,
    "KnowledgeBaseSummary": KnowledgeBaseSummary,
    "KnowledgeBaseVectorIndexDetails": KnowledgeBaseVectorIndexDetails,
    "Libraries": Libraries,
    "LifecycleState": LifecycleState,
    "ListExperimentRunsDetails": ListExperimentRunsDetails,
    "ListExperimentsDetails": ListExperimentsDetails,
    "ListFilter": ListFilter,
    "ListLoggedModelsDetails": ListLoggedModelsDetails,
    "ListPermissionsWithResourceDetails": ListPermissionsWithResourceDetails,
    "LlmConfig": LlmConfig,
    "LogExperimentRunBatchDetails": LogExperimentRunBatchDetails,
    "LogExperimentRunBatchResponseDetails": LogExperimentRunBatchResponseDetails,
    "LogExperimentRunInputsDetails": LogExperimentRunInputsDetails,
    "LogExperimentRunInputsResponseDetails": LogExperimentRunInputsResponseDetails,
    "LogExperimentRunMetricDetails": LogExperimentRunMetricDetails,
    "LogExperimentRunMetricResponseDetails": LogExperimentRunMetricResponseDetails,
    "LogExperimentRunModelDetails": LogExperimentRunModelDetails,
    "LogExperimentRunModelResponseDetails": LogExperimentRunModelResponseDetails,
    "LogExperimentRunParamDetails": LogExperimentRunParamDetails,
    "LogExperimentRunParamResponseDetails": LogExperimentRunParamResponseDetails,
    "LogGroup": LogGroup,
    "LoggedModel": LoggedModel,
    "LoggedModelCollection": LoggedModelCollection,
    "LoggedModelInfo": LoggedModelInfo,
    "LoggedModelOrder": LoggedModelOrder,
    "LoggedModelTag": LoggedModelTag,
    "LoggingConfig": LoggingConfig,
    "ManageAgentFlowPermissionDetails": ManageAgentFlowPermissionDetails,
    "ManageAuditLogsDetails": ManageAuditLogsDetails,
    "ManageCatalogPermissionDetails": ManageCatalogPermissionDetails,
    "ManageClusterPermissionDetails": ManageClusterPermissionDetails,
    "ManageCreateWorkspacePermissionDetails": ManageCreateWorkspacePermissionDetails,
    "ManageCredentialPermissionDetails": ManageCredentialPermissionDetails,
    "ManageJobPermissionDetails": ManageJobPermissionDetails,
    "ManageKnowledgeBasePermissionDetails": ManageKnowledgeBasePermissionDetails,
    "ManageMasterCatalogPermissionDetails": ManageMasterCatalogPermissionDetails,
    "ManageRecipientPermissionDetails": ManageRecipientPermissionDetails,
    "ManageRolePermissionDetails": ManageRolePermissionDetails,
    "ManageSchemaPermissionDetails": ManageSchemaPermissionDetails,
    "ManageShareAccessDetails": ManageShareAccessDetails,
    "ManageShareDataAssetDetails": ManageShareDataAssetDetails,
    "ManageSharePermissionDetails": ManageSharePermissionDetails,
    "ManageTablePermissionDetails": ManageTablePermissionDetails,
    "ManageToolPermissionDetails": ManageToolPermissionDetails,
    "ManageViewPermissionDetails": ManageViewPermissionDetails,
    "ManageVolumePermissionDetails": ManageVolumePermissionDetails,
    "ManageWorkspaceObjectPermissionDetails": ManageWorkspaceObjectPermissionDetails,
    "ManageWorkspacePermissionDetails": ManageWorkspacePermissionDetails,
    "ManagedTableDefinition": ManagedTableDefinition,
    "MasterCatalog": MasterCatalog,
    "MasterCatalogCollection": MasterCatalogCollection,
    "MasterCatalogPermissionCollection": MasterCatalogPermissionCollection,
    "MasterCatalogPermissionSummary": MasterCatalogPermissionSummary,
    "MasterCatalogSummary": MasterCatalogSummary,
    "McpObject": McpObject,
    "McpPromptObject": McpPromptObject,
    "McpResourceObject": McpResourceObject,
    "McpResult": McpResult,
    "McpTestToolResult": McpTestToolResult,
    "McpTool": McpTool,
    "McpToolConfiguration": McpToolConfiguration,
    "McpToolNode": McpToolNode,
    "McpToolObject": McpToolObject,
    "MemoryConfiguration": MemoryConfiguration,
    "MemoryLimitConfiguration": MemoryLimitConfiguration,
    "MemoryLimitConfigurationDetails": MemoryLimitConfigurationDetails,
    "MetricsSummary": MetricsSummary,
    "MkdirDetails": MkdirDetails,
    "Model": Model,
    "ModelInput": ModelInput,
    "ModelMetric": ModelMetric,
    "ModelOutput": ModelOutput,
    "ModelParam": ModelParam,
    "ModelParameter": ModelParameter,
    "ModelParameterDetail": ModelParameterDetail,
    "ModelParameterResponse": ModelParameterResponse,
    "ModelSummary": ModelSummary,
    "ModelVersion": ModelVersion,
    "ModelVersionCollection": ModelVersionCollection,
    "ModelVersionDeploymentJobState": ModelVersionDeploymentJobState,
    "ModelVersionTag": ModelVersionTag,
    "ModelVersionTagKey": ModelVersionTagKey,
    "ModelsCollection": ModelsCollection,
    "ModifyContentDetails": ModifyContentDetails,
    "MoveWorkspaceObjectDetails": MoveWorkspaceObjectDetails,
    "NestedAgentFlowNode": NestedAgentFlowNode,
    "NewClusterConfiguration": NewClusterConfiguration,
    "NlToSqlTool": NlToSqlTool,
    "NlToSqlToolConfiguration": NlToSqlToolConfiguration,
    "NlToSqlToolInputSchema": NlToSqlToolInputSchema,
    "NoAuth": NoAuth,
    "NodeInput": NodeInput,
    "NodeIo": NodeIo,
    "NodeIoColor": NodeIoColor,
    "NodeOutput": NodeOutput,
    "NotebookTask": NotebookTask,
    "NotifyClusterEventHandlerDetails": NotifyClusterEventHandlerDetails,
    "OAuth": OAuth,
    "OAuthAdminSetting": OAuthAdminSetting,
    "OAuthConfiguration": OAuthConfiguration,
    "OacSchema": OacSchema,
    "OacSchemaSummary": OacSchemaSummary,
    "OacTable": OacTable,
    "OacTableSummary": OacTableSummary,
    "ObjectRecentSearchSummary": ObjectRecentSearchSummary,
    "ObjectSearchSummary": ObjectSearchSummary,
    "ObjectSuggestSummary": ObjectSuggestSummary,
    "OciLogging": OciLogging,
    "OciResourcePrincipalAuth": OciResourcePrincipalAuth,
    "OracleSchema": OracleSchema,
    "OracleSchemaSummary": OracleSchemaSummary,
    "OracleTable": OracleTable,
    "OracleTableSummary": OracleTableSummary,
    "OutputParameter": OutputParameter,
    "ParDetails": ParDetails,
    "Parameter": Parameter,
    "PatchClusterLibraryDetails": PatchClusterLibraryDetails,
    "PatchSessionDetails": PatchSessionDetails,
    "PerformInferSchemaDetails": PerformInferSchemaDetails,
    "PermissionAssignees": PermissionAssignees,
    "PermissionSummary": PermissionSummary,
    "PermissionWithResourceDetails": PermissionWithResourceDetails,
    "PiiCategory": PiiCategory,
    "PiiDetectionPolicy": PiiDetectionPolicy,
    "PlaygroundCache": PlaygroundCache,
    "Point": Point,
    "PreviewAgentFlowAgentCardDetails": PreviewAgentFlowAgentCardDetails,
    "PrincipalsWithWorkspaceAccessCollection": PrincipalsWithWorkspaceAccessCollection,
    "PrincipalsWithWorkspaceAccessSummary": PrincipalsWithWorkspaceAccessSummary,
    "PromptAttacksPreventionPolicy": PromptAttacksPreventionPolicy,
    "PromptResult": PromptResult,
    "PromptTestToolResult": PromptTestToolResult,
    "PromptTool": PromptTool,
    "PromptToolConfiguration": PromptToolConfiguration,
    "PromptToolNode": PromptToolNode,
    "ProvisionUserSchemaDetails": ProvisionUserSchemaDetails,
    "PurgeBundleDetails": PurgeBundleDetails,
    "PythonTask": PythonTask,
    "Queue": Queue,
    "RagResult": RagResult,
    "RagTestToolResult": RagTestToolResult,
    "RagTool": RagTool,
    "RagToolConfiguration": RagToolConfiguration,
    "RagToolInputSchema": RagToolInputSchema,
    "RagToolNode": RagToolNode,
    "RangeFilter": RangeFilter,
    "RecentResourceItem": RecentResourceItem,
    "RecentSearchResultsCollection": RecentSearchResultsCollection,
    "RecentSearchesCriteria": RecentSearchesCriteria,
    "RecentlyAccessed": RecentlyAccessed,
    "RecentlyAccessedResource": RecentlyAccessedResource,
    "Recipient": Recipient,
    "RecipientCollection": RecipientCollection,
    "RecipientPermissionCollection": RecipientPermissionCollection,
    "RecipientPermissionSummary": RecipientPermissionSummary,
    "RecipientSummary": RecipientSummary,
    "RegisteredModel": RegisteredModel,
    "RegisteredModelAlias": RegisteredModelAlias,
    "RegisteredModelCollection": RegisteredModelCollection,
    "RegisteredModelTag": RegisteredModelTag,
    "RegisteredModelTagKey": RegisteredModelTagKey,
    "RemoveMemberFromRoleDetails": RemoveMemberFromRoleDetails,
    "RenameRegisteredModelDetails": RenameRegisteredModelDetails,
    "RenameRegisteredModelResponseDetails": RenameRegisteredModelResponseDetails,
    "RenameTableFieldDetails": RenameTableFieldDetails,
    "RenameWorkspaceObjectDetails": RenameWorkspaceObjectDetails,
    "RepairHistory": RepairHistory,
    "RepairJobRunDetails": RepairJobRunDetails,
    "ResetGitFolderStateDetails": ResetGitFolderStateDetails,
    "RestartClusterDetails": RestartClusterDetails,
    "RestoreExperimentDetails": RestoreExperimentDetails,
    "RestoreExperimentResponseDetails": RestoreExperimentResponseDetails,
    "RestoreExperimentRunDetails": RestoreExperimentRunDetails,
    "RestoreExperimentRunResponseDetails": RestoreExperimentRunResponseDetails,
    "RetrievedChunk": RetrievedChunk,
    "RevokeAgentFlowPermissionDetails": RevokeAgentFlowPermissionDetails,
    "RevokeCatalogPermissionDetails": RevokeCatalogPermissionDetails,
    "RevokeClusterPermissionDetails": RevokeClusterPermissionDetails,
    "RevokeCreateWorkspacePermissionDetails": RevokeCreateWorkspacePermissionDetails,
    "RevokeCredentialPermissionDetails": RevokeCredentialPermissionDetails,
    "RevokeJobPermissionDetails": RevokeJobPermissionDetails,
    "RevokeKnowledgeBasePermissionDetails": RevokeKnowledgeBasePermissionDetails,
    "RevokeMasterCatalogPermissionDetails": RevokeMasterCatalogPermissionDetails,
    "RevokeRecipientPermissionDetails": RevokeRecipientPermissionDetails,
    "RevokeRolePermissionDetails": RevokeRolePermissionDetails,
    "RevokeSchemaPermissionDetails": RevokeSchemaPermissionDetails,
    "RevokeSharePermissionDetails": RevokeSharePermissionDetails,
    "RevokeTablePermissionDetails": RevokeTablePermissionDetails,
    "RevokeToolPermissionDetails": RevokeToolPermissionDetails,
    "RevokeViewPermissionDetails": RevokeViewPermissionDetails,
    "RevokeVolumePermissionDetails": RevokeVolumePermissionDetails,
    "RevokeWorkspaceObjectPermissionDetails": RevokeWorkspaceObjectPermissionDetails,
    "RevokeWorkspacePermissionDetails": RevokeWorkspacePermissionDetails,
    "Role": Role,
    "RoleAssignee": RoleAssignee,
    "RoleCollection": RoleCollection,
    "RolePermissionCollection": RolePermissionCollection,
    "RolePermissionSummary": RolePermissionSummary,
    "RoleSummary": RoleSummary,
    "RunOutputData": RunOutputData,
    "SafetyPolicy": SafetyPolicy,
    "Scan": Scan,
    "Schedule": Schedule,
    "Schema": Schema,
    "SchemaCollection": SchemaCollection,
    "SchemaPermissionCollection": SchemaPermissionCollection,
    "SchemaPermissionSummary": SchemaPermissionSummary,
    "SchemaSummary": SchemaSummary,
    "SearchAuditLogsDetails": SearchAuditLogsDetails,
    "SearchClusterLogsDetails": SearchClusterLogsDetails,
    "SearchCriteria": SearchCriteria,
    "SearchObjectType": SearchObjectType,
    "SearchResult": SearchResult,
    "SearchResultSummary": SearchResultSummary,
    "SearchResultsCollection": SearchResultsCollection,
    "SearchResultsGroupByCollection": SearchResultsGroupByCollection,
    "SecretPair": SecretPair,
    "SecretTokenCredentialDetails": SecretTokenCredentialDetails,
    "ServiceAccountCredentialDetails": ServiceAccountCredentialDetails,
    "Session": Session,
    "SessionChatHistoryCollection": SessionChatHistoryCollection,
    "SessionChatHistorySummary": SessionChatHistorySummary,
    "SessionCollection": SessionCollection,
    "SessionConfiguration": SessionConfiguration,
    "SessionRetentionConfiguration": SessionRetentionConfiguration,
    "SessionSummary": SessionSummary,
    "SessionVariable": SessionVariable,
    "SessionVariableDetails": SessionVariableDetails,
    "SetExperimentRunTagDetails": SetExperimentRunTagDetails,
    "SetExperimentRunTagResponseDetails": SetExperimentRunTagResponseDetails,
    "SetExperimentTagDetails": SetExperimentTagDetails,
    "SetExperimentTagResponseDetails": SetExperimentTagResponseDetails,
    "SetModelVersionTagDetails": SetModelVersionTagDetails,
    "SetModelVersionTagResponseDetails": SetModelVersionTagResponseDetails,
    "SetRegisteredModelTagDetails": SetRegisteredModelTagDetails,
    "SetRegisteredModelTagResponseDetails": SetRegisteredModelTagResponseDetails,
    "Setting": Setting,
    "SettingData": SettingData,
    "ShapeConfig": ShapeConfig,
    "Share": Share,
    "ShareCollection": ShareCollection,
    "ShareDataAssetCollection": ShareDataAssetCollection,
    "ShareDataAssetSummary": ShareDataAssetSummary,
    "SharePermissionCollection": SharePermissionCollection,
    "SharePermissionSummary": SharePermissionSummary,
    "ShareSummary": ShareSummary,
    "SortDetails": SortDetails,
    "SpanDetails": SpanDetails,
    "SpanStatus": SpanStatus,
    "SparkCluster": SparkCluster,
    "SparkRuntimeConfig": SparkRuntimeConfig,
    "SqlResult": SqlResult,
    "SqlTestToolResult": SqlTestToolResult,
    "SqlTool": SqlTool,
    "SqlToolConfiguration": SqlToolConfiguration,
    "SqlToolNode": SqlToolNode,
    "StandardSchema": StandardSchema,
    "StandardSchemaSummary": StandardSchemaSummary,
    "StandardTable": StandardTable,
    "StandardTableSummary": StandardTableSummary,
    "StartClusterDetails": StartClusterDetails,
    "StartNode": StartNode,
    "State": State,
    "StopAgentFlowSessionDetails": StopAgentFlowSessionDetails,
    "StopClusterDetails": StopClusterDetails,
    "SubscriptionDetails": SubscriptionDetails,
    "SuggestCriteria": SuggestCriteria,
    "SuggestResultsCollection": SuggestResultsCollection,
    "SummarizeMetricsDataDetails": SummarizeMetricsDataDetails,
    "SummarizeMetricsResponse": SummarizeMetricsResponse,
    "SupervisorAgentNode": SupervisorAgentNode,
    "SyncBundleDetails": SyncBundleDetails,
    "Table": Table,
    "TableCollection": TableCollection,
    "TableFieldDetails": TableFieldDetails,
    "TablePermissionCollection": TablePermissionCollection,
    "TablePermissionSummary": TablePermissionSummary,
    "TableProperty": TableProperty,
    "TableSummary": TableSummary,
    "Task": Task,
    "TaskExecutionResult": TaskExecutionResult,
    "TaskRun": TaskRun,
    "TaskRunCollection": TaskRunCollection,
    "TaskRunOutput": TaskRunOutput,
    "TaskRunRetry": TaskRunRetry,
    "TaskRunSummary": TaskRunSummary,
    "TestCustomToolDetails": TestCustomToolDetails,
    "TestHttpToolDetails": TestHttpToolDetails,
    "TestMcpConnection": TestMcpConnection,
    "TestMcpExternalTool": TestMcpExternalTool,
    "TestMcpOperation": TestMcpOperation,
    "TestMcpToolDetails": TestMcpToolDetails,
    "TestPromptToolDetails": TestPromptToolDetails,
    "TestRagToolDetails": TestRagToolDetails,
    "TestSqlToolDetails": TestSqlToolDetails,
    "TestToolDetails": TestToolDetails,
    "TestToolParamValues": TestToolParamValues,
    "TestToolResult": TestToolResult,
    "TimeCreated": TimeCreated,
    "TimeUpdated": TimeUpdated,
    "Tool": Tool,
    "ToolCollection": ToolCollection,
    "ToolPermissionCollection": ToolPermissionCollection,
    "ToolPermissionSummary": ToolPermissionSummary,
    "ToolSummary": ToolSummary,
    "TraceDetails": TraceDetails,
    "TraceEvent": TraceEvent,
    "TransitionModelVersionStageDetails": TransitionModelVersionStageDetails,
    "TransitionModelVersionStageResponseDetails": TransitionModelVersionStageResponseDetails,
    "TxtFileDefinition": TxtFileDefinition,
    "UninstallClusterLibraryDetails": UninstallClusterLibraryDetails,
    "UpdateAdminSettingDetails": UpdateAdminSettingDetails,
    "UpdateAgentFlowComputeDetails": UpdateAgentFlowComputeDetails,
    "UpdateAgentFlowDeploymentDetails": UpdateAgentFlowDeploymentDetails,
    "UpdateAgentFlowDeploymentMetadataDetails": UpdateAgentFlowDeploymentMetadataDetails,
    "UpdateAgentFlowDetails": UpdateAgentFlowDetails,
    "UpdateAgentFlowNodeDetails": UpdateAgentFlowNodeDetails,
    "UpdateAgentFlowSessionDetails": UpdateAgentFlowSessionDetails,
    "UpdateAgentFlowSessionPlaygroundCacheDetails": UpdateAgentFlowSessionPlaygroundCacheDetails,
    "UpdateAgentNodeDetails": UpdateAgentNodeDetails,
    "UpdateCatalogDetails": UpdateCatalogDetails,
    "UpdateClusterAsyncOperationStatusDetails": UpdateClusterAsyncOperationStatusDetails,
    "UpdateClusterDetails": UpdateClusterDetails,
    "UpdateConnectionDetails": UpdateConnectionDetails,
    "UpdateContentDetails": UpdateContentDetails,
    "UpdateCustomToolDetails": UpdateCustomToolDetails,
    "UpdateCustomToolNodeDetails": UpdateCustomToolNodeDetails,
    "UpdateDataLakeCredentialDetails": UpdateDataLakeCredentialDetails,
    "UpdateDirDetails": UpdateDirDetails,
    "UpdateExperimentDetails": UpdateExperimentDetails,
    "UpdateExperimentResponseDetails": UpdateExperimentResponseDetails,
    "UpdateExperimentRunDetails": UpdateExperimentRunDetails,
    "UpdateExperimentRunResponseDetails": UpdateExperimentRunResponseDetails,
    "UpdateExperimentRunTagsDetails": UpdateExperimentRunTagsDetails,
    "UpdateExperimentRunTagsResponseDetails": UpdateExperimentRunTagsResponseDetails,
    "UpdateExperimentTagsDetails": UpdateExperimentTagsDetails,
    "UpdateExperimentTagsResponseDetails": UpdateExperimentTagsResponseDetails,
    "UpdateFileMetadataDetails": UpdateFileMetadataDetails,
    "UpdateGitRepositoryDetails": UpdateGitRepositoryDetails,
    "UpdateHttpToolDetails": UpdateHttpToolDetails,
    "UpdateHttpToolNodeDetails": UpdateHttpToolNodeDetails,
    "UpdateJobDetails": UpdateJobDetails,
    "UpdateKnowledgeBaseAddSourceDetails": UpdateKnowledgeBaseAddSourceDetails,
    "UpdateKnowledgeBaseDeleteSourceDetails": UpdateKnowledgeBaseDeleteSourceDetails,
    "UpdateKnowledgeBaseDetails": UpdateKnowledgeBaseDetails,
    "UpdateKnowledgeBaseMetadataUpdateDetails": UpdateKnowledgeBaseMetadataUpdateDetails,
    "UpdateKnowledgeBaseSourceUpdateDetails": UpdateKnowledgeBaseSourceUpdateDetails,
    "UpdateKnowledgeBaseSourceUpdateDetailsItem": UpdateKnowledgeBaseSourceUpdateDetailsItem,
    "UpdateMasterCatalogDetails": UpdateMasterCatalogDetails,
    "UpdateMcpToolNodeDetails": UpdateMcpToolNodeDetails,
    "UpdateModelVersionDetails": UpdateModelVersionDetails,
    "UpdateModelVersionResponseDetails": UpdateModelVersionResponseDetails,
    "UpdateModelVersionTagsDetails": UpdateModelVersionTagsDetails,
    "UpdateModelVersionTagsResponseDetails": UpdateModelVersionTagsResponseDetails,
    "UpdateNlToSqlToolDetails": UpdateNlToSqlToolDetails,
    "UpdatePromptToolDetails": UpdatePromptToolDetails,
    "UpdatePromptToolNodeDetails": UpdatePromptToolNodeDetails,
    "UpdateRagToolDetails": UpdateRagToolDetails,
    "UpdateRagToolNodeDetails": UpdateRagToolNodeDetails,
    "UpdateRecipientDetails": UpdateRecipientDetails,
    "UpdateRegisteredModelDetails": UpdateRegisteredModelDetails,
    "UpdateRegisteredModelResponseDetails": UpdateRegisteredModelResponseDetails,
    "UpdateRegisteredModelTagsDetails": UpdateRegisteredModelTagsDetails,
    "UpdateRegisteredModelTagsResponseDetails": UpdateRegisteredModelTagsResponseDetails,
    "UpdateRoleDetails": UpdateRoleDetails,
    "UpdateSchemaDetails": UpdateSchemaDetails,
    "UpdateSettingDetails": UpdateSettingDetails,
    "UpdateShareDetails": UpdateShareDetails,
    "UpdateSparkClusterDetails": UpdateSparkClusterDetails,
    "UpdateSqlToolDetails": UpdateSqlToolDetails,
    "UpdateSqlToolNodeDetails": UpdateSqlToolNodeDetails,
    "UpdateTableDetails": UpdateTableDetails,
    "UpdateTableFieldDetails": UpdateTableFieldDetails,
    "UpdateToolDetails": UpdateToolDetails,
    "UpdateUserSettingDetails": UpdateUserSettingDetails,
    "UpdateViewDetails": UpdateViewDetails,
    "UpdateVolumeDetails": UpdateVolumeDetails,
    "UpdateWorkspaceAsyncOperationStatusDetails": UpdateWorkspaceAsyncOperationStatusDetails,
    "UpdateWorkspaceDetails": UpdateWorkspaceDetails,
    "UploadFileWithParDetails": UploadFileWithParDetails,
    "UploadFileWithParResult": UploadFileWithParResult,
    "UserSetting": UserSetting,
    "UserSettingCollection": UserSettingCollection,
    "UserSettingSummary": UserSettingSummary,
    "ValidateAgentFlowDiagramDetails": ValidateAgentFlowDiagramDetails,
    "ValidateAgentFlowResponse": ValidateAgentFlowResponse,
    "ValidateBundleDetails": ValidateBundleDetails,
    "ValidateViewSqlDetails": ValidateViewSqlDetails,
    "ValidationError": ValidationError,
    "VaultReferenceCredentialDetails": VaultReferenceCredentialDetails,
    "View": View,
    "ViewCollection": ViewCollection,
    "ViewFieldDetails": ViewFieldDetails,
    "ViewPermissionCollection": ViewPermissionCollection,
    "ViewPermissionSummary": ViewPermissionSummary,
    "ViewProperty": ViewProperty,
    "ViewSqlParseDetails": ViewSqlParseDetails,
    "ViewSummary": ViewSummary,
    "ViewUpdateDetails": ViewUpdateDetails,
    "Volume": Volume,
    "VolumeCollection": VolumeCollection,
    "VolumeFile": VolumeFile,
    "VolumeFileClusterLibrarySummary": VolumeFileClusterLibrarySummary,
    "VolumeFileCollection": VolumeFileCollection,
    "VolumeFileSummary": VolumeFileSummary,
    "VolumePermissionCollection": VolumePermissionCollection,
    "VolumePermissionSummary": VolumePermissionSummary,
    "VolumeSummary": VolumeSummary,
    "WordFiltersPolicy": WordFiltersPolicy,
    "WorkerConfig": WorkerConfig,
    "Workspace": Workspace,
    "WorkspaceCollection": WorkspaceCollection,
    "WorkspaceFileClusterLibrarySummary": WorkspaceFileClusterLibrarySummary,
    "WorkspaceNetworkConfigurationDetails": WorkspaceNetworkConfigurationDetails,
    "WorkspaceObject": WorkspaceObject,
    "WorkspaceObjectCollection": WorkspaceObjectCollection,
    "WorkspaceObjectDetails": WorkspaceObjectDetails,
    "WorkspaceObjectPermissionCollection": WorkspaceObjectPermissionCollection,
    "WorkspaceObjectPermissionSummary": WorkspaceObjectPermissionSummary,
    "WorkspaceObjectSearchResultsCollection": WorkspaceObjectSearchResultsCollection,
    "WorkspaceObjectSearchSummary": WorkspaceObjectSearchSummary,
    "WorkspaceObjectSummary": WorkspaceObjectSummary,
    "WorkspacePermissionCollection": WorkspacePermissionCollection,
    "WorkspacePermissionSummary": WorkspacePermissionSummary,
    "WorkspaceSearchCriteria": WorkspaceSearchCriteria,
    "WorkspaceSummary": WorkspaceSummary
}
