# Copyright (c) 2026, Oracle and/or its affiliates.  All rights reserved.

[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aidp-python-client"
dynamic = ["version"]
dependencies = ["oci>=2.160.3,<2.161"]
requires-python = ">=3.9"
description = "Python SDK to use Oracle AI Data Platform Workbench."
readme = "README.md"
license = "UPL-1.0"
license-files = ["LICENSE.txt", "NOTICE.txt"]

[project.urls]
Homepage = "https://docs.oracle.com/en/cloud/paas/ai-data-platform/"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["aidp_python_client*"]

[tool.setuptools.dynamic]
version = { file = ["src/VERSION"] }
