/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Active resources of a cluster.
*/
export interface ActiveClusterResources {
    /**
    * Count of active executors. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'activeExecutorCount'?: number;
    /**
    * Count of active cores. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'activeCores'?: number;
    /**
    * Count of active GPU cores. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'activeGpuCores'?: number;
    /**
    * Active memory in GB. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'activeMemoryInGBs'?: number;
    /**
    * Active GPU memory in GB. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'activeGpuMemoryInGBs'?: number;

}

export namespace ActiveClusterResources {






    export function getJsonObj(obj: ActiveClusterResources): object {
        const jsonObj = {...obj, ...{
            





        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ActiveClusterResources): object {
        const jsonObj = {...obj, ...{
            





         }};

        
        
        return jsonObj;
    }
}
