/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary of Setting
*/
export interface AdminSettingSummary {
    /**
    * The unique identifier for the setting.
    */
    'key': string;
    /**
    * A user-friendly name for the setting.
    */
    'name': string;
    /**
    * Setting data type discriminator
    */
    'type': model.SettingType;
    /**
    * Indicates whether this setting is the default.
    */
    'isDefault': boolean;
    /**
    * The date and time when the setting was created.
    */
    'timeCreated': Date;
    /**
    * The date and time when the setting was most recently updated.
    */
    'timeUpdated': Date;
    /**
    * A generic property bag associated with the setting resource
    */
    'properties'?: { [key: string]: any; };

}

export namespace AdminSettingSummary {








    export function getJsonObj(obj: AdminSettingSummary): object {
        const jsonObj = {...obj, ...{
            







        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: AdminSettingSummary): object {
        const jsonObj = {...obj, ...{
            







         }};

        
        
        return jsonObj;
    }
}
