/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Derived model for table summary of a ADW catalog.
*/
export interface AdwTableSummary extends model.TableSummary {

   "entityType": string;
}

export namespace AdwTableSummary {

    export function getJsonObj(obj: AdwTableSummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TableSummary.getJsonObj(obj) as AdwTableSummary, ...{
            
        }};

        
        
        return jsonObj;
    }
    export const entityType = 'ADW';
    export function getDeserializedJsonObj(obj: AdwTableSummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TableSummary.getDeserializedJsonObj(obj) as AdwTableSummary, ...{
            
         }};

        
        
        return jsonObj;
    }
}
