/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * ADW external catalog connection property keys.
**/
export enum AdwExternalCatalogConnectionPropertyKey {
    AdwWalletContentBase64 = "ADW_WALLET_CONTENT_BASE64",
    AdwWalletPassword = "ADW_WALLET_PASSWORD",
    AdwUsername = "ADW_USERNAME",
    AdwPassword = "ADW_PASSWORD",
    AdwTnsAlias = "ADW_TNS_ALIAS",
    AdwStagingTenancyOcid = "ADW_STAGING_TENANCY_OCID",
    AdwStagingRegion = "ADW_STAGING_REGION",
    AdwStagingNamespace = "ADW_STAGING_NAMESPACE",
    AdwStagingBucket = "ADW_STAGING_BUCKET",
    AdwStagingFilePrefix = "ADW_STAGING_FILE_PREFIX"
    
}

export namespace AdwExternalCatalogConnectionPropertyKey {
    export function getJsonObj(obj: AdwExternalCatalogConnectionPropertyKey): AdwExternalCatalogConnectionPropertyKey {
        return obj;
    }
    export function getDeserializedJsonObj(obj: AdwExternalCatalogConnectionPropertyKey): AdwExternalCatalogConnectionPropertyKey {
        return obj;
    }
}

