/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* User-created cluster.
*/
export interface AgentFlowCompute extends model.Cluster {

   "sourceApi": string;
}

export namespace AgentFlowCompute {

    export function getJsonObj(obj: AgentFlowCompute, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Cluster.getJsonObj(obj) as AgentFlowCompute, ...{
            
        }};

        
        
        return jsonObj;
    }
    export const sourceApi = 'AGENT_FLOW_COMPUTE';
    export function getDeserializedJsonObj(obj: AgentFlowCompute, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Cluster.getDeserializedJsonObj(obj) as AgentFlowCompute, ...{
            
         }};

        
        
        return jsonObj;
    }
}
