/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary information of Agent flow in the schema.
*/
export interface AgentFlowSummary {
    /**
    * The unique identifier (UUID) of the Agent flow
    */
    'key': string;
    /**
    * AgentFlow name.
    */
    'displayName': string;
    /**
    * AgentFlow description.
    */
    'description'?: string;
    /**
    * The key of the workspace to which this Agent flow belongs.
    */
    'workspaceKey'?: string;
    /**
    * Path inside volume where the agentFlow json is written
    */
    'pathInfo'?: string;
    /**
    * The type of Agent Flow (Canvas or Code)
    */
    'type'?: AgentFlowSummary.Type;
    /**
    * The key of the Compute where Agent Flow is deployed
    */
    'deploymentComputeKey'?: string;
    /**
    * Agent flow deployment mode.
    */
    'deploymentMode'?: string;
    /**
    * Agent flow uri.
    */
    'uri'?: string;
    /**
    * Agent flow uri state.
    */
    'uriState'?: string;
    /**
    * The path to project entry file
    */
    'entryFilePath'?: string;
    /**
    * The path to dependencies file
    */
    'dependenciesFilePath'?: string;
    /**
    * The current state of the Agent Flow.
    */
    'lifecycleState'?: string;
    /**
    * A message that describes the current state of the Agent Flow in more detail. For example,
* can be used to provide actionable information for a resource in the Failed state.
* 
    */
    'lifecycleDetails'?: string;
    /**
    * The key of the Agent Flow Compute associated with this Agent Flow
    */
    'computeKey'?: string;
    /**
    * The date and time the Agent flow was created.
    */
    'timeCreated'?: Date;
    /**
    * The date and time the Agent flow was updated.
    */
    'timeUpdated'?: Date;
    /**
    * The OCID of the user/principal who created the Agent flow.
    */
    'createdBy'?: string;
    /**
    * The ID of the user who last updated the schema.
    */
    'updatedBy'?: string;

}

export namespace AgentFlowSummary {






    export enum Type {
    
    Canvas = "CANVAS",
    Code = "CODE"

}















    export function getJsonObj(obj: AgentFlowSummary): object {
        const jsonObj = {...obj, ...{
            



















        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: AgentFlowSummary): object {
        const jsonObj = {...obj, ...{
            



















         }};

        
        
        return jsonObj;
    }
}
