/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Agent flow session summary.
*/
export interface AgentFlowSessionSummary {
    /**
    * Display name.
    */
    'displayName': string;
    /**
    * Agent Flow Session identifier.
    */
    'key': string;
    /**
    * The unique identifier (UUID) of the Agent flow
    */
    'agentFlowKey': string;
    /**
    * LifecycleState of an Agent Flow Session or Deployment.
    */
    'lifecycleState'?: model.DeploymentLifecycleState;
    /**
    * The key of the Agent Flow Compute associated with this Agent Flow
    */
    'agentFlowComputeKey'?: string;
    /**
    * The endpointUrl where the client should connect to communicate with the Agent.
    */
    'endpointUrl'?: string;
    /**
    * The date and time the Agent flow session was created.
    */
    'timeCreated': Date;
    /**
    * The OCID of the user/principal who created the Agent flow session.
    */
    'createdBy': string;
    /**
    * The date and time the session was started
    */
    'timeStarted'?: Date;
    /**
    * The date and time the session was ended
    */
    'timeEnded'?: Date;
    /**
    * Agent flow session duration Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'duration'?: number;
    /**
    * Agent flow session token usage Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'tokens'?: number;

}

export namespace AgentFlowSessionSummary {













    export function getJsonObj(obj: AgentFlowSessionSummary): object {
        const jsonObj = {...obj, ...{
            












        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: AgentFlowSessionSummary): object {
        const jsonObj = {...obj, ...{
            












         }};

        
        
        return jsonObj;
    }
}
