/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Aggregated override candidate for an aicompute dependency.
*/
export interface AiComputeOverrideItem {
    /**
    * Aicompute dependency name.
    */
    'name': string;
    /**
    * Variable name used for this override candidate.
    */
    'variableName': string;
    /**
    * Canonical dependency token using {@code .key}.
    */
    'defaultValue': string;
    /**
    * Current override value resolved from {@code .aidp/overrides.yaml} if present.
    */
    'overrideValue': string;
    /**
    * Top-level agentflows that reference this aicompute dependency.
    */
    'agentflows'?: Array<string>;

}

export namespace AiComputeOverrideItem {






    export function getJsonObj(obj: AiComputeOverrideItem): object {
        const jsonObj = {...obj, ...{
            





        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: AiComputeOverrideItem): object {
        const jsonObj = {...obj, ...{
            





         }};

        
        
        return jsonObj;
    }
}
