/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* A Data Lake AiModel details
* 
*/
export interface AiModel extends model.Model {
    /**
    * Provides Ai Model's Capabilities.
    */
    'modelCapabilities'?: Array<model.AiModelCapabilitiesEnum>;
    /**
    * version that is available for that AI Model.
    */
    'modelVersion'?: string;
    /**
    * vendor name for that Model.
    */
    'vendor'?: string;
    /**
    * region source of that model
    */
    'regionId'?: string;

   "modelType": string;
}

export namespace AiModel {





    export function getJsonObj(obj: AiModel, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Model.getJsonObj(obj) as AiModel, ...{
            
                'modelCapabilities': obj.modelCapabilities ?
                
                obj.modelCapabilities.map((item)=>{return model.AiModelCapabilitiesEnum.getJsonObj(item)})
                
                 : undefined,



        }};

        
        
        return jsonObj;
    }
    export const modelType = 'GEN_AI';
    export function getDeserializedJsonObj(obj: AiModel, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Model.getDeserializedJsonObj(obj) as AiModel, ...{
            
                    'modelCapabilities': obj.modelCapabilities ?
                
                obj.modelCapabilities.map((item)=>{return model.AiModelCapabilitiesEnum.getDeserializedJsonObj(item)})
                
                 : undefined,



         }};

        
        
        return jsonObj;
    }
}
