/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * ALH external catalog connection property keys.
**/
export enum AlhExternalCatalogConnectionPropertyKey {
    AlhWalletContentBase64 = "ALH_WALLET_CONTENT_BASE64",
    AlhWalletPassword = "ALH_WALLET_PASSWORD",
    AlhUsername = "ALH_USERNAME",
    AlhPassword = "ALH_PASSWORD",
    AlhTnsAlias = "ALH_TNS_ALIAS",
    AlhStagingTenancyOcid = "ALH_STAGING_TENANCY_OCID",
    AlhStagingRegion = "ALH_STAGING_REGION",
    AlhStagingNamespace = "ALH_STAGING_NAMESPACE",
    AlhStagingBucket = "ALH_STAGING_BUCKET",
    AlhStagingFilePrefix = "ALH_STAGING_FILE_PREFIX"
    
}

export namespace AlhExternalCatalogConnectionPropertyKey {
    export function getJsonObj(obj: AlhExternalCatalogConnectionPropertyKey): AlhExternalCatalogConnectionPropertyKey {
        return obj;
    }
    export function getDeserializedJsonObj(obj: AlhExternalCatalogConnectionPropertyKey): AlhExternalCatalogConnectionPropertyKey {
        return obj;
    }
}

