/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* FileInfo of Artifact.
*/
export interface ArtifactFileInfo {
    /**
    * Path relative to the root artifact directory run.
    */
    'path'?: string;
    /**
    * Whether the path is a directory.
    */
    'isDir'?: boolean;
    /**
    * Size in bytes. Unset for directories. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'fileSize'?: number;

}

export namespace ArtifactFileInfo {




    export function getJsonObj(obj: ArtifactFileInfo): object {
        const jsonObj = {...obj, ...{
            

                'is_dir': obj.isDir,

                'file_size': obj.fileSize,

        }};

        delete (jsonObj as Partial<ArtifactFileInfo>).isDir;delete (jsonObj as Partial<ArtifactFileInfo>).fileSize;
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ArtifactFileInfo): object {
        const jsonObj = {...obj, ...{
            

                'isDir': (obj as any)["is_dir"],

                'fileSize': (obj as any)["file_size"],

         }};

        delete (jsonObj as any)["is_dir"];delete (jsonObj as any)["file_size"];
        
        return jsonObj;
    }
}
