/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Result of listing Artifacts.
*/
export interface ArtifactList {
    /**
    * Root artifact directory for the run.
    */
    'rootUri'?: string;
    /**
    * File location and metadata for artifacts.
    */
    'files'?: Array<model.ArtifactFileInfo>;
    /**
    * Token that can be used to retrieve the next page of artifact results.
    */
    'nextPageToken'?: string;

}

export namespace ArtifactList {




    export function getJsonObj(obj: ArtifactList): object {
        const jsonObj = {...obj, ...{
            
                'root_uri': obj.rootUri,

                'files': obj.files ?
                
                obj.files.map((item)=>{return model.ArtifactFileInfo.getJsonObj(item)})
                
                 : undefined,
                'next_page_token': obj.nextPageToken,

        }};

        delete (jsonObj as Partial<ArtifactList>).rootUri;delete (jsonObj as Partial<ArtifactList>).nextPageToken;
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ArtifactList): object {
        const jsonObj = {...obj, ...{
            
                'rootUri': (obj as any)["root_uri"],

                    'files': obj.files ?
                
                obj.files.map((item)=>{return model.ArtifactFileInfo.getDeserializedJsonObj(item)})
                
                 : undefined,
                'nextPageToken': (obj as any)["next_page_token"],

         }};

        delete (jsonObj as any)["root_uri"];delete (jsonObj as any)["next_page_token"];
        
        return jsonObj;
    }
}
