/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Auth configuration while using bearer token
*/
export interface BearerTokenAuth extends model.Auth {
    /**
    * The bearer token used for auth
    */
    'token'?: string;

   "authType": string;
}

export namespace BearerTokenAuth {


    export function getJsonObj(obj: BearerTokenAuth, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Auth.getJsonObj(obj) as BearerTokenAuth, ...{
            

        }};

        
        
        return jsonObj;
    }
    export const authType = 'BEARER_TOKEN';
    export function getDeserializedJsonObj(obj: BearerTokenAuth, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Auth.getDeserializedJsonObj(obj) as BearerTokenAuth, ...{
            

         }};

        
        
        return jsonObj;
    }
}
