/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Override candidates grouped by dependency for compute and aicompute.
*/
export interface BundleOverrides {
    /**
    * Compute override candidates grouped by dependency.
    */
    'compute': Array<model.ComputeOverrideItem>;
    /**
    * Aicompute override candidates grouped by dependency.
    */
    'aicompute': Array<model.AiComputeOverrideItem>;

}

export namespace BundleOverrides {



    export function getJsonObj(obj: BundleOverrides): object {
        const jsonObj = {...obj, ...{
            
                'compute': obj.compute ?
                
                obj.compute.map((item)=>{return model.ComputeOverrideItem.getJsonObj(item)})
                
                 : undefined,
                'aicompute': obj.aicompute ?
                
                obj.aicompute.map((item)=>{return model.AiComputeOverrideItem.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: BundleOverrides): object {
        const jsonObj = {...obj, ...{
            
                    'compute': obj.compute ?
                
                obj.compute.map((item)=>{return model.ComputeOverrideItem.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'aicompute': obj.aicompute ?
                
                obj.aicompute.map((item)=>{return model.AiComputeOverrideItem.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
