/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Descriptor for a workspace resource (Job/Agentflow) to include in a bundle.
*/
export interface BundledResource {
    /**
    * Type of resource (job or agentflow)
    */
    'resourceType': BundledResource.ResourceType;
    /**
    * Workspace unique key for the resource
    */
    'resourceKey': string;

}

export namespace BundledResource {

    export enum ResourceType {
    
    Job = "JOB",
    Agentflow = "AGENTFLOW"

}



    export function getJsonObj(obj: BundledResource): object {
        const jsonObj = {...obj, ...{
            


        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: BundledResource): object {
        const jsonObj = {...obj, ...{
            


         }};

        
        
        return jsonObj;
    }
}
