/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The content of the chat query sent by the user.
*/
export interface ChatMessage {
    /**
    * Type of input.
    */
    'type': ChatMessage.Type;
    /**
    * Text input from the user. Set this parameter when type is input_text.
    */
    'text'?: string;
    /**
    * Image URL for the image user intends to query. Set this parameter when type is input_image.
    */
    'imageUrl'?: string;
    /**
    * File URL for the image user intends to query. Set this parameter when type is input_file.
    */
    'fileUrl'?: string;

}

export namespace ChatMessage {

    export enum Type {
    
    InputText = "INPUT_TEXT",
    InputImage = "INPUT_IMAGE",
    InputFile = "INPUT_FILE"

}





    export function getJsonObj(obj: ChatMessage): object {
        const jsonObj = {...obj, ...{
            




        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ChatMessage): object {
        const jsonObj = {...obj, ...{
            




         }};

        
        
        return jsonObj;
    }
}
