/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Response payload containing search results and metadata.
*/
export interface ClusterLogsSummary {
    /**
    * List of log field schema information.
    */
    'fields'?: Array<model.FieldInfo>;
    /**
    * List of search results.
    */
    'results': Array<model.SearchResult>;
    'summary': model.SearchResultSummary;

}

export namespace ClusterLogsSummary {




    export function getJsonObj(obj: ClusterLogsSummary): object {
        const jsonObj = {...obj, ...{
            
                'fields': obj.fields ?
                
                obj.fields.map((item)=>{return model.FieldInfo.getJsonObj(item)})
                
                 : undefined,
                'results': obj.results ?
                
                obj.results.map((item)=>{return model.SearchResult.getJsonObj(item)})
                
                 : undefined,
                'summary': obj.summary ?
                
                
                model.SearchResultSummary.getJsonObj(obj.summary) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ClusterLogsSummary): object {
        const jsonObj = {...obj, ...{
            
                    'fields': obj.fields ?
                
                obj.fields.map((item)=>{return model.FieldInfo.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'results': obj.results ?
                
                obj.results.map((item)=>{return model.SearchResult.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'summary': obj.summary ?
                
                
                model.SearchResultSummary.getDeserializedJsonObj(obj.summary) : undefined,
         }};

        
        
        return jsonObj;
    }
}
