/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Properties of a event provided by the cluster.
*/
export interface ClusterEvent {

   "type": string;
}

export namespace ClusterEvent {

    export function getJsonObj(obj: ClusterEvent): object {
        const jsonObj = {...obj, ...{
            
        }};

        
        
        if (obj && "type" in obj && obj.type) {
            switch (obj.type) {
                case "CLUSTER_STATE_EVENT":
                    return model.ClusterStateEvent.getJsonObj(<model.ClusterStateEvent>(<object>jsonObj), true);
                case "CLUSTER_PATCH_EVENT":
                    return model.ClusterPatchEvent.getJsonObj(<model.ClusterPatchEvent>(<object>jsonObj), true);
                case "CLUSTER_EXECUTION_CONTEXT_AVAILABILITY_EVENT":
                    return model.ClusterExecutionContextAvailabilityEvent.getJsonObj(<model.ClusterExecutionContextAvailabilityEvent>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`)

        }
        }
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ClusterEvent): object {
        const jsonObj = {...obj, ...{
            
         }};

        
        
        if (obj && "type" in obj && obj.type) {
            switch (obj.type) {
                case "CLUSTER_STATE_EVENT":
                    return model.ClusterStateEvent.getDeserializedJsonObj(<model.ClusterStateEvent>(<object>jsonObj), true);
                case "CLUSTER_PATCH_EVENT":
                    return model.ClusterPatchEvent.getDeserializedJsonObj(<model.ClusterPatchEvent>(<object>jsonObj), true);
                case "CLUSTER_EXECUTION_CONTEXT_AVAILABILITY_EVENT":
                    return model.ClusterExecutionContextAvailabilityEvent.getDeserializedJsonObj(<model.ClusterExecutionContextAvailabilityEvent>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.type}`)
        }
        }
        return jsonObj;
    }
}
