/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The cluster used for this run.
* The value of this field will be set when a new cluster is specified for execution and once the request to create a new cluster is successfully submitted.
* 
*/
export interface ClusterInstance {
    /**
    * The cluster key for the cluster configuration on which the job is executed.
    */
    'clusterKey'?: string;
    /**
    * The spark context used in the job run.
    */
    'sparkContextKey'?: string;

}

export namespace ClusterInstance {



    export function getJsonObj(obj: ClusterInstance): object {
        const jsonObj = {...obj, ...{
            


        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ClusterInstance): object {
        const jsonObj = {...obj, ...{
            


         }};

        
        
        return jsonObj;
    }
}
