/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Cluster specification snapshot of a job.
*/
export interface ClusterSpec {
    /**
    * The key of the cluster.
    */
    'existingClusterKey'?: string;
    'newCluster'?: model.NewClusterConfiguration;
    'libraries'?: model.Libraries;

}

export namespace ClusterSpec {




    export function getJsonObj(obj: ClusterSpec): object {
        const jsonObj = {...obj, ...{
            

                'newCluster': obj.newCluster ?
                
                
                model.NewClusterConfiguration.getJsonObj(obj.newCluster) : undefined,
                'libraries': obj.libraries ?
                
                
                model.Libraries.getJsonObj(obj.libraries) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ClusterSpec): object {
        const jsonObj = {...obj, ...{
            

                    'newCluster': obj.newCluster ?
                
                
                model.NewClusterConfiguration.getDeserializedJsonObj(obj.newCluster) : undefined,
                    'libraries': obj.libraries ?
                
                
                model.Libraries.getDeserializedJsonObj(obj.libraries) : undefined,
         }};

        
        
        return jsonObj;
    }
}
