/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The configuration details, whether to add the content moderation feature to the model. Content moderation removes toxic and biased content from responses.
*/
export interface ContentModerationConfig {
    /**
    * Enum for the modes of operation for inference protection.
    */
    'mode'?: ContentModerationConfig.Mode;
    /**
    * The OCID of the model used for the feature.
    */
    'modelId'?: string;
    /**
    * Whether to enable the content moderation feature.
    */
    'isEnabled': boolean;

}

export namespace ContentModerationConfig {

    export enum Mode {
    
    Inform = "INFORM",
    Block = "BLOCK"

}




    export function getJsonObj(obj: ContentModerationConfig): object {
        const jsonObj = {...obj, ...{
            



        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ContentModerationConfig): object {
        const jsonObj = {...obj, ...{
            



         }};

        
        
        return jsonObj;
    }
}
