/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Configuration for a content moderation category
*/
export interface ContentModerationCategoryConfig {
    /**
    * Content moderation category
    */
    'category': model.ContentModerationCategory;
    /**
    * Whether this category is enabled
    */
    'isEnabled': boolean;
    /**
    * Threshold value for this category (0.0 to 1.0) Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'threshold': number;
    /**
    * Action to take for this category
    */
    'action': model.PolicyAction;

}

export namespace ContentModerationCategoryConfig {





    export function getJsonObj(obj: ContentModerationCategoryConfig): object {
        const jsonObj = {...obj, ...{
            




        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ContentModerationCategoryConfig): object {
        const jsonObj = {...obj, ...{
            




         }};

        
        
        return jsonObj;
    }
}
