/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details to create a NL to SQL Tool
*/
export interface CreateNlToSqlToolDetails extends model.CreateToolDetails {
    'inputSchema'?: model.NlToSqlToolInputSchema;
    'toolConfig'?: model.NlToSqlToolConfiguration;

   "toolType": string;
}

export namespace CreateNlToSqlToolDetails {



    export function getJsonObj(obj: CreateNlToSqlToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.CreateToolDetails.getJsonObj(obj) as CreateNlToSqlToolDetails, ...{
            
                'inputSchema': obj.inputSchema ?
                
                
                model.NlToSqlToolInputSchema.getJsonObj(obj.inputSchema) : undefined,
                'toolConfig': obj.toolConfig ?
                
                
                model.NlToSqlToolConfiguration.getJsonObj(obj.toolConfig) : undefined,
        }};

        
        
        return jsonObj;
    }
    export const toolType = 'NL2SQL';
    export function getDeserializedJsonObj(obj: CreateNlToSqlToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.CreateToolDetails.getDeserializedJsonObj(obj) as CreateNlToSqlToolDetails, ...{
            
                    'inputSchema': obj.inputSchema ?
                
                
                model.NlToSqlToolInputSchema.getDeserializedJsonObj(obj.inputSchema) : undefined,
                    'toolConfig': obj.toolConfig ?
                
                
                model.NlToSqlToolConfiguration.getDeserializedJsonObj(obj.toolConfig) : undefined,
         }};

        
        
        return jsonObj;
    }
}
