/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The data to create a RegisteredModel.
*/
export interface CreateRegisteredModelDetails {
    /**
    * Register models under this name.
    */
    'name': string;
    /**
    * Tags for the registered model.
    */
    'tags'?: Array<model.RegisteredModelTag>;
    /**
    * Description for the registered model.
    */
    'description'?: string;
    /**
    * Deployment job id for this model.
    */
    'deploymentJobId'?: string;

}

export namespace CreateRegisteredModelDetails {





    export function getJsonObj(obj: CreateRegisteredModelDetails): object {
        const jsonObj = {...obj, ...{
            

                'tags': obj.tags ?
                
                obj.tags.map((item)=>{return model.RegisteredModelTag.getJsonObj(item)})
                
                 : undefined,

                'deployment_job_id': obj.deploymentJobId,

        }};

        delete (jsonObj as Partial<CreateRegisteredModelDetails>).deploymentJobId;
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CreateRegisteredModelDetails): object {
        const jsonObj = {...obj, ...{
            

                    'tags': obj.tags ?
                
                obj.tags.map((item)=>{return model.RegisteredModelTag.getDeserializedJsonObj(item)})
                
                 : undefined,

                'deploymentJobId': (obj as any)["deployment_job_id"],

         }};

        delete (jsonObj as any)["deployment_job_id"];
        
        return jsonObj;
    }
}
