/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details required to create a new session of an Agent Flow.
*/
export interface CreateAgentFlowSessionDetails {
    /**
    * Display name.
    */
    'displayName'?: string;
    /**
    * The unique identifier (UUID) of the Agent flow
    */
    'agentFlowKey': string;
    'context'?: model.AgentFlowSessionContext;

}

export namespace CreateAgentFlowSessionDetails {




    export function getJsonObj(obj: CreateAgentFlowSessionDetails): object {
        const jsonObj = {...obj, ...{
            


                'context': obj.context ?
                
                
                model.AgentFlowSessionContext.getJsonObj(obj.context) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CreateAgentFlowSessionDetails): object {
        const jsonObj = {...obj, ...{
            


                    'context': obj.context ?
                
                
                model.AgentFlowSessionContext.getDeserializedJsonObj(obj.context) : undefined,
         }};

        
        
        return jsonObj;
    }
}
