/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Request body to create a new Bundle.
*/
export interface CreateBundleDetails {
    /**
    * Name for the new bundle
    */
    'name': string;
    /**
    * Description for the bundle
    */
    'description'?: string;
    /**
    * Target folder for the new bundle
    */
    'path': string;
    /**
    * List of workspace resource descriptors (jobs, agentflows) to be included.
* Each has minimally resourceType and resourceKey.
* 
    */
    'bundledResources': Array<model.BundledResource>;

}

export namespace CreateBundleDetails {





    export function getJsonObj(obj: CreateBundleDetails): object {
        const jsonObj = {...obj, ...{
            



                'bundledResources': obj.bundledResources ?
                
                obj.bundledResources.map((item)=>{return model.BundledResource.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CreateBundleDetails): object {
        const jsonObj = {...obj, ...{
            



                    'bundledResources': obj.bundledResources ?
                
                obj.bundledResources.map((item)=>{return model.BundledResource.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
