/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Configuration for a custom tool package uploaded to the workspace volume.
*/
export interface CustomToolConfiguration {
    /**
    * Human-readable name for this tool package
    */
    'displayName'?: string;
    /**
    * Description of the tool package
    */
    'description'?: string;
    /**
    * Tool package version
    */
    'version'?: string;
    /**
    * Workspace volume path to the uploaded ZIP file
    */
    'packagePath'?: string;
    /**
    * SHA256 hash of requirements.txt for dependency caching
    */
    'requirementsHash'?: string;
    'auth'?: model.OciResourcePrincipalAuth| model.BearerTokenAuth| model.NoAuth| model.OAuth;
    /**
    * Tool provider identifier
    */
    'toolProvider'?: string;
    /**
    * List of tool class entries in this package (multi-tool support)
    */
    'tools'?: Array<model.CustomToolEntry>;

}

export namespace CustomToolConfiguration {









    export function getJsonObj(obj: CustomToolConfiguration): object {
        const jsonObj = {...obj, ...{
            





                'auth': obj.auth ?
                
                
                model.Auth.getJsonObj(obj.auth) : undefined,

                'tools': obj.tools ?
                
                obj.tools.map((item)=>{return model.CustomToolEntry.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CustomToolConfiguration): object {
        const jsonObj = {...obj, ...{
            





                    'auth': obj.auth ?
                
                
                model.Auth.getDeserializedJsonObj(obj.auth) : undefined,

                    'tools': obj.tools ?
                
                obj.tools.map((item)=>{return model.CustomToolEntry.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
