/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* A single tool class entry within a custom tool package
*/
export interface CustomToolEntry {
    /**
    * Python class name (e.g., WeatherTool, BashTool)
    */
    'toolClassName': string;
    /**
    * Human-readable tool name shown to LLM
    */
    'displayName': string;
    /**
    * Tool description for LLM tool selection
    */
    'description'?: string;
    /**
    * Tool version
    */
    'version'?: string;
    /**
    * Tool-specific configuration values (supports template variables)
    */
    'config'?: { [key: string]: any; };
    /**
    * JSON schema for tool input parameters
    */
    'inputSchema'?: { [key: string]: any; };

}

export namespace CustomToolEntry {







    export function getJsonObj(obj: CustomToolEntry): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CustomToolEntry): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
