/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Custom PII detection rule
*/
export interface CustomPiiRule {
    /**
    * Name of the custom rule
    */
    'name': string;
    /**
    * Regex pattern for detection
    */
    'pattern': string;
    /**
    * Prefix pattern to match
    */
    'prefix'?: string;
    /**
    * Suffix pattern to match
    */
    'suffix'?: string;
    /**
    * Whether the pattern is case sensitive
    */
    'isCaseSensitive'?: boolean;
    /**
    * Maximum distance for pattern matching Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'maxDistance'?: number;
    /**
    * Priority of this rule Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'priority'?: number;

}

export namespace CustomPiiRule {








    export function getJsonObj(obj: CustomPiiRule): object {
        const jsonObj = {...obj, ...{
            







        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: CustomPiiRule): object {
        const jsonObj = {...obj, ...{
            







         }};

        
        
        return jsonObj;
    }
}
