/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary information for an endpoint resource.
*/
export interface DacEndpointSummary {
    /**
    * An OCID that uniquely identifies this endpoint resource.
    */
    'id': string;
    /**
    * A user-friendly name. Does not have to be unique, and it's changeable.
    */
    'displayName'?: string;
    /**
    * An optional description of the endpoint.
    */
    'description'?: string;
    /**
    * The OCID of the model that's used to create this endpoint.
    */
    'modelId': string;
    /**
    * The compartment OCID to create the endpoint in.
    */
    'compartmentId': string;
    /**
    * The OCID of the dedicated AI cluster on which a model will be deployed to.
    */
    'dedicatedAiClusterId': string;
    /**
    * The date and time that the endpoint was created in the format of an RFC3339 datetime string.
    */
    'timeCreated': Date;
    /**
    * The date and time the endpoint was updated in the format of n RFC3339 datetime string.
    */
    'timeUpdated'?: Date;
    /**
    * The current state of the endpoint.
* Allowed values are:
* - ACTIVE
* - CREATING
* - UPDATING
* - DELETING
* - DELETED
* - FAILED
* 
    */
    'lifecycleState': DacEndpointSummary.LifecycleState;
    /**
    * A message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in Failed state.
    */
    'lifecycleDetails'?: string;
    'contentModerationConfig'?: model.ContentModerationConfig;
    /**
    * System tags for this resource. Each key is predefined and scoped to a namespace.
* <p>
Example: {@code {\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}}
* 
    */
    'systemTags'?: { [key: string]: { [key: string]: any; }; };

}

export namespace DacEndpointSummary {









    export enum LifecycleState {
    
    Active = "ACTIVE",
    Creating = "CREATING",
    Updating = "UPDATING",
    Deleting = "DELETING",
    Deleted = "DELETED",
    Failed = "FAILED"

}





    export function getJsonObj(obj: DacEndpointSummary): object {
        const jsonObj = {...obj, ...{
            










                'contentModerationConfig': obj.contentModerationConfig ?
                
                
                model.ContentModerationConfig.getJsonObj(obj.contentModerationConfig) : undefined,

        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: DacEndpointSummary): object {
        const jsonObj = {...obj, ...{
            










                    'contentModerationConfig': obj.contentModerationConfig ?
                
                
                model.ContentModerationConfig.getDeserializedJsonObj(obj.contentModerationConfig) : undefined,

         }};

        
        
        return jsonObj;
    }
}
