/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information about the list of AI Data Platform Workbench clusters contained within a workspace.
*/
export interface DataLakeClusterSummary {
    /**
    * Key of the AI Data Platform Workbench workspace.
    */
    'workspaceKey': string;
    /**
    * Name of the AI Data Platform Workbench workspace.
    */
    'workspaceDisplayName': string;
    /**
    * List of clusters.
    */
    'clusters'?: Array<model.ClusterSummary>;

}

export namespace DataLakeClusterSummary {




    export function getJsonObj(obj: DataLakeClusterSummary): object {
        const jsonObj = {...obj, ...{
            


                'clusters': obj.clusters ?
                
                obj.clusters.map((item)=>{return model.ClusterSummary.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: DataLakeClusterSummary): object {
        const jsonObj = {...obj, ...{
            


                    'clusters': obj.clusters ?
                
                obj.clusters.map((item)=>{return model.ClusterSummary.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
