/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Deprovision user schemas created by AI Data Platform Workbench.
*/
export interface DeProvisionUserSchemasDetails extends model.ExecuteDatabaseUserWorkflowsDetails {

   "actionType": string;
}

export namespace DeProvisionUserSchemasDetails {

    export function getJsonObj(obj: DeProvisionUserSchemasDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getJsonObj(obj) as DeProvisionUserSchemasDetails, ...{
            
        }};

        
        
        return jsonObj;
    }
    export const actionType = 'DEPROVISION_USER_SCHEMAS';
    export function getDeserializedJsonObj(obj: DeProvisionUserSchemasDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getDeserializedJsonObj(obj) as DeProvisionUserSchemasDetails, ...{
            
         }};

        
        
        return jsonObj;
    }
}
