/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * Status of the Run.
**/
export enum DeploymentJobRunState {
    DeploymentJobRunStateUnspecified = "DEPLOYMENT_JOB_RUN_STATE_UNSPECIFIED",
    NoValidDeploymentJobFound = "NO_VALID_DEPLOYMENT_JOB_FOUND",
    Running = "RUNNING",
    Succeeded = "SUCCEEDED",
    Failed = "FAILED",
    Pending = "PENDING",
    Approval = "APPROVAL",
    
    /**
     * This value is used if a service returns a value for this enum that is not recognized by this
     * version of the SDK.
     */
    UnknownValue = "UNKNOWN_VALUE"
}

export namespace DeploymentJobRunState {
    export function getJsonObj(obj: DeploymentJobRunState): DeploymentJobRunState {
        return obj;
    }
    export function getDeserializedJsonObj(obj: DeploymentJobRunState): DeploymentJobRunState {
        return obj;
    }
}

