/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * LifecycleState of an Agent Flow Session or Deployment.
**/
export enum DeploymentLifecycleState {
    Creating = "CREATING",
    Active = "ACTIVE",
    Inactive = "INACTIVE",
    Failed = "FAILED",
    Deleted = "DELETED"
    
}

export namespace DeploymentLifecycleState {
    export function getJsonObj(obj: DeploymentLifecycleState): DeploymentLifecycleState {
        return obj;
    }
    export function getDeserializedJsonObj(obj: DeploymentLifecycleState): DeploymentLifecycleState {
        return obj;
    }
}

