/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The embedding models which need to be enabled along with their storage location.
*/
export interface EmbeddingModelDetails extends model.ExecuteDatabaseUserWorkflowsDetails {
    /**
    * CSV list of models, e.g. \"<all_MiniLM_L12_v2>,<all_MiniLM_L64_v2>\"
    */
    'onnxModelFiles'?: string;
    /**
    * Directory for the models listed in onnxModelFiles.
    */
    'locationUri'?: string;

   "actionType": string;
}

export namespace EmbeddingModelDetails {



    export function getJsonObj(obj: EmbeddingModelDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getJsonObj(obj) as EmbeddingModelDetails, ...{
            


        }};

        
        
        return jsonObj;
    }
    export const actionType = 'LOAD_EMBEDDING_MODELS';
    export function getDeserializedJsonObj(obj: EmbeddingModelDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getDeserializedJsonObj(obj) as EmbeddingModelDetails, ...{
            


         }};

        
        
        return jsonObj;
    }
}
