/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Running SQL command.
*/
export interface ExecuteSqlCommandDetails extends model.ExecuteDatabaseUserWorkflowsDetails {
    /**
    * The user schema name. Only supports a valid knowledge base user and ADMIN.
    */
    'userSchemaName'?: string;
    /**
    * Base64-encoded SQL command.
    */
    'sqlCommand'?: string;

   "actionType": string;
}

export namespace ExecuteSqlCommandDetails {



    export function getJsonObj(obj: ExecuteSqlCommandDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getJsonObj(obj) as ExecuteSqlCommandDetails, ...{
            


        }};

        
        
        return jsonObj;
    }
    export const actionType = 'EXECUTE_SQL_COMMAND';
    export function getDeserializedJsonObj(obj: ExecuteSqlCommandDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ExecuteDatabaseUserWorkflowsDetails.getDeserializedJsonObj(obj) as ExecuteSqlCommandDetails, ...{
            


         }};

        
        
        return jsonObj;
    }
}
