/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The details for a generated URI for uploading a temporary file in a schema.
*/
export interface GenerateTempFileUploadTargetResponseDetails {
    /**
    * The generated target URI to upload the file, it must be prefixed by object stroage URL.
    */
    'tempFileUploadTarget': string;
    /**
    * The unique key for this request.
    */
    'uploadKey': string;
    /**
    * The exact URI path of the object storage.
    */
    'ociFilePath': string;

}

export namespace GenerateTempFileUploadTargetResponseDetails {




    export function getJsonObj(obj: GenerateTempFileUploadTargetResponseDetails): object {
        const jsonObj = {...obj, ...{
            



        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GenerateTempFileUploadTargetResponseDetails): object {
        const jsonObj = {...obj, ...{
            



         }};

        
        
        return jsonObj;
    }
}
