/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details needed to reset the current branch for a folder context.
*/
export interface GitResetDetails {
    /**
    * Folder path used to locate the git worktree.
    */
    'gitFolderPath'?: string;
    /**
    * Git branch name that is cloned.
    */
    'branchName'?: string;
    /**
    * Commit id / ref to reset to. If omitted, server may default to HEAD~1 for soft reset flows.
    */
    'commitId'?: string;
    /**
    * Reset mode requested.
    */
    'resetMode'?: GitResetDetails.ResetMode;

}

export namespace GitResetDetails {




    export enum ResetMode {
    
    Soft = "SOFT",
    Mixed = "MIXED",
    Hard = "HARD"

}


    export function getJsonObj(obj: GitResetDetails): object {
        const jsonObj = {...obj, ...{
            




        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GitResetDetails): object {
        const jsonObj = {...obj, ...{
            




         }};

        
        
        return jsonObj;
    }
}
