/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details about a git repository
*/
export interface GitRepository {
    /**
    * Unique key associated with repository
    */
    'key': string;
    /**
    * The workspaceKey associated with the git repository
    */
    'workspaceKey': string;
    /**
    * The name of the git branch
    */
    'branchName': string;
    /**
    * The git repository url corresponding to the branch
    */
    'gitUrl': string;
    /**
    * The path of the current git folder which has to be created for the new branch
    */
    'gitFolderPath': string;
    /**
    * The credential setting key
    */
    'credentialKey'?: string;

}

export namespace GitRepository {







    export function getJsonObj(obj: GitRepository): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GitRepository): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
