/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Represents a Git folder object.
*/
export interface GitFolder {
    /**
    * The absolute path of the Git folder user wants to create.
    */
    'folderPath': string;
    /**
    * key corresponding to Git service provider in git provider table.
    */
    'gitProviderKey'?: string;
    /**
    * Git repository url used to clone.
    */
    'gitRepositoryUrl'?: string;
    /**
    * Short description about the git repository.
    */
    'description'?: string;
    /**
    * Git branch name that is cloned.
    */
    'branchName'?: string;
    /**
    * The metadata about the folder, like branchName.
    */
    'folderMetadata'?: { [key: string]: any; };

}

export namespace GitFolder {







    export function getJsonObj(obj: GitFolder): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GitFolder): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
