/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Current git operation state for a repository folder context.
*/
export interface GitOperationState {
    /**
    * Folder path used to locate the git worktree.
    */
    'gitFolderPath': string;
    /**
    * Current git operation state detected.
    */
    'state': GitOperationState.State;
    /**
    * Whether the detected state blocks typical write operations.
    */
    'isBlocking': boolean;
    /**
    * Whether the requested operation is allowed in the current state. If operationName is not provided, this indicates if the repository is in a generally safe state.
    */
    'isAllowed': boolean;
    /**
    * Human-readable hint for UI display.
    */
    'message'?: string;
    /**
    * Current branch name. Empty if detached HEAD.
    */
    'currentBranch'?: string;
    /**
    * Full commit id of HEAD.
    */
    'headCommitId'?: string;
    /**
    * Whether HEAD is detached.
    */
    'isDetached'?: boolean;
    /**
    * Indicates if unmerged/conflicted files exist. This does not include file names.
    */
    'haveConflicts'?: boolean;
    /**
    * Time when the state was computed.
    */
    'timeChecked'?: Date;

}

export namespace GitOperationState {


    export enum State {
    
    Clean = "CLEAN",
    MergeInProgress = "MERGE_IN_PROGRESS",
    RebaseInProgress = "REBASE_IN_PROGRESS",
    PullInProgress = "PULL_IN_PROGRESS",
    DetachedHead = "DETACHED_HEAD",
    Unknown = "UNKNOWN",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}










    export function getJsonObj(obj: GitOperationState): object {
        const jsonObj = {...obj, ...{
            










        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GitOperationState): object {
        const jsonObj = {...obj, ...{
            










         }};

        
        
        return jsonObj;
    }
}
