/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Git configuration used when source is GIT_PROVIDER.
*/
export interface GitConfig {
    /**
    * Git provider.
    */
    'provider'?: GitConfig.Provider;
    /**
    * Git credential to access the repository.
    */
    'credential'?: string;
    /**
    * Git repository URL.
    */
    'repositoryUrl'?: string;
    /**
    * Git branch path.
    */
    'branch'?: string;

}

export namespace GitConfig {

    export enum Provider {
    
    Github = "GITHUB",
    Bitbucket = "BITBUCKET",
    Gitlab = "GITLAB",
    OciDevops = "OCI_DEVOPS",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}





    export function getJsonObj(obj: GitConfig): object {
        const jsonObj = {...obj, ...{
            




        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: GitConfig): object {
        const jsonObj = {...obj, ...{
            




         }};

        
        
        return jsonObj;
    }
}
