/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary information for a commit.
*/
export interface HistorySummary {
    /**
    * Commit SHA.
    */
    'commitId': string;
    /**
    * First line of commit message (subject).
    */
    'message': string;
    /**
    * Commit author display name.
    */
    'authorName': string;
    /**
    * Commit author email (optional).
    */
    'authorEmail'?: string;
    /**
    * Commit authored time (or committed time if you prefer, but be consistent).
    */
    'timeCreated': Date;
    /**
    * True if commit has multiple parents.
    */
    'isMergeCommit'?: boolean;
    /**
    * Parent commit SHAs (empty for root commit). Present to explain merge commits.
    */
    'parents'?: Array<string>;

}

export namespace HistorySummary {








    export function getJsonObj(obj: HistorySummary): object {
        const jsonObj = {...obj, ...{
            







        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: HistorySummary): object {
        const jsonObj = {...obj, ...{
            







         }};

        
        
        return jsonObj;
    }
}
