/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Configuration for HTTP Tool requests
*/
export interface HttpToolConfiguration {
    /**
    * HTTP method (GET, POST, PUT, DELETE, PATCH)
    */
    'method': model.HttpMethod;
    /**
    * Target URL with optional {{variable}} templates
    */
    'url': string;
    /**
    * Optional custom headers
    */
    'headers'?: { [key: string]: string; };
    /**
    * Optional query parameters
    */
    'params'?: { [key: string]: string; };
    /**
    * Optional request body (for POST, PUT, PATCH)
    */
    'body'?: { [key: string]: any; };
    /**
    * Request timeout in seconds Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'timeout'?: number;
    'auth'?: model.OciResourcePrincipalAuth| model.BearerTokenAuth| model.NoAuth| model.OAuth;
    /**
    * Response optimization settings
    */
    'responseOptimization'?: { [key: string]: any; };

}

export namespace HttpToolConfiguration {









    export function getJsonObj(obj: HttpToolConfiguration): object {
        const jsonObj = {...obj, ...{
            






                'auth': obj.auth ?
                
                
                model.Auth.getJsonObj(obj.auth) : undefined,

        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: HttpToolConfiguration): object {
        const jsonObj = {...obj, ...{
            






                    'auth': obj.auth ?
                
                
                model.Auth.getDeserializedJsonObj(obj.auth) : undefined,

         }};

        
        
        return jsonObj;
    }
}
