/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* A node used to represent a human interaction in the flow.
*/
export interface HumanInTheLoopNode extends model.AgentFlowNode {
    /**
    * Extra configuration for the human in the loop node.
    */
    'humanInTheLoopConfig'?: { [key: string]: string; };

   "type": string;
}

export namespace HumanInTheLoopNode {


    export function getJsonObj(obj: HumanInTheLoopNode, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.AgentFlowNode.getJsonObj(obj) as HumanInTheLoopNode, ...{
            

        }};

        
        
        return jsonObj;
    }
    export const type = 'HUMAN_IN_THE_LOOP';
    export function getDeserializedJsonObj(obj: HumanInTheLoopNode, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.AgentFlowNode.getDeserializedJsonObj(obj) as HumanInTheLoopNode, ...{
            

         }};

        
        
        return jsonObj;
    }
}
