/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* IAM user credential setting details
*/
export interface IamUserCredentialUserSetting extends model.SettingData {
    /**
    * User OCID or User Name
    */
    'userId': string;
    /**
    * Tenancy
    */
    'tenancy': string;
    /**
    * Region
    */
    'region': string;
    /**
    * Fingerprint
    */
    'fingerprint': string;
    /**
    * Private API Key
    */
    'privateApiKey': string;

   "type": string;
}

export namespace IamUserCredentialUserSetting {






    export function getJsonObj(obj: IamUserCredentialUserSetting, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SettingData.getJsonObj(obj) as IamUserCredentialUserSetting, ...{
            





        }};

        
        
        return jsonObj;
    }
    export const type = 'IAM_USER_CREDENTIAL';
    export function getDeserializedJsonObj(obj: IamUserCredentialUserSetting, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SettingData.getDeserializedJsonObj(obj) as IamUserCredentialUserSetting, ...{
            





         }};

        
        
        return jsonObj;
    }
}
