/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The information about the If Else task.
*/
export interface IfElseTask extends model.Task {
    /**
    * List of expressions.
    */
    'expressions': Array<model.Expression>;
    /**
    * The condition string which binds expressions from expressions list using AND, OR or NOT operator. Expression key should be used to bind the expressions.
    */
    'condition': string;
    /**
    * An optional list of parameters.
    */
    'parameters'?: Array<model.Parameter>;

   "type": string;
}

export namespace IfElseTask {




    export function getJsonObj(obj: IfElseTask, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Task.getJsonObj(obj) as IfElseTask, ...{
            
                'expressions': obj.expressions ?
                
                obj.expressions.map((item)=>{return model.Expression.getJsonObj(item)})
                
                 : undefined,

                'parameters': obj.parameters ?
                
                obj.parameters.map((item)=>{return model.Parameter.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    export const type = 'IF_ELSE_TASK';
    export function getDeserializedJsonObj(obj: IfElseTask, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Task.getDeserializedJsonObj(obj) as IfElseTask, ...{
            
                    'expressions': obj.expressions ?
                
                obj.expressions.map((item)=>{return model.Expression.getDeserializedJsonObj(item)})
                
                 : undefined,

                    'parameters': obj.parameters ?
                
                obj.parameters.map((item)=>{return model.Parameter.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
