/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Column inferred from location.
*/
export interface InferSchemaColumn {
    /**
    * Name of the column.
    */
    'fieldName'?: string;
    /**
    * Type of the column.
    */
    'fieldType'?: string;
    /**
    * Boolean value indicating if this column is partition column.
    */
    'isPartition'?: boolean;
    /**
    * For partition columns rank value indicates level, for non-partition column the value will be zero. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'rank'?: number;

}

export namespace InferSchemaColumn {





    export function getJsonObj(obj: InferSchemaColumn): object {
        const jsonObj = {...obj, ...{
            




        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: InferSchemaColumn): object {
        const jsonObj = {...obj, ...{
            




         }};

        
        
        return jsonObj;
    }
}
