/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Inferred schema and data.
*/
export interface InferSchemaWithPreview {
    /**
    * Column information obtained by inferring schema.
    */
    'schema': Array<model.InferSchemaColumn>;
    /**
    * Sample preview data.
    */
    'data': Array<{ [key: string]: string; }>;

}

export namespace InferSchemaWithPreview {



    export function getJsonObj(obj: InferSchemaWithPreview): object {
        const jsonObj = {...obj, ...{
            
                'schema': obj.schema ?
                
                obj.schema.map((item)=>{return model.InferSchemaColumn.getJsonObj(item)})
                
                 : undefined,

        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: InferSchemaWithPreview): object {
        const jsonObj = {...obj, ...{
            
                    'schema': obj.schema ?
                
                obj.schema.map((item)=>{return model.InferSchemaColumn.getDeserializedJsonObj(item)})
                
                 : undefined,

         }};

        
        
        return jsonObj;
    }
}
