/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details required to install a library on a cluster.
*/
export interface InstallClusterLibraryDetails extends model.ClusterLibraryDetails {
    /**
    * File path for the library to install. Example - /Workspace/shared/example/test.txt or /Volumes/catalogName/schemaName/volumeName/test.txt
    */
    'path'?: string;

   "operation": string;
}

export namespace InstallClusterLibraryDetails {


    export function getJsonObj(obj: InstallClusterLibraryDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ClusterLibraryDetails.getJsonObj(obj) as InstallClusterLibraryDetails, ...{
            

        }};

        
        
        return jsonObj;
    }
    export const operation = 'INSTALL';
    export function getDeserializedJsonObj(obj: InstallClusterLibraryDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ClusterLibraryDetails.getDeserializedJsonObj(obj) as InstallClusterLibraryDetails, ...{
            

         }};

        
        
        return jsonObj;
    }
}
