/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Derived model for topic of a Kafka external catalog.
*/
export interface KafkaTopicSchema extends model.Schema {
    /**
    * The number of partitions in the Kafka topic.
    */
    'partitions'?: string;
    /**
    * The replication factor.
    */
    'replicationFactor'?: string;
    /**
    * Bootstrap servers for the Kafka topic.
    */
    'bootstrapServers'?: string;
    /**
    * The details of the partitions in Kafka topic.
    */
    'partitionDetails': string;

   "entityType": string;
}

export namespace KafkaTopicSchema {





    export function getJsonObj(obj: KafkaTopicSchema, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Schema.getJsonObj(obj) as KafkaTopicSchema, ...{
            




        }};

        
        
        return jsonObj;
    }
    export const entityType = 'KAFKA_TOPIC';
    export function getDeserializedJsonObj(obj: KafkaTopicSchema, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Schema.getDeserializedJsonObj(obj) as KafkaTopicSchema, ...{
            




         }};

        
        
        return jsonObj;
    }
}
