/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Derived model for topic of a Kafka external catalog.
*/
export interface KafkaTopicSchemaSummary extends model.SchemaSummary {
    /**
    * The number of partitions in the Kafka topic.
    */
    'partitions'?: string;
    /**
    * The replication factor.
    */
    'replicationFactor'?: string;

   "entityType": string;
}

export namespace KafkaTopicSchemaSummary {



    export function getJsonObj(obj: KafkaTopicSchemaSummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SchemaSummary.getJsonObj(obj) as KafkaTopicSchemaSummary, ...{
            


        }};

        
        
        return jsonObj;
    }
    export const entityType = 'KAFKA_TOPIC';
    export function getDeserializedJsonObj(obj: KafkaTopicSchemaSummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SchemaSummary.getDeserializedJsonObj(obj) as KafkaTopicSchemaSummary, ...{
            


         }};

        
        
        return jsonObj;
    }
}
