/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Index configuration details
*/
export interface KnowledgeBaseVectorIndexDetails {
    /**
    * Type of vector index (HNSW or IVF)
    */
    'type'?: model.KnowledgeBaseVectorIndexType;
    'hnswDetails'?: model.KbVHnswIndexDetails;
    'ivfDetails'?: model.KbVIvfIndexDetails;

}

export namespace KnowledgeBaseVectorIndexDetails {




    export function getJsonObj(obj: KnowledgeBaseVectorIndexDetails): object {
        const jsonObj = {...obj, ...{
            

                'hnswDetails': obj.hnswDetails ?
                
                
                model.KbVHnswIndexDetails.getJsonObj(obj.hnswDetails) : undefined,
                'ivfDetails': obj.ivfDetails ?
                
                
                model.KbVIvfIndexDetails.getJsonObj(obj.ivfDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: KnowledgeBaseVectorIndexDetails): object {
        const jsonObj = {...obj, ...{
            

                    'hnswDetails': obj.hnswDetails ?
                
                
                model.KbVHnswIndexDetails.getDeserializedJsonObj(obj.hnswDetails) : undefined,
                    'ivfDetails': obj.ivfDetails ?
                
                
                model.KbVIvfIndexDetails.getDeserializedJsonObj(obj.ivfDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
