/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Description of KB Job Run Statistics.
*/
export interface KnowledgeBaseJobRunData {
    /**
    * Number of records/files added as part of this job run Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'recordsAdded'?: number;
    /**
    * Number of records/files deleted as part of this job run Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'recordsDeleted'?: number;
    /**
    * Number of records/files updated as part of this job run Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'recordsUpdated'?: number;
    /**
    * Size of all the records/files processed as part of this job run Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'recordsAddedUpdatedSize'?: number;
    /**
    * Hint for how job run is getting started.
    */
    'triggerType'?: model.KnowledgeBaseJobRunTriggerType;

}

export namespace KnowledgeBaseJobRunData {






    export function getJsonObj(obj: KnowledgeBaseJobRunData): object {
        const jsonObj = {...obj, ...{
            





        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: KnowledgeBaseJobRunData): object {
        const jsonObj = {...obj, ...{
            





         }};

        
        
        return jsonObj;
    }
}
