/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update data assets on a share.
*/
export interface ManageShareDataAssetDetails {
    /**
    * The action of this update.
    */
    'action': model.ShareDataAssetAction;
    /**
    * The asset type for this update.
    */
    'type': model.ShareDataAssetType;
    /**
    * The data asset name for this operation. For relational assets, it should be fully qualified name. For example, catalog.schema or catalog.schema.table.
* 
    */
    'name': string;
    /**
    * The data asset description for this operation.
* 
    */
    'description'?: string;
    /**
    * Partition clause information, only applicable for TABLE.
* 
    */
    'partition'?: string;
    /**
    * The data asset alias for this operation, only applicable for TABLE and VIEW.
* 
    */
    'alias'?: string;

}

export namespace ManageShareDataAssetDetails {







    export function getJsonObj(obj: ManageShareDataAssetDetails): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageShareDataAssetDetails): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
