/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update permissions on a Knowledge Base.
*/
export interface ManageKnowledgeBasePermissionDetails {
    'assignKnowledgeBasePermissionDetails'?: model.AssignKnowledgeBasePermissionDetails;
    'revokeKnowledgeBasePermissionDetails'?: model.RevokeKnowledgeBasePermissionDetails;

}

export namespace ManageKnowledgeBasePermissionDetails {



    export function getJsonObj(obj: ManageKnowledgeBasePermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignKnowledgeBasePermissionDetails': obj.assignKnowledgeBasePermissionDetails ?
                
                
                model.AssignKnowledgeBasePermissionDetails.getJsonObj(obj.assignKnowledgeBasePermissionDetails) : undefined,
                'revokeKnowledgeBasePermissionDetails': obj.revokeKnowledgeBasePermissionDetails ?
                
                
                model.RevokeKnowledgeBasePermissionDetails.getJsonObj(obj.revokeKnowledgeBasePermissionDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageKnowledgeBasePermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignKnowledgeBasePermissionDetails': obj.assignKnowledgeBasePermissionDetails ?
                
                
                model.AssignKnowledgeBasePermissionDetails.getDeserializedJsonObj(obj.assignKnowledgeBasePermissionDetails) : undefined,
                    'revokeKnowledgeBasePermissionDetails': obj.revokeKnowledgeBasePermissionDetails ?
                
                
                model.RevokeKnowledgeBasePermissionDetails.getDeserializedJsonObj(obj.revokeKnowledgeBasePermissionDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
