/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update permissions on a view.
*/
export interface ManageViewPermissionDetails {
    'assignViewPermissionDetails'?: model.AssignViewPermissionDetails;
    'revokeViewPermissionDetails'?: model.RevokeViewPermissionDetails;

}

export namespace ManageViewPermissionDetails {



    export function getJsonObj(obj: ManageViewPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignViewPermissionDetails': obj.assignViewPermissionDetails ?
                
                
                model.AssignViewPermissionDetails.getJsonObj(obj.assignViewPermissionDetails) : undefined,
                'revokeViewPermissionDetails': obj.revokeViewPermissionDetails ?
                
                
                model.RevokeViewPermissionDetails.getJsonObj(obj.revokeViewPermissionDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageViewPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignViewPermissionDetails': obj.assignViewPermissionDetails ?
                
                
                model.AssignViewPermissionDetails.getDeserializedJsonObj(obj.assignViewPermissionDetails) : undefined,
                    'revokeViewPermissionDetails': obj.revokeViewPermissionDetails ?
                
                
                model.RevokeViewPermissionDetails.getDeserializedJsonObj(obj.revokeViewPermissionDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
