/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update permissions on a Agent flow.
*/
export interface ManageAgentFlowPermissionDetails {
    'assignAgentFlowPermissionDetails'?: model.AssignAgentFlowPermissionDetails;
    'revokeAgentFlowPermissionDetails'?: model.RevokeAgentFlowPermissionDetails;

}

export namespace ManageAgentFlowPermissionDetails {



    export function getJsonObj(obj: ManageAgentFlowPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignAgentFlowPermissionDetails': obj.assignAgentFlowPermissionDetails ?
                
                
                model.AssignAgentFlowPermissionDetails.getJsonObj(obj.assignAgentFlowPermissionDetails) : undefined,
                'revokeAgentFlowPermissionDetails': obj.revokeAgentFlowPermissionDetails ?
                
                
                model.RevokeAgentFlowPermissionDetails.getJsonObj(obj.revokeAgentFlowPermissionDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageAgentFlowPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignAgentFlowPermissionDetails': obj.assignAgentFlowPermissionDetails ?
                
                
                model.AssignAgentFlowPermissionDetails.getDeserializedJsonObj(obj.assignAgentFlowPermissionDetails) : undefined,
                    'revokeAgentFlowPermissionDetails': obj.revokeAgentFlowPermissionDetails ?
                
                
                model.RevokeAgentFlowPermissionDetails.getDeserializedJsonObj(obj.revokeAgentFlowPermissionDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
