/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update permissions on a Credential.
*/
export interface ManageCredentialPermissionDetails {
    'assignCredentialPermissionDetails'?: model.AssignCredentialPermissionDetails;
    'revokeCredentialPermissionDetails'?: model.RevokeCredentialPermissionDetails;

}

export namespace ManageCredentialPermissionDetails {



    export function getJsonObj(obj: ManageCredentialPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignCredentialPermissionDetails': obj.assignCredentialPermissionDetails ?
                
                
                model.AssignCredentialPermissionDetails.getJsonObj(obj.assignCredentialPermissionDetails) : undefined,
                'revokeCredentialPermissionDetails': obj.revokeCredentialPermissionDetails ?
                
                
                model.RevokeCredentialPermissionDetails.getJsonObj(obj.revokeCredentialPermissionDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageCredentialPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignCredentialPermissionDetails': obj.assignCredentialPermissionDetails ?
                
                
                model.AssignCredentialPermissionDetails.getDeserializedJsonObj(obj.assignCredentialPermissionDetails) : undefined,
                    'revokeCredentialPermissionDetails': obj.revokeCredentialPermissionDetails ?
                
                
                model.RevokeCredentialPermissionDetails.getDeserializedJsonObj(obj.revokeCredentialPermissionDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
