/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information to update permissions on a workspace.
*/
export interface ManageWorkspacePermissionDetails {
    'assignWorkspacePermissionDetails'?: model.AssignWorkspacePermissionDetails;
    'revokeWorkspacePermissionDetails'?: model.RevokeWorkspacePermissionDetails;

}

export namespace ManageWorkspacePermissionDetails {



    export function getJsonObj(obj: ManageWorkspacePermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignWorkspacePermissionDetails': obj.assignWorkspacePermissionDetails ?
                
                
                model.AssignWorkspacePermissionDetails.getJsonObj(obj.assignWorkspacePermissionDetails) : undefined,
                'revokeWorkspacePermissionDetails': obj.revokeWorkspacePermissionDetails ?
                
                
                model.RevokeWorkspacePermissionDetails.getJsonObj(obj.revokeWorkspacePermissionDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ManageWorkspacePermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignWorkspacePermissionDetails': obj.assignWorkspacePermissionDetails ?
                
                
                model.AssignWorkspacePermissionDetails.getDeserializedJsonObj(obj.assignWorkspacePermissionDetails) : undefined,
                    'revokeWorkspacePermissionDetails': obj.revokeWorkspacePermissionDetails ?
                
                
                model.RevokeWorkspacePermissionDetails.getDeserializedJsonObj(obj.revokeWorkspacePermissionDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
