/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Mcp object.
*/
export interface McpObject {
    /**
    * name of the mcp object
    */
    'name'?: string;
    /**
    * description of the mcp object
    */
    'description'?: string;

   "objectType": string;
}

export namespace McpObject {



    export function getJsonObj(obj: McpObject): object {
        const jsonObj = {...obj, ...{
            


        }};

        
        
        if (obj && "objectType" in obj && obj.objectType) {
            switch (obj.objectType) {
                case "PROMPT":
                    return model.McpPromptObject.getJsonObj(<model.McpPromptObject>(<object>jsonObj), true);
                case "TOOL":
                    return model.McpToolObject.getJsonObj(<model.McpToolObject>(<object>jsonObj), true);
                case "RESOURCE":
                    return model.McpResourceObject.getJsonObj(<model.McpResourceObject>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.objectType}`)

        }
        }
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: McpObject): object {
        const jsonObj = {...obj, ...{
            


         }};

        
        
        if (obj && "objectType" in obj && obj.objectType) {
            switch (obj.objectType) {
                case "PROMPT":
                    return model.McpPromptObject.getDeserializedJsonObj(<model.McpPromptObject>(<object>jsonObj), true);
                case "TOOL":
                    return model.McpToolObject.getDeserializedJsonObj(<model.McpToolObject>(<object>jsonObj), true);
                case "RESOURCE":
                    return model.McpResourceObject.getDeserializedJsonObj(<model.McpResourceObject>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.objectType}`)
        }
        }
        return jsonObj;
    }
}
