/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Memory configuration for an agent node.
*/
export interface MemoryConfiguration {
    /**
    * Whether agent memory is enabled. When disabled, no conversation history is injected into the LLM context window.
    */
    'isEnabled'?: boolean;
    'limit'?: model.MemoryLimitConfiguration;
    /**
    * Some extra named memory properties.
    */
    'memoryProperties'?: { [key: string]: any; };

}

export namespace MemoryConfiguration {




    export function getJsonObj(obj: MemoryConfiguration): object {
        const jsonObj = {...obj, ...{
            

                'limit': obj.limit ?
                
                
                model.MemoryLimitConfiguration.getJsonObj(obj.limit) : undefined,

        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: MemoryConfiguration): object {
        const jsonObj = {...obj, ...{
            

                    'limit': obj.limit ?
                
                
                model.MemoryLimitConfiguration.getDeserializedJsonObj(obj.limit) : undefined,

         }};

        
        
        return jsonObj;
    }
}
