/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The summary of the Model.
*/
export interface ModelSummary {
    /**
    * A unique Id for the Model summary, that is immutable on creation.
    */
    'id': string;
    /**
    * A unique key for the Model summary, that is immutable on creation.
    */
    'modelName': string;
    /**
    * The Model summary name, it can be changed.
    */
    'displayName'?: string;
    /**
    * version that is available for that Model.
    */
    'modelVersion': string;
    /**
    * vendor name for that Model.
    */
    'vendor'?: string;
    /**
    * Possible modelTypes of Models object
    */
    'modelType': ModelSummary.ModelType;

}

export namespace ModelSummary {






    export enum ModelType {
    
    GenAi = "GEN_AI"

}


    export function getJsonObj(obj: ModelSummary): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ModelSummary): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
