/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Result of listing ModelVersions.
*/
export interface ModelVersionCollection {
    /**
    * ModelVersions that match the search criteria
    */
    'modelVersions': Array<model.ModelVersion>;
    /**
    * Token that can be used to retrieve the next page of ModelVersions.
    */
    'nextPageToken'?: string;

}

export namespace ModelVersionCollection {



    export function getJsonObj(obj: ModelVersionCollection): object {
        const jsonObj = {...obj, ...{
            
                'model_versions': obj.modelVersions ?
                
                obj.modelVersions.map((item)=>{return model.ModelVersion.getJsonObj(item)})
                
                 : undefined,
                'next_page_token': obj.nextPageToken,

        }};

        delete (jsonObj as Partial<ModelVersionCollection>).modelVersions;delete (jsonObj as Partial<ModelVersionCollection>).nextPageToken;
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ModelVersionCollection): object {
        const jsonObj = {...obj, ...{
            
                    'modelVersions': (obj as any)["model_versions"] ?
                
                (obj as any)["model_versions"].map((item: any)=>{return model.ModelVersion.getDeserializedJsonObj(item)})
                
                 : undefined,
                'nextPageToken': (obj as any)["next_page_token"],

         }};

        delete (jsonObj as any)["model_versions"];delete (jsonObj as any)["next_page_token"];
        
        return jsonObj;
    }
}
