/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details to move a workspace object to a different location.
*/
export interface MoveWorkspaceObjectDetails {
    /**
    * The fully qualified path of the workspace object that should be moved.
    */
    'fromPath'?: string;
    /**
    * The fully qualified destination path to which the Workspace object should be moved.
    */
    'toPath'?: string;

}

export namespace MoveWorkspaceObjectDetails {



    export function getJsonObj(obj: MoveWorkspaceObjectDetails): object {
        const jsonObj = {...obj, ...{
            


        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: MoveWorkspaceObjectDetails): object {
        const jsonObj = {...obj, ...{
            


         }};

        
        
        return jsonObj;
    }
}
