/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* An agent node representing a nested Agent Flow
*/
export interface NestedAgentFlowNode extends model.AgentFlowNode {
    /**
    * System prompt written by the flow developer defining the agent\u2019s goal(s) and what tools the agent has access to.
    */
    'instructions'?: string;
    /**
    * Extra configuration for the nested agent flow node.
    */
    'nestedAgentFlowConfig'?: { [key: string]: string; };

   "type": string;
}

export namespace NestedAgentFlowNode {



    export function getJsonObj(obj: NestedAgentFlowNode, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.AgentFlowNode.getJsonObj(obj) as NestedAgentFlowNode, ...{
            


        }};

        
        
        return jsonObj;
    }
    export const type = 'NESTED_AGENT_FLOW';
    export function getDeserializedJsonObj(obj: NestedAgentFlowNode, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.AgentFlowNode.getDeserializedJsonObj(obj) as NestedAgentFlowNode, ...{
            


         }};

        
        
        return jsonObj;
    }
}
