/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Tool configurations are set by the agent developer when they create the tool. | The agent does not see those configurations and can NOT modify their values
*/
export interface NlToSqlToolConfiguration {
    /**
    * The Catalog to use for SQL query execution
    */
    'catalogKey': string;
    /**
    * The Schema to use for SQL query execution
    */
    'schemaKey': string;
    /**
    * The fully qualified table names to use in SQL query generation
    */
    'tables': Array<string>;
    /**
    * The fully qualified column names to use in SQL query generation
    */
    'columns': Array<string>;
    /**
    * Optional few-shot examples (NL \u2192 SQL pairs) for better generation.
    */
    'inContextLearning'?: string;
    /**
    * Additional instructions that is injected in the system prompt
    */
    'additionalInstructions'?: string;

}

export namespace NlToSqlToolConfiguration {







    export function getJsonObj(obj: NlToSqlToolConfiguration): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: NlToSqlToolConfiguration): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
