/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * Node type.
**/
export enum NodeType {
    StartNode = "START_NODE",
    Guardrails = "GUARDRAILS",
    Agent = "AGENT",
    SupervisorAgent = "SUPERVISOR_AGENT",
    NestedAgentFlow = "NESTED_AGENT_FLOW",
    ExternalAgent = "EXTERNAL_AGENT",
    HumanInTheLoop = "HUMAN_IN_THE_LOOP",
    SqlTool = "SQL_TOOL",
    PromptTool = "PROMPT_TOOL",
    RagTool = "RAG_TOOL",
    McpTool = "MCP_TOOL",
    HttpTool = "HTTP_TOOL",
    CustomTool = "CUSTOM_TOOL"
    
}

export namespace NodeType {
    export function getJsonObj(obj: NodeType): NodeType {
        return obj;
    }
    export function getDeserializedJsonObj(obj: NodeType): NodeType {
        return obj;
    }
}

