/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* OCI logging configuration.
*/
export interface OciLogging extends model.LoggingConfig {
    /**
    * Init script paths that are run in the order of definition.
    */
    'logGroups'?: Array<model.LogGroup>;

   "type": string;
}

export namespace OciLogging {


    export function getJsonObj(obj: OciLogging, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.LoggingConfig.getJsonObj(obj) as OciLogging, ...{
            
                'logGroups': obj.logGroups ?
                
                obj.logGroups.map((item)=>{return model.LogGroup.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    export const type = 'OCI_LOGGING';
    export function getDeserializedJsonObj(obj: OciLogging, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.LoggingConfig.getDeserializedJsonObj(obj) as OciLogging, ...{
            
                    'logGroups': obj.logGroups ?
                
                obj.logGroups.map((item)=>{return model.LogGroup.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
