/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Derived model for schema of a Oracle external catalog.
*/
export interface OracleSchema extends model.Schema {

   "entityType": string;
}

export namespace OracleSchema {

    export function getJsonObj(obj: OracleSchema, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Schema.getJsonObj(obj) as OracleSchema, ...{
            
        }};

        
        
        return jsonObj;
    }
    export const entityType = 'ORACLE';
    export function getDeserializedJsonObj(obj: OracleSchema, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.Schema.getDeserializedJsonObj(obj) as OracleSchema, ...{
            
         }};

        
        
        return jsonObj;
    }
}
