/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Prompt attacks prevention safety policy
*/
export interface PromptAttacksPreventionPolicy extends model.SafetyPolicy {

   "policyType": string;
}

export namespace PromptAttacksPreventionPolicy {

    export function getJsonObj(obj: PromptAttacksPreventionPolicy, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SafetyPolicy.getJsonObj(obj) as PromptAttacksPreventionPolicy, ...{
            
        }};

        
        
        return jsonObj;
    }
    export const policyType = 'PROMPT_ATTACKS_PREVENTION';
    export function getDeserializedJsonObj(obj: PromptAttacksPreventionPolicy, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.SafetyPolicy.getDeserializedJsonObj(obj) as PromptAttacksPreventionPolicy, ...{
            
         }};

        
        
        return jsonObj;
    }
}
