/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * Recipient property keys.
**/
export enum RecipientPropertyKey {
    ActivationLinkEmail = "ACTIVATION_LINK_EMAIL",
    DeltaShareEndpoint = "DELTA_SHARE_ENDPOINT",
    ActivationLink = "ACTIVATION_LINK",
    ActivationTokenKey = "ACTIVATION_TOKEN_KEY",
    ActivationTokenExpiryTime = "ACTIVATION_TOKEN_EXPIRY_TIME",
    BearerTokenKey = "BEARER_TOKEN_KEY",
    BearerTokenExpiryTime = "BEARER_TOKEN_EXPIRY_TIME"
    
}

export namespace RecipientPropertyKey {
    export function getJsonObj(obj: RecipientPropertyKey): RecipientPropertyKey {
        return obj;
    }
    export function getDeserializedJsonObj(obj: RecipientPropertyKey): RecipientPropertyKey {
        return obj;
    }
}

