/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The details of the permissions revoked from assignees for a MasterCatalog.
*/
export interface RevokeMasterCatalogPermissionDetails {
    'assignees': model.PermissionAssignees;
    /**
    * The permissions revoked from the assignees
    */
    'permissions': Array<RevokeMasterCatalogPermissionDetails.Permissions>;

}

export namespace RevokeMasterCatalogPermissionDetails {


    export enum Permissions {
    
    CreateCatalog = "CREATE_CATALOG",
    Admin = "ADMIN",
    CreateShare = "CREATE_SHARE",
    CreateRecipient = "CREATE_RECIPIENT",
    CreateCredential = "CREATE_CREDENTIAL"

}


    export function getJsonObj(obj: RevokeMasterCatalogPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                'assignees': obj.assignees ?
                
                
                model.PermissionAssignees.getJsonObj(obj.assignees) : undefined,

        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: RevokeMasterCatalogPermissionDetails): object {
        const jsonObj = {...obj, ...{
            
                    'assignees': obj.assignees ?
                
                
                model.PermissionAssignees.getDeserializedJsonObj(obj.assignees) : undefined,

         }};

        
        
        return jsonObj;
    }
}
