/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Role details.
*/
export interface Role {
    /**
    * A unique key for the role. It cannot be changed.
    */
    'key': string;
    /**
    * The role name. It can be changed.
    */
    'displayName'?: string;
    /**
    * Type of role.
    */
    'roleType'?: model.RoleType;
    /**
    * The time the role was created. An RFC3339 formatted datetime string.
    */
    'timeCreated'?: Date;
    /**
    * The time the Role was updated. An RFC3339 formatted datetime string.
    */
    'timeUpdated'?: Date;
    /**
    * The user name of the user/principal who created the role.
    */
    'createdBy'?: string;
    /**
    * The user name of the user/principal who updated the role.
    */
    'updatedBy'?: string;
    /**
    * The role is assigned to the current user or a group that the user is part of.
    */
    'isAssigned'?: boolean;
    /**
    * The users and groups this role is assigned to.
    */
    'assignees'?: Array<model.RoleAssignee>;
    /**
    * The state of the role.
    */
    'lifecycleState'?: Role.LifecycleState;
    /**
    * A message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in Failed state.
    */
    'lifecycleDetails'?: string;
    /**
    * The description of the role.
    */
    'description'?: string;

}

export namespace Role {










    export enum LifecycleState {
    
    Active = "ACTIVE",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}




    export function getJsonObj(obj: Role): object {
        const jsonObj = {...obj, ...{
            








                'assignees': obj.assignees ?
                
                obj.assignees.map((item)=>{return model.RoleAssignee.getJsonObj(item)})
                
                 : undefined,



        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: Role): object {
        const jsonObj = {...obj, ...{
            








                    'assignees': obj.assignees ?
                
                obj.assignees.map((item)=>{return model.RoleAssignee.getDeserializedJsonObj(item)})
                
                 : undefined,



         }};

        
        
        return jsonObj;
    }
}
