/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * Schema details key. This can be referred to when the related catalog is an external (Non-ADW) catalog.
**/
export enum SchemaDetailsKey {
    Partitions = "PARTITIONS",
    ReplicationFactor = "REPLICATION_FACTOR",
    BootstrapServers = "BOOTSTRAP_SERVERS",
    PartitionsDetails = "PARTITIONS_DETAILS"
    
}

export namespace SchemaDetailsKey {
    export function getJsonObj(obj: SchemaDetailsKey): SchemaDetailsKey {
        return obj;
    }
    export function getDeserializedJsonObj(obj: SchemaDetailsKey): SchemaDetailsKey {
        return obj;
    }
}

