/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * The privilege for a schema.
**/
export enum SchemaPrivilegeForManage {
    Select = "SELECT",
    Write = "WRITE",
    CreateView = "CREATE_VIEW",
    CreateVolume = "CREATE_VOLUME",
    CreateTable = "CREATE_TABLE",
    Admin = "ADMIN",
    CreateKnowledgeBase = "CREATE_KNOWLEDGE_BASE"
    
}

export namespace SchemaPrivilegeForManage {
    export function getJsonObj(obj: SchemaPrivilegeForManage): SchemaPrivilegeForManage {
        return obj;
    }
    export function getDeserializedJsonObj(obj: SchemaPrivilegeForManage): SchemaPrivilegeForManage {
        return obj;
    }
}

