/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The schedule configuration for the job.
*/
export interface Schedule {
    /**
    * A cron expression using Quartz syntax that describes the schedule for a job.
    */
    'quartzCronExpression': string;
    /**
    * A Java timezone ID. The schedule of the job is resolved with respect to this timezone. Example - US/Pacific.
    */
    'timezoneId': string;
    /**
    * Indicates whether the schedule is paused or not.
    */
    'pauseStatus'?: Schedule.PauseStatus;

}

export namespace Schedule {



    export enum PauseStatus {
    
    Paused = "PAUSED",
    Unpaused = "UNPAUSED",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}


    export function getJsonObj(obj: Schedule): object {
        const jsonObj = {...obj, ...{
            



        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: Schedule): object {
        const jsonObj = {...obj, ...{
            



         }};

        
        
        return jsonObj;
    }
}
