/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Credential details for representing service account object. This extends
* the base CredentialDetails object, with the credential type set as SERVICE_ACCOUNT.
* 
*/
export interface ServiceAccountCredentialDetails extends model.CredentialDetails {
    /**
    * The OCID of the user for the service account.
    */
    'userId': string;
    /**
    * The fingerprint of the service account's API key.
    */
    'fingerprint': string;
    /**
    * The OCID of the tenancy for the service account.
    */
    'tenancy': string;
    /**
    * The region for the service account (e.g., us-ashburn-1).
    */
    'region': string;
    /**
    * Whether the credentials are read-only.
    */
    'isReadOnly': boolean;
    /**
    * The private key associated with the service account.
    */
    'privateKey': string;

   "credentialType": string;
}

export namespace ServiceAccountCredentialDetails {







    export function getJsonObj(obj: ServiceAccountCredentialDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.CredentialDetails.getJsonObj(obj) as ServiceAccountCredentialDetails, ...{
            






        }};

        
        
        return jsonObj;
    }
    export const credentialType = 'SERVICE_ACCOUNT';
    export function getDeserializedJsonObj(obj: ServiceAccountCredentialDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.CredentialDetails.getDeserializedJsonObj(obj) as ServiceAccountCredentialDetails, ...{
            






         }};

        
        
        return jsonObj;
    }
}
