/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Session Variable Details.
*/
export interface SessionVariableDetails {
    /**
    * Name of the Session Variable.
    */
    'name': string;
    /**
    * Description of the Session Variable
    */
    'description'?: string;
    /**
    * If this Variable is required or not
    */
    'isRequired'?: boolean;
    /**
    * If we should log this Session Variable or not
    */
    'shouldLog'?: boolean;
    /**
    * True if Session Variable is defined by System
    */
    'isSystem'?: boolean;
    /**
    * Default Value of this Session Variable
    */
    'value'?: string;

}

export namespace SessionVariableDetails {







    export function getJsonObj(obj: SessionVariableDetails): object {
        const jsonObj = {...obj, ...{
            






        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: SessionVariableDetails): object {
        const jsonObj = {...obj, ...{
            






         }};

        
        
        return jsonObj;
    }
}
