/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary information about a share data asset.
*/
export interface ShareDataAssetSummary {
    /**
    * The asset type for this update.
    */
    'type': model.ShareDataAssetType;
    /**
    * The data asset name for this operation.
* 
    */
    'name': string;
    /**
    * The ID of the user who created the share data asset.
* 
    */
    'createdBy': string;
    /**
    * Short description or comment.
    */
    'description'?: string;
    /**
    * The data asset catalog for this operation.
* 
    */
    'catalog'?: string;
    /**
    * Partition clause information, only applicable for TABLE.
* 
    */
    'partition'?: string;
    /**
    * The date and time the Delta Share Data Asset was created, in the format defined by <a href=\"https://tools.ietf.org/html/rfc3339\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 3339</a>.
* Example: {@code 2016-08-25T21:10:29.600Z}
* 
    */
    'timeCreated'?: Date;
    /**
    * The date and time the Delta Share Data Asset was updated, in the format defined by <a href=\"https://tools.ietf.org/html/rfc3339\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 3339</a>.
* Example: {@code 2016-08-25T21:10:29.600Z}
* 
    */
    'timeUpdated'?: Date;

}

export namespace ShareDataAssetSummary {









    export function getJsonObj(obj: ShareDataAssetSummary): object {
        const jsonObj = {...obj, ...{
            








        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ShareDataAssetSummary): object {
        const jsonObj = {...obj, ...{
            








         }};

        
        
        return jsonObj;
    }
}
