/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Span details
*/
export interface SpanDetails {
    /**
    * trace id
    */
    'parentTraceId': string;
    /**
    * span id
    */
    'spanId': string;
    /**
    * parent span id
    */
    'parentSpanId'?: string;
    /**
    * start time Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'startTime': number;
    /**
    * end time Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'endTime': number;
    /**
    * type of span
    */
    'kind': string;
    /**
    * span name
    */
    'spanName': string;
    /**
    * span attributes
    */
    'attributes': { [key: string]: any; };
    /**
    * collections of trace objects
    */
    'events': Array<model.TraceEvent>;
    'status': model.SpanStatus;

}

export namespace SpanDetails {











    export function getJsonObj(obj: SpanDetails): object {
        const jsonObj = {...obj, ...{
            








                'events': obj.events ?
                
                obj.events.map((item)=>{return model.TraceEvent.getJsonObj(item)})
                
                 : undefined,
                'status': obj.status ?
                
                
                model.SpanStatus.getJsonObj(obj.status) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: SpanDetails): object {
        const jsonObj = {...obj, ...{
            








                    'events': obj.events ?
                
                obj.events.map((item)=>{return model.TraceEvent.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'status': obj.status ?
                
                
                model.SpanStatus.getDeserializedJsonObj(obj.status) : undefined,
         }};

        
        
        return jsonObj;
    }
}
