/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Information about a table permission.
*/
export interface TablePermissionSummary {
    /**
    * The OCID of user/group and name in case of role.
    */
    'grantee': string;
    /**
    * The simplified name of the grantee.
    */
    'granteeName'?: string;
    /**
    * The type of grantee.
    */
    'granteeType': model.GranteeType;
    /**
    * The selected permissions for a table.
    */
    'granteePermissions': Array<TablePermissionSummary.GranteePermissions>;
    /**
    * The list of the columns included for permission assignment.
    */
    'columns'?: Array<string>;
    /**
    * The list of the columns excluded from permission assignment.
    */
    'excludeColumns'?: Array<string>;
    /**
    * If the permission listed is inherited or not from object higher up in hierarchy.
    */
    'isInherited'?: boolean;
    /**
    * Name of the object to which this permission belong to. Name of table if permission is not inherited or name of object higher up in hierarchy if permission is inherited.
    */
    'resourceName'?: string;

}

export namespace TablePermissionSummary {




    export enum GranteePermissions {
    
    Select = "SELECT",
    Manage = "MANAGE",
    Write = "WRITE",
    Insert = "INSERT",
    Update = "UPDATE",
    Delete = "DELETE",
    Alter = "ALTER",
    Admin = "ADMIN",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}






    export function getJsonObj(obj: TablePermissionSummary): object {
        const jsonObj = {...obj, ...{
            








        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: TablePermissionSummary): object {
        const jsonObj = {...obj, ...{
            








         }};

        
        
        return jsonObj;
    }
}
