/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Test mcp tool connection
*/
export interface TestMcpExternalTool extends model.TestMcpOperation {
    /**
    * name of external tool to test
    */
    'externalToolName': string;
    'paramValues'?: model.TestToolParamValues;

   "testType": string;
}

export namespace TestMcpExternalTool {



    export function getJsonObj(obj: TestMcpExternalTool, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestMcpOperation.getJsonObj(obj) as TestMcpExternalTool, ...{
            

                'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getJsonObj(obj.paramValues) : undefined,
        }};

        
        
        return jsonObj;
    }
    export const testType = 'EXTERNAL_TOOL';
    export function getDeserializedJsonObj(obj: TestMcpExternalTool, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestMcpOperation.getDeserializedJsonObj(obj) as TestMcpExternalTool, ...{
            

                    'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getDeserializedJsonObj(obj.paramValues) : undefined,
         }};

        
        
        return jsonObj;
    }
}
