/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Request details when toolType = RAG.
*/
export interface TestRagToolDetails extends model.TestToolDetails {
    'config': model.RagToolConfiguration;
    /**
    * The user query or instruction to be augmented with retrieved context.
    */
    'query': string;

   "toolType": string;
}

export namespace TestRagToolDetails {



    export function getJsonObj(obj: TestRagToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getJsonObj(obj) as TestRagToolDetails, ...{
            
                'config': obj.config ?
                
                
                model.RagToolConfiguration.getJsonObj(obj.config) : undefined,

        }};

        
        
        return jsonObj;
    }
    export const toolType = 'RAG';
    export function getDeserializedJsonObj(obj: TestRagToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getDeserializedJsonObj(obj) as TestRagToolDetails, ...{
            
                    'config': obj.config ?
                
                
                model.RagToolConfiguration.getDeserializedJsonObj(obj.config) : undefined,

         }};

        
        
        return jsonObj;
    }
}
