/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Represents a type of testing on mcp.
*/
export interface TestMcpOperation {

   "testType": string;
}

export namespace TestMcpOperation {

    export function getJsonObj(obj: TestMcpOperation): object {
        const jsonObj = {...obj, ...{
            
        }};

        
        
        if (obj && "testType" in obj && obj.testType) {
            switch (obj.testType) {
                case "CONNECTION":
                    return model.TestMcpConnection.getJsonObj(<model.TestMcpConnection>(<object>jsonObj), true);
                case "EXTERNAL_TOOL":
                    return model.TestMcpExternalTool.getJsonObj(<model.TestMcpExternalTool>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.testType}`)

        }
        }
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: TestMcpOperation): object {
        const jsonObj = {...obj, ...{
            
         }};

        
        
        if (obj && "testType" in obj && obj.testType) {
            switch (obj.testType) {
                case "CONNECTION":
                    return model.TestMcpConnection.getDeserializedJsonObj(<model.TestMcpConnection>(<object>jsonObj), true);
                case "EXTERNAL_TOOL":
                    return model.TestMcpExternalTool.getDeserializedJsonObj(<model.TestMcpExternalTool>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.testType}`)
        }
        }
        return jsonObj;
    }
}
