/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Request details when toolType = MCP
*/
export interface TestMcpToolDetails extends model.TestToolDetails {
    'config': model.McpToolConfiguration;
    'mcpTest': model.TestMcpConnection| model.TestMcpExternalTool;
    'paramValues'?: model.TestToolParamValues;
    /**
    * name of mcp server
    */
    'serverName': string;

   "toolType": string;
}

export namespace TestMcpToolDetails {





    export function getJsonObj(obj: TestMcpToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getJsonObj(obj) as TestMcpToolDetails, ...{
            
                'config': obj.config ?
                
                
                model.McpToolConfiguration.getJsonObj(obj.config) : undefined,
                'mcpTest': obj.mcpTest ?
                
                
                model.TestMcpOperation.getJsonObj(obj.mcpTest) : undefined,
                'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getJsonObj(obj.paramValues) : undefined,

        }};

        
        
        return jsonObj;
    }
    export const toolType = 'MCP';
    export function getDeserializedJsonObj(obj: TestMcpToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getDeserializedJsonObj(obj) as TestMcpToolDetails, ...{
            
                    'config': obj.config ?
                
                
                model.McpToolConfiguration.getDeserializedJsonObj(obj.config) : undefined,
                    'mcpTest': obj.mcpTest ?
                
                
                model.TestMcpOperation.getDeserializedJsonObj(obj.mcpTest) : undefined,
                    'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getDeserializedJsonObj(obj.paramValues) : undefined,

         }};

        
        
        return jsonObj;
    }
}
