/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Request details when toolType = HTTP
*/
export interface TestHttpToolDetails extends model.TestToolDetails {
    'config': model.HttpToolConfiguration;
    'paramValues'?: model.TestToolParamValues;

   "toolType": string;
}

export namespace TestHttpToolDetails {



    export function getJsonObj(obj: TestHttpToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getJsonObj(obj) as TestHttpToolDetails, ...{
            
                'config': obj.config ?
                
                
                model.HttpToolConfiguration.getJsonObj(obj.config) : undefined,
                'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getJsonObj(obj.paramValues) : undefined,
        }};

        
        
        return jsonObj;
    }
    export const toolType = 'HTTP';
    export function getDeserializedJsonObj(obj: TestHttpToolDetails, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.TestToolDetails.getDeserializedJsonObj(obj) as TestHttpToolDetails, ...{
            
                    'config': obj.config ?
                
                
                model.HttpToolConfiguration.getDeserializedJsonObj(obj.config) : undefined,
                    'paramValues': obj.paramValues ?
                
                
                model.TestToolParamValues.getDeserializedJsonObj(obj.paramValues) : undefined,
         }};

        
        
        return jsonObj;
    }
}
