/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Trace object
*/
export interface TraceDetails {
    /**
    * trace id
    */
    'traceId': string;
    /**
    * session id
    */
    'parentSessionId': string;
    /**
    * collections of spans
    */
    'spans': Array<model.SpanDetails>;
    /**
    * startTime Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'startTime': number;
    /**
    * endTime Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'endTime': number;
    /**
    * Map of properties
    */
    'resources'?: { [key: string]: any; };

}

export namespace TraceDetails {







    export function getJsonObj(obj: TraceDetails): object {
        const jsonObj = {...obj, ...{
            


                'spans': obj.spans ?
                
                obj.spans.map((item)=>{return model.SpanDetails.getJsonObj(item)})
                
                 : undefined,



        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: TraceDetails): object {
        const jsonObj = {...obj, ...{
            


                    'spans': obj.spans ?
                
                obj.spans.map((item)=>{return model.SpanDetails.getDeserializedJsonObj(item)})
                
                 : undefined,



         }};

        
        
        return jsonObj;
    }
}
