/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Transition details of the model version
*/
export interface TransitionModelVersionStageDetails {
    /**
    * Name of the registered model.
    */
    'name': string;
    /**
    * Model\u2019s version number.
    */
    'version': string;
    /**
    * New stage for the model version.
    */
    'stage': string;
    /**
    * Whether to archive existing versions in the target stage.
    */
    'archiveExistingVersions': boolean;

}

export namespace TransitionModelVersionStageDetails {





    export function getJsonObj(obj: TransitionModelVersionStageDetails): object {
        const jsonObj = {...obj, ...{
            



                'archive_existing_versions': obj.archiveExistingVersions,

        }};

        delete (jsonObj as Partial<TransitionModelVersionStageDetails>).archiveExistingVersions;
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: TransitionModelVersionStageDetails): object {
        const jsonObj = {...obj, ...{
            



                'archiveExistingVersions': (obj as any)["archive_existing_versions"],

         }};

        delete (jsonObj as any)["archive_existing_versions"];
        
        return jsonObj;
    }
}
