/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The data to update a tool.
*/
export interface UpdateToolDetails {
    /**
    * Tool name.
    */
    'displayName'?: string;
    /**
    * Tool description.
    */
    'description'?: string;
    /**
    * A list of key-value pairs to use for configuring the tool
    */
    'properties'?: { [key: string]: any; };

   "toolType": string;
}

export namespace UpdateToolDetails {




    export function getJsonObj(obj: UpdateToolDetails): object {
        const jsonObj = {...obj, ...{
            



        }};

        
        
        if (obj && "toolType" in obj && obj.toolType) {
            switch (obj.toolType) {
                case "CUSTOM":
                    return model.UpdateCustomToolDetails.getJsonObj(<model.UpdateCustomToolDetails>(<object>jsonObj), true);
                case "HTTP":
                    return model.UpdateHttpToolDetails.getJsonObj(<model.UpdateHttpToolDetails>(<object>jsonObj), true);
                case "PROMPT":
                    return model.UpdatePromptToolDetails.getJsonObj(<model.UpdatePromptToolDetails>(<object>jsonObj), true);
                case "RAG":
                    return model.UpdateRagToolDetails.getJsonObj(<model.UpdateRagToolDetails>(<object>jsonObj), true);
                case "SQL":
                    return model.UpdateSqlToolDetails.getJsonObj(<model.UpdateSqlToolDetails>(<object>jsonObj), true);
                case "NL2SQL":
                    return model.UpdateNlToSqlToolDetails.getJsonObj(<model.UpdateNlToSqlToolDetails>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.toolType}`)

        }
        }
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateToolDetails): object {
        const jsonObj = {...obj, ...{
            



         }};

        
        
        if (obj && "toolType" in obj && obj.toolType) {
            switch (obj.toolType) {
                case "CUSTOM":
                    return model.UpdateCustomToolDetails.getDeserializedJsonObj(<model.UpdateCustomToolDetails>(<object>jsonObj), true);
                case "HTTP":
                    return model.UpdateHttpToolDetails.getDeserializedJsonObj(<model.UpdateHttpToolDetails>(<object>jsonObj), true);
                case "PROMPT":
                    return model.UpdatePromptToolDetails.getDeserializedJsonObj(<model.UpdatePromptToolDetails>(<object>jsonObj), true);
                case "RAG":
                    return model.UpdateRagToolDetails.getDeserializedJsonObj(<model.UpdateRagToolDetails>(<object>jsonObj), true);
                case "SQL":
                    return model.UpdateSqlToolDetails.getDeserializedJsonObj(<model.UpdateSqlToolDetails>(<object>jsonObj), true);
                case "NL2SQL":
                    return model.UpdateNlToSqlToolDetails.getDeserializedJsonObj(<model.UpdateNlToSqlToolDetails>(<object>jsonObj), true);
                default:
                    if (common.LOG.logger) common.LOG.logger.info(`Unknown value for: ${obj.toolType}`)
        }
        }
        return jsonObj;
    }
}
