/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The data to update a Agent flow.
*/
export interface UpdateAgentFlowDetails {
    /**
    * AgentFlow name.
    */
    'displayName'?: string;
    /**
    * AgentFlow description.
    */
    'description'?: string;
    /**
    * The key of the Agent Flow Compute associated with this Agent Flow
    */
    'computeKey'?: string;
    'diagram'?: model.AgentFlowDiagram;
    /**
    * The path to project entry file
    */
    'entryFilePath'?: string;
    /**
    * The path to dependencies file
    */
    'dependenciesFilePath'?: string;
    /**
    * List of node keys that were removed from the flow.
    */
    'deletedNodes'?: Array<string>;
    /**
    * List of node keys that were updated in the flow.
    */
    'updatedNodes'?: Array<string>;
    /**
    * List of node keys that were newly added to the flow.
    */
    'addedNodes'?: Array<string>;
    'guardrails'?: model.GuardrailsConfiguration;
    'sessionConfig'?: model.SessionConfiguration;

}

export namespace UpdateAgentFlowDetails {












    export function getJsonObj(obj: UpdateAgentFlowDetails): object {
        const jsonObj = {...obj, ...{
            



                'diagram': obj.diagram ?
                
                
                model.AgentFlowDiagram.getJsonObj(obj.diagram) : undefined,





                'guardrails': obj.guardrails ?
                
                
                model.GuardrailsConfiguration.getJsonObj(obj.guardrails) : undefined,
                'sessionConfig': obj.sessionConfig ?
                
                
                model.SessionConfiguration.getJsonObj(obj.sessionConfig) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateAgentFlowDetails): object {
        const jsonObj = {...obj, ...{
            



                    'diagram': obj.diagram ?
                
                
                model.AgentFlowDiagram.getDeserializedJsonObj(obj.diagram) : undefined,





                    'guardrails': obj.guardrails ?
                
                
                model.GuardrailsConfiguration.getDeserializedJsonObj(obj.guardrails) : undefined,
                    'sessionConfig': obj.sessionConfig ?
                
                
                model.SessionConfiguration.getDeserializedJsonObj(obj.sessionConfig) : undefined,
         }};

        
        
        return jsonObj;
    }
}
