/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The information to be updated for KnowledgeBase source.
*/
export interface UpdateKnowledgeBaseSourceUpdateDetailsItem {
    /**
    * Source update action type
    */
    'action': model.KnowledgeBaseSourceUpdateOperationType;
    'updateKnowledgeBaseAddSourceDetails'?: model.UpdateKnowledgeBaseAddSourceDetails;
    'updateKnowledgeBaseDeleteSourceDetails'?: model.UpdateKnowledgeBaseDeleteSourceDetails;

}

export namespace UpdateKnowledgeBaseSourceUpdateDetailsItem {




    export function getJsonObj(obj: UpdateKnowledgeBaseSourceUpdateDetailsItem): object {
        const jsonObj = {...obj, ...{
            

                'updateKnowledgeBaseAddSourceDetails': obj.updateKnowledgeBaseAddSourceDetails ?
                
                
                model.UpdateKnowledgeBaseAddSourceDetails.getJsonObj(obj.updateKnowledgeBaseAddSourceDetails) : undefined,
                'updateKnowledgeBaseDeleteSourceDetails': obj.updateKnowledgeBaseDeleteSourceDetails ?
                
                
                model.UpdateKnowledgeBaseDeleteSourceDetails.getJsonObj(obj.updateKnowledgeBaseDeleteSourceDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateKnowledgeBaseSourceUpdateDetailsItem): object {
        const jsonObj = {...obj, ...{
            

                    'updateKnowledgeBaseAddSourceDetails': obj.updateKnowledgeBaseAddSourceDetails ?
                
                
                model.UpdateKnowledgeBaseAddSourceDetails.getDeserializedJsonObj(obj.updateKnowledgeBaseAddSourceDetails) : undefined,
                    'updateKnowledgeBaseDeleteSourceDetails': obj.updateKnowledgeBaseDeleteSourceDetails ?
                
                
                model.UpdateKnowledgeBaseDeleteSourceDetails.getDeserializedJsonObj(obj.updateKnowledgeBaseDeleteSourceDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
