/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details required to update the deployment of an Agent Flow.
*/
export interface UpdateAgentFlowDeploymentDetails {
    /**
    * Display name.
    */
    'displayName'?: string;
    /**
    * deployment description.
    */
    'description'?: string;
    /**
    * The key of the Agent Flow Compute associated with this Agent Flow
    */
    'agentFlowComputeKey'?: string;
    /**
    * The unique identifier (UUID) of the Agent flow
    */
    'agentFlowKey': string;
    /**
    * Type of an Agent Flow Deployment.
    */
    'deploymentType': model.DeploymentType;
    'oAuthConfig'?: model.OAuthConfiguration;

}

export namespace UpdateAgentFlowDeploymentDetails {







    export function getJsonObj(obj: UpdateAgentFlowDeploymentDetails): object {
        const jsonObj = {...obj, ...{
            





                'oAuthConfig': obj.oAuthConfig ?
                
                
                model.OAuthConfiguration.getJsonObj(obj.oAuthConfig) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateAgentFlowDeploymentDetails): object {
        const jsonObj = {...obj, ...{
            





                    'oAuthConfig': obj.oAuthConfig ?
                
                
                model.OAuthConfiguration.getDeserializedJsonObj(obj.oAuthConfig) : undefined,
         }};

        
        
        return jsonObj;
    }
}
