/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The data to update a view.
*/
export interface UpdateViewDetails {
    /**
    * The mode of update for a view
    */
    'updateMode': UpdateViewDetails.UpdateMode;
    'viewUpdateDetails'?: model.ViewUpdateDetails;

}

export namespace UpdateViewDetails {

    export enum UpdateMode {
    
    RenameView = "RENAME_VIEW",
    AddProperties = "ADD_PROPERTIES",
    DropProperties = "DROP_PROPERTIES",
    UpdateViewDescription = "UPDATE_VIEW_DESCRIPTION",
    UpdateViewQuery = "UPDATE_VIEW_QUERY",
    UpdateColumnDescription = "UPDATE_COLUMN_DESCRIPTION"

}



    export function getJsonObj(obj: UpdateViewDetails): object {
        const jsonObj = {...obj, ...{
            

                'viewUpdateDetails': obj.viewUpdateDetails ?
                
                
                model.ViewUpdateDetails.getJsonObj(obj.viewUpdateDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateViewDetails): object {
        const jsonObj = {...obj, ...{
            

                    'viewUpdateDetails': obj.viewUpdateDetails ?
                
                
                model.ViewUpdateDetails.getDeserializedJsonObj(obj.viewUpdateDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
