/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The information to be updated.
*/
export interface UpdateKnowledgeBaseDetails {
    /**
    * The update operation we want to perform on KnowledgeBase.
    */
    'action': model.KnowledgeBaseUpdateOperationType;
    'indexDetails'?: model.KnowledgeBaseVectorIndexDetails;
    'updateKnowledgeBaseMetadataUpdateDetails'?: model.UpdateKnowledgeBaseMetadataUpdateDetails;
    'updateKnowledgeBaseSourceUpdateDetails'?: model.UpdateKnowledgeBaseSourceUpdateDetails;

}

export namespace UpdateKnowledgeBaseDetails {





    export function getJsonObj(obj: UpdateKnowledgeBaseDetails): object {
        const jsonObj = {...obj, ...{
            

                'indexDetails': obj.indexDetails ?
                
                
                model.KnowledgeBaseVectorIndexDetails.getJsonObj(obj.indexDetails) : undefined,
                'updateKnowledgeBaseMetadataUpdateDetails': obj.updateKnowledgeBaseMetadataUpdateDetails ?
                
                
                model.UpdateKnowledgeBaseMetadataUpdateDetails.getJsonObj(obj.updateKnowledgeBaseMetadataUpdateDetails) : undefined,
                'updateKnowledgeBaseSourceUpdateDetails': obj.updateKnowledgeBaseSourceUpdateDetails ?
                
                
                model.UpdateKnowledgeBaseSourceUpdateDetails.getJsonObj(obj.updateKnowledgeBaseSourceUpdateDetails) : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: UpdateKnowledgeBaseDetails): object {
        const jsonObj = {...obj, ...{
            

                    'indexDetails': obj.indexDetails ?
                
                
                model.KnowledgeBaseVectorIndexDetails.getDeserializedJsonObj(obj.indexDetails) : undefined,
                    'updateKnowledgeBaseMetadataUpdateDetails': obj.updateKnowledgeBaseMetadataUpdateDetails ?
                
                
                model.UpdateKnowledgeBaseMetadataUpdateDetails.getDeserializedJsonObj(obj.updateKnowledgeBaseMetadataUpdateDetails) : undefined,
                    'updateKnowledgeBaseSourceUpdateDetails': obj.updateKnowledgeBaseSourceUpdateDetails ?
                
                
                model.UpdateKnowledgeBaseSourceUpdateDetails.getDeserializedJsonObj(obj.updateKnowledgeBaseSourceUpdateDetails) : undefined,
         }};

        
        
        return jsonObj;
    }
}
