/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The response object for validating the agent flow json
*/
export interface ValidateAgentFlowResponse {
    /**
    * true if valid, else false
    */
    'isValidAgentFlow': boolean;
    /**
    * List of validation errors encountered in the diagram.
    */
    'validationError'?: Array<model.ValidationError>;

}

export namespace ValidateAgentFlowResponse {



    export function getJsonObj(obj: ValidateAgentFlowResponse): object {
        const jsonObj = {...obj, ...{
            

                'validationError': obj.validationError ?
                
                obj.validationError.map((item)=>{return model.ValidationError.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ValidateAgentFlowResponse): object {
        const jsonObj = {...obj, ...{
            

                    'validationError': obj.validationError ?
                
                obj.validationError.map((item)=>{return model.ValidationError.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
