/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* The details for updating a view.
*/
export interface ViewUpdateDetails {
    /**
    * A user-friendly name. Has to be unique within the scope of the schema and is changeable.
    */
    'displayName'?: string;
    /**
    * The description of the view.
    */
    'description'?: string;
    /**
    * The Query used to create the view.
    */
    'viewText'?: string;
    /**
    * Columns for view.
    */
    'viewFields'?: Array<model.ViewFieldDetails>;
    /**
    * View Properties.
    */
    'addViewProperties'?: Array<model.ViewProperty>;
    /**
    * View Properties.
    */
    'dropViewProperties'?: Array<model.ViewProperty>;

}

export namespace ViewUpdateDetails {







    export function getJsonObj(obj: ViewUpdateDetails): object {
        const jsonObj = {...obj, ...{
            



                'viewFields': obj.viewFields ?
                
                obj.viewFields.map((item)=>{return model.ViewFieldDetails.getJsonObj(item)})
                
                 : undefined,
                'addViewProperties': obj.addViewProperties ?
                
                obj.addViewProperties.map((item)=>{return model.ViewProperty.getJsonObj(item)})
                
                 : undefined,
                'dropViewProperties': obj.dropViewProperties ?
                
                obj.dropViewProperties.map((item)=>{return model.ViewProperty.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ViewUpdateDetails): object {
        const jsonObj = {...obj, ...{
            



                    'viewFields': obj.viewFields ?
                
                obj.viewFields.map((item)=>{return model.ViewFieldDetails.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'addViewProperties': obj.addViewProperties ?
                
                obj.addViewProperties.map((item)=>{return model.ViewProperty.getDeserializedJsonObj(item)})
                
                 : undefined,
                    'dropViewProperties': obj.dropViewProperties ?
                
                obj.dropViewProperties.map((item)=>{return model.ViewProperty.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
