/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Parsed view select query post validation.
*/
export interface ViewSqlParseDetails {
    /**
    * Flag to indicate whether given view SQL is valid or not.
    */
    'isQueryValid': boolean;
    /**
    * Error message if given view SQL is not valid.
    */
    'queryParseErrorMessage'?: string;
    /**
    * Columns for view.
    */
    'viewFields'?: Array<model.ViewFieldDetails>;

}

export namespace ViewSqlParseDetails {




    export function getJsonObj(obj: ViewSqlParseDetails): object {
        const jsonObj = {...obj, ...{
            


                'viewFields': obj.viewFields ?
                
                obj.viewFields.map((item)=>{return model.ViewFieldDetails.getJsonObj(item)})
                
                 : undefined,
        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: ViewSqlParseDetails): object {
        const jsonObj = {...obj, ...{
            


                    'viewFields': obj.viewFields ?
                
                obj.viewFields.map((item)=>{return model.ViewFieldDetails.getDeserializedJsonObj(item)})
                
                 : undefined,
         }};

        
        
        return jsonObj;
    }
}
