/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Summary information about a volume.
*/
export interface VolumeSummary {
    /**
    * The key of the volume.
    */
    'key': string;
    /**
    * A user-friendly name. Has to be unique within the schema and is changeable.
    */
    'displayName': string;
    /**
    * Short description of the volume
    */
    'description'?: string;
    /**
    * The date and time the Data Lake Volume was created, in the format defined by <a href=\"https://tools.ietf.org/html/rfc3339\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 3339</a>.
* Example: {@code 2016-08-25T21:10:29.600Z}
* 
    */
    'timeCreated': Date;
    /**
    * The date and time the Data Lake Volume was updated, in the format defined by <a href=\"https://tools.ietf.org/html/rfc3339\" target=\"_blank\" rel=\"noopener noreferrer\">RFC 3339</a>.
* Example: {@code 2016-08-25T21:10:29.600Z}
* 
    */
    'timeUpdated'?: Date;
    /**
    * The ID of the user that created the volume.
* 
    */
    'createdBy'?: string;
    /**
    * The ID of the user that last updated the volume
* 
    */
    'updatedBy'?: string;
    /**
    * The fully qualified name of this volume.
    */
    'fullName'?: string;
    /**
    * The type of volume.
    */
    'volumeType'?: VolumeSummary.VolumeType;
    /**
    * The current state of the volume.
    */
    'lifecycleState'?: string;
    /**
    * Additional details associated with the lifecycle state.
    */
    'lifecycleStateDetails'?: string;
    /**
    * System tags for this resource. Each key is predefined and scoped to a namespace.
* <p>
Example: {@code {\"orcl-cloud\": {\"free-tier-retained\": \"true\"}}}
* 
    */
    'systemTags'?: { [key: string]: { [key: string]: any; }; };

}

export namespace VolumeSummary {









    export enum VolumeType {
    
    Managed = "MANAGED",
    External = "EXTERNAL",
    /**
    * This value is used if a service returns a value for this enum that is not recognized by this
    * version of the SDK.
    */
    UnknownValue = "UNKNOWN_VALUE"
}





    export function getJsonObj(obj: VolumeSummary): object {
        const jsonObj = {...obj, ...{
            












        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: VolumeSummary): object {
        const jsonObj = {...obj, ...{
            












         }};

        
        
        return jsonObj;
    }
}
