/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Details of a volume file installed as a library on a cluster.
*/
export interface VolumeFileClusterLibrarySummary extends model.ClusterLibrarySummary {
    /**
    * Library name.
    */
    'name'?: string;
    /**
    * Full path of the library.
    */
    'path'?: string;

   "type": string;
}

export namespace VolumeFileClusterLibrarySummary {



    export function getJsonObj(obj: VolumeFileClusterLibrarySummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ClusterLibrarySummary.getJsonObj(obj) as VolumeFileClusterLibrarySummary, ...{
            


        }};

        
        
        return jsonObj;
    }
    export const type = 'VOLUME_FILE';
    export function getDeserializedJsonObj(obj: VolumeFileClusterLibrarySummary, isParentJsonObj?: boolean): object {
        const jsonObj = {...isParentJsonObj? obj : model.ClusterLibrarySummary.getDeserializedJsonObj(obj) as VolumeFileClusterLibrarySummary, ...{
            


         }};

        
        
        return jsonObj;
    }
}
