/**
 * AI Data Platform Data Plane API
 * Use the AI Data Platform Data Plane API to manage workspaces and objects in the workspace.
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");


/**
* Worker configuration.
*/
export interface WorkerConfig {
    /**
    * Shape of the compute cluster executor instance.
    */
    'workerShape'?: string;
    'workerShapeConfig'?: model.ShapeConfig;
    /**
    * Minimum number of workers. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'minWorkerCount'?: number;
    /**
    * Maximum number of workers. When this property is specified, the cluster is auto-scaled. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
    */
    'maxWorkerCount'?: number;

}

export namespace WorkerConfig {





    export function getJsonObj(obj: WorkerConfig): object {
        const jsonObj = {...obj, ...{
            

                'workerShapeConfig': obj.workerShapeConfig ?
                
                
                model.ShapeConfig.getJsonObj(obj.workerShapeConfig) : undefined,


        }};

        
        
        return jsonObj;
    }
    ;
    export function getDeserializedJsonObj(obj: WorkerConfig): object {
        const jsonObj = {...obj, ...{
            

                    'workerShapeConfig': obj.workerShapeConfig ?
                
                
                model.ShapeConfig.getDeserializedJsonObj(obj.workerShapeConfig) : undefined,


         }};

        
        
        return jsonObj;
    }
}
