/**
 * 
 * 
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * @example Click {@link https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/latest/aidp/GetAiDataPlatformGitDiffDetail.ts.html |here} to see how to use GetAiDataPlatformGitDiffDetailRequest.
 */
export interface GetAiDataPlatformGitDiffDetailRequest extends common.BaseRequest {
/**
 * The [OCID]({{DOC_SERVER_URL}}/iaas/Content/General/Concepts/identifiers.htm) of the AI Data Platform (Data Lake) instance.
 */
 'aiDataPlatformId': string;
/**
 * The key of the Workspace
 */
 'workspaceKey': string;
/**
 * The git repository key
 */
 'gitRepositoryKey': string;
/**
 * The git folder path
 */
 'gitFolderPath': string;
/**
 * Expected branch name for the folder context.
 */
 'branchName': string;
/**
 * File path relative to repository root.
 */
 'gitFilePath': string;
/**
 * Number of context lines to include in the diff.
 */
 'contextLines'?: number;
/**
 * Maximum number of bytes of diff output to return.
 */
 'maxPatchBytes'?: number;
/**
 * Unique Oracle-assigned identifier for the request. If you need to contact
* Oracle about a particular request, please provide the request ID.
* The only valid characters for request IDs are letters, numbers,
* underscore, and dash.
* 
 */
 'opcRequestId'?: string;
}

