/**
 * 
 * 
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * @example Click {@link https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/latest/aidp/ListAiDataPlatformTaskRuns.ts.html |here} to see how to use ListAiDataPlatformTaskRunsRequest.
 */
export interface ListAiDataPlatformTaskRunsRequest extends common.BaseRequest {
/**
 * The [OCID]({{DOC_SERVER_URL}}/iaas/Content/General/Concepts/identifiers.htm) of the AI Data Platform (Data Lake) instance.
 */
 'aiDataPlatformId': string;
/**
 * The key of the Workspace
 */
 'workspaceKey': string;
/**
 * The field to filter based on job run key.
 */
 'jobRunKey': string;
/**
 * A filter to return only resources that match the given display name exactly.
 */
 'displayName'?: string;
/**
 * The field to filter based on state.
 */
 'status'?: Array<ListAiDataPlatformTaskRunsRequest.Status>;
/**
 * The field to filter based on parent job run key.
 */
 'parentJobRunKey'?: string;
/**
 * The field to filter based on root job run key.
 */
 'rootJobRunKey'?: string;
/**
 * For list pagination. The maximum number of results per page, or items to return in a
* paginated \"List\" call. For important details about how pagination works, see
* [List Pagination]({{DOC_SERVER_URL}}/iaas/Content/API/Concepts/usingapi.htm#nine).
* 
 */
 'limit'?: number;
/**
 * For list pagination. The value of the opc-next-page response header from the previous
* \"List\" call. For important details about how pagination works, see
* [List Pagination]({{DOC_SERVER_URL}}/iaas/Content/API/Concepts/usingapi.htm#nine).
* 
 */
 'page'?: string;
/**
 * The sort order to use, either ascending ({@code ASC}) or descending ({@code DESC}).
 */
 'sortOrder'?: model.SortOrder;
/**
 * The field to sort by. You can provide only one sort order. Default order for {@code timeCreated} is descending. Default order for {@code displayName} is ascending.
 */
 'sortBy'?: ListAiDataPlatformTaskRunsRequest.SortBy;
/**
 * Unique Oracle-assigned identifier for the request. If you need to contact
* Oracle about a particular request, please provide the request ID.
* The only valid characters for request IDs are letters, numbers,
* underscore, and dash.
* 
 */
 'opcRequestId'?: string;
}

export namespace ListAiDataPlatformTaskRunsRequest {

  export enum Status {
    Pending = ("PENDING"),
    Running = ("RUNNING"),
    Skipped = ("SKIPPED"),
    InternalError = ("INTERNAL_ERROR"),
    Blocked = ("BLOCKED"),
    Success = ("SUCCESS"),
    Failed = ("FAILED"),
    Canceled = ("CANCELED"),
    UpstreamCanceled = ("UPSTREAM_CANCELED"),
    UpstreamFailed = ("UPSTREAM_FAILED"),
    Excluded = ("EXCLUDED")
  }

  export enum SortBy {
    TimeCreated = ("timeCreated"),
    DisplayName = ("displayName"),
    Status = ("status")
  }

}
