/**
 * 
 * 
 * OpenAPI spec version: 20260430
 * 
 *
 * NOTE: This class is auto generated by OracleSDKGenerator.
 * Do not edit the class manually.
 *
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates.  All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

import * as model from '../model';
import common = require("oci-common");

/**
 * @example Click {@link https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/latest/aidp/UploadAiDataPlatformWorkspaceObjectWithPar.ts.html |here} to see how to use UploadAiDataPlatformWorkspaceObjectWithParRequest.
 */
export interface UploadAiDataPlatformWorkspaceObjectWithParRequest extends common.BaseRequest {
/**
 * The [OCID]({{DOC_SERVER_URL}}/iaas/Content/General/Concepts/identifiers.htm) of the AI Data Platform (Data Lake) instance.
 */
 'aiDataPlatformId': string;
/**
 * The key of the Workspace
 */
 'workspaceKey': string;
/**
 * Contents of the file to upload.
 */
 'uploadFileWithParDetails':  model.UploadFileWithParDetails;
/**
 * The absolute path of the file or folder
 */
 'path': string;
/**
 * A boolean which decides if overwrite is allowed
 */
 'isOverwrite'?: boolean;
/**
 * A flag to identify if the recent list should be updated.
 */
 'shouldUpdateRecent'?: boolean;
/**
 * A token that uniquely identifies a request so it can be retried in case of a timeout or
* server error without risk of running that same action again. Retry tokens expire after 24
* hours, but can be invalidated before then due to conflicting operations. For example, if a resource
* has been deleted and removed from the system, then a retry of the original creation request
* might be rejected.
* 
 */
 'opcRetryToken'?: string;
/**
 * Unique Oracle-assigned identifier for the request. If you need to contact
* Oracle about a particular request, please provide the request ID.
* The only valid characters for request IDs are letters, numbers,
* underscore, and dash.
* 
 */
 'opcRequestId'?: string;
/**
 * The type of workspace object.
 */
 'type'?: string;
/**
 * The description of the workspace object
 */
 'objectDescription'?: string;
}

